"use client";import Link from "next/link";import {useEffect,useState} from "react";import {useParams} from "next/navigation";
const defaults={logo:"",primary:"#111827",accent:"#22c55e",heroTitle:"مرحبا بكم فالمتجر ديالنا",heroText:"منتجات مختارة بعناية، والدفع عند الاستلام.",heroButton:"تسوق الآن",announcement:"🚚 التوصيل لجميع المدن فالمغرب",showAnnouncement:true,showProducts:true,showTrust:true,showFooter:true,heroImage:"",selectedProductIds:[],collectionTitle:"Nos produits",sectionOrder:["hero","products","trust"]};
export default function StoreBuilder(){const p=useParams<{id:string}>(),[store,setStore]=useState<any>(null),[settings,setSettings]=useState<any>(defaults),[products,setProducts]=useState<any[]>([]),[saving,setSaving]=useState(false),[tab,setTab]=useState("general");
useEffect(()=>{Promise.all([fetch("/api/stores/"+p.id,{cache:"no-store"}).then(r=>r.json()),fetch("/api/products?limit=12",{cache:"no-store"}).then(r=>r.json())]).then(([a,b])=>{if(a.store){setStore(a.store);setSettings({...defaults,...(a.store.settings||{}),selectedProductIds:Array.isArray(a.store.settings?.selectedProductIds)?a.store.settings.selectedProductIds:[]})}setProducts(b.products||[])})},[p.id]);
async function save(status?:string){if(!store)return;setSaving(true);const r=await fetch("/api/stores/"+store.id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:store.name,locale:store.locale,templateId:store.template_id,settings,status})}),x=await r.json();setSaving(false);if(!r.ok)return alert(x.error||"Erreur");setStore(x.store);if(status==="PUBLISHED")alert("Boutique publiée.");}
if(!store)return <main className="store-builder-loading">Chargement du Store Builder…</main>;
return <main className="store-builder-shell"><aside className="store-builder-side"><div className="store-builder-brand"><Link href="/stores">← Stores</Link><b>LandPro Store Builder</b><small>{store.status==="PUBLISHED"?"PUBLIÉ":"BROUILLON"}</small></div><div className="store-builder-tabs">{[["general","⚙","Général"],["design","◐","Design"],["hero","▣","Hero"],["catalog","◇","Produits"],["sections","☷","Sections"]].map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}><span>{x[1]}</span>{x[2]}</button>)}</div></aside>
<section className="store-builder-controls"><header><div><small>ÉDITEUR</small><h1>{store.name}</h1></div><div><button className="ghost-btn" onClick={()=>save()} disabled={saving}>{saving?"Enregistrement…":"Enregistrer"}</button><button className="new-page-btn" onClick={()=>save("PUBLISHED")}>Publier</button></div></header>
{tab==="general"&&<div className="store-settings-card"><h2>Informations boutique</h2><label>Nom<input value={store.name} onChange={e=>setStore({...store,name:e.target.value})}/></label><label>Langue<select value={store.locale} onChange={e=>setStore({...store,locale:e.target.value})}><option value="darija">Darija Maroc</option><option value="ar">العربية</option><option value="fr">Français</option></select></label><label>Annonce<input value={settings.announcement} onChange={e=>setSettings({...settings,announcement:e.target.value})}/></label></div>}
{tab==="design"&&<div className="store-settings-card"><h2>Identité visuelle</h2><label>Logo URL<input value={settings.logo} onChange={e=>setSettings({...settings,logo:e.target.value})} placeholder="https://..."/></label><div className="store-color-grid"><label>Couleur principale<input type="color" value={settings.primary} onChange={e=>setSettings({...settings,primary:e.target.value})}/></label><label>Couleur CTA<input type="color" value={settings.accent} onChange={e=>setSettings({...settings,accent:e.target.value})}/></label></div></div>}
{tab==="hero"&&<div className="store-settings-card"><h2>Hero</h2><label>Titre<input value={settings.heroTitle} onChange={e=>setSettings({...settings,heroTitle:e.target.value})}/></label><label>Description<textarea value={settings.heroText} onChange={e=>setSettings({...settings,heroText:e.target.value})}/></label><label>Bouton<input value={settings.heroButton} onChange={e=>setSettings({...settings,heroButton:e.target.value})}/></label><label>Image Hero URL<input value={settings.heroImage||""} onChange={e=>setSettings({...settings,heroImage:e.target.value})} placeholder="https://..."/></label></div>}
{tab==="catalog"&&<div className="store-settings-card"><h2>Catalogue de la boutique</h2><p>Sélectionne les produits à afficher. Si aucun produit n’est sélectionné, tous les produits actifs seront affichés.</p><label>Titre de la collection<input value={settings.collectionTitle||""} onChange={e=>setSettings({...settings,collectionTitle:e.target.value})}/></label><div className="store-builder-products selectable">{products.map(x=>{const checked=(settings.selectedProductIds||[]).includes(x.id);return <label key={x.id} className={checked?"selected":""}><input type="checkbox" checked={checked} onChange={e=>setSettings({...settings,selectedProductIds:e.target.checked?[...(settings.selectedProductIds||[]),x.id]:(settings.selectedProductIds||[]).filter((id:string)=>id!==x.id)})}/>{x.image?<img src={x.image} alt=""/>:<span>PR</span>}<b>{x.name}</b><small>{x.price} MAD</small></label>})}</div><Link className="store-builder-link" href="/products">+ Gérer mes produits</Link></div>}
{tab==="sections"&&<div className="store-settings-card"><h2>Sections visibles</h2>{[["showAnnouncement","Barre d’annonce"],["showProducts","Catalogue produits"],["showTrust","Arguments de confiance"],["showFooter","Footer"]].map(x=><label className="store-toggle" key={x[0]}><span>{x[1]}</span><input type="checkbox" checked={!!settings[x[0]]} onChange={e=>setSettings({...settings,[x[0]]:e.target.checked})}/></label>)}</div>}
</section>
<section className="store-builder-preview"><div className="store-preview-label"><b>Aperçu boutique</b><span>Desktop</span></div><div className="store-live" style={{"--store-primary":settings.primary,"--store-accent":settings.accent} as any} dir={store.locale==="fr"?"ltr":"rtl"}>{settings.showAnnouncement&&<div className="store-live-announcement">{settings.announcement}</div>}<header>{settings.logo?<img src={settings.logo} alt="logo"/>:<b>{store.name}</b>}<nav>{store.locale==="fr"?"Accueil · Produits · Contact":"الرئيسية · المنتجات · تواصل معنا"}</nav></header><div className="store-live-hero" style={settings.heroImage?{backgroundImage:`linear-gradient(rgba(248,250,252,.88),rgba(248,250,252,.88)),url(${settings.heroImage})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined}><small>LANDPRO STORE</small><h2>{settings.heroTitle}</h2><p>{settings.heroText}</p><button>{settings.heroButton}</button></div>{settings.showProducts&&<div className="store-live-catalog"><h3>{store.locale==="fr"?"Nos produits":"منتجاتنا"}</h3><div>{products.filter(x=>!(settings.selectedProductIds||[]).length||(settings.selectedProductIds||[]).includes(x.id)).slice(0,3).map(x=><article key={x.id}>{x.image?<img src={x.image} alt=""/>:<i/>}<b>{x.name}</b><span>{x.price} DH</span></article>)}</div></div>}{settings.showTrust&&<div className="store-live-trust"><span>🚚 Livraison Maroc</span><span>💵 COD</span><span>✓ Qualité</span></div>}{settings.showFooter&&<footer><b>{store.name}</b><small>© {new Date().getFullYear()} · LandPro Store</small></footer>}</div></section></main>}