"use client";import {useMemo,useRef,useState} from "react";import {createBuilderV3} from "../../../lib/builder-v3";
const library=["hero","order","benefits","problem","features","how","trust","faq"];const labels:any={hero:"Hero",order:"Formulaire COD",benefits:"Bénéfices",problem:"Problème / Solution",features:"Caractéristiques",how:"Comment ça marche",trust:"Confiance",faq:"FAQ"};
export default function BuilderV3({draft,editing,onChange,onSave,onClose}:{draft:any;editing:any;onChange:(v:any)=>void;onSave:(publish:boolean)=>void;onClose:()=>void}){const [selected,setSelected]=useState("hero"),[viewport,setViewport]=useState<"desktop"|"tablet"|"mobile">("desktop"),[showLibrary,setShowLibrary]=useState(false),[history,setHistory]=useState<any[]>([]),[future,setFuture]=useState<any[]>([]);const drag=useRef<string|null>(null);const doc=useMemo(()=>createBuilderV3(draft),[draft]);const ds=draft.design_system||{},colors=ds.tokens?.colors||{},fonts=ds.tokens?.fonts||{};const commit=(next:any)=>{setHistory(h=>[...h.slice(-29),draft]);setFuture([]);onChange(next)};const patch=(k:string,v:any)=>commit({...draft,[k]:v,builder_v3:{...doc,viewport}});
const setOrder=(order:string[])=>commit({...draft,section_order:order,builder_v3:{...doc,blocks:order.map(id=>doc.blocks.find(b=>b.id===id)||{id,type:id,visible:true,props:{}}),viewport}});
const move=(from:string,to:string)=>{if(from===to)return;const a=[...(draft.section_order||doc.blocks.map(b=>b.id))],i=a.indexOf(from),j=a.indexOf(to);if(i<0||j<0)return;a.splice(j,0,a.splice(i,1)[0]);setOrder(a)};
const add=(id:string)=>{const a=[...(draft.section_order||doc.blocks.map(b=>b.id))];if(!a.includes(id))a.push(id);commit({...draft,section_order:a,hidden_sections:(draft.hidden_sections||[]).filter((x:string)=>x!==id)});setSelected(id);setShowLibrary(false)};
const remove=(id:string)=>{if(id==="hero"||id==="order")return;commit({...draft,section_order:(draft.section_order||[]).filter((x:string)=>x!==id)});setSelected("hero")};
const duplicate=(id:string)=>{const src=doc.blocks.find(b=>b.id===id);if(!src||!id.startsWith("custom-"))return;const nid="custom-"+Date.now();commit({...draft,section_order:[...(draft.section_order||[]),nid],custom_sections:{...(draft.custom_sections||{}),[nid]:{...(draft.custom_sections?.[id]||{}),title:(draft.custom_sections?.[id]?.title||"Section")+" copie"}}});setSelected(nid)};
const undo=()=>{const prev=history.at(-1);if(!prev)return;setHistory(h=>h.slice(0,-1));setFuture(f=>[draft,...f]);onChange(prev)};const redo=()=>{const next=future[0];if(!next)return;setFuture(f=>f.slice(1));setHistory(h=>[...h,draft]);onChange(next)};
const blocks=doc.blocks.filter(b=>b.visible);
const list=(key:string)=>Array.isArray(draft[key])?draft[key]:[];const cards=(key:string)=><div className="bv3-cards">{list(key).map((x:any,i:number)=><article key={i}><b>{typeof x==="string"?x:x?.title||x?.question||""}</b>{typeof x!=="string"&&x?.text&&<p>{x.text}</p>}</article>)}</div>;
const render=(id:string)=>{if(id==="hero")return <section className="bv3-hero"><div className="bv3-hero-copy"><span className="bv3-kicker">COD MAROC</span><h1>{draft.headline||editing?.name}</h1><p>{draft.subheadline}</p><div className="bv3-price"><strong>{draft.price||0} DH</strong>{draft.oldPrice&&<s>{draft.oldPrice} DH</s>}</div><button>{draft.cta||"Commander maintenant"}</button></div><div className="bv3-hero-media">{(draft.images||draft.product_images||[])[0]?<img src={(draft.images||draft.product_images)[0]} alt=""/>:<span>Image produit</span>}</div></section>;
if(id==="order")return <section className="bv3-order"><div><span className="bv3-kicker">COMMANDE</span><h2>{draft.order_title||"Commandez maintenant"}</h2><p>{draft.delivery||"Paiement à la livraison"}</p></div><div className="bv3-order-card"><input placeholder="Nom complet"/><input placeholder="Téléphone"/><input placeholder="Ville"/>{draft.order_show_address!==false&&<input placeholder="Adresse"/>}<div className="bv3-total"><span>Total</span><b>{Number(draft.price||0)+Number(draft.delivery_price||0)} DH</b></div><button>{draft.cta||"Commander maintenant"}</button></div></section>;
if(id==="problem")return <section className="bv3-split"><div><span className="bv3-kicker">PROBLÈME</span><h2>{draft.problem_title||""}</h2><p>{draft.problem}</p></div><div className="bv3-solution"><span className="bv3-kicker">SOLUTION</span><p>{draft.solution}</p></div></section>;
if(id==="benefits")return <section><span className="bv3-kicker">BÉNÉFICES</span><h2>{draft.benefits_title||""}</h2><p>{draft.description}</p>{cards("benefits")}</section>;
if(id==="features")return <section><span className="bv3-kicker">CARACTÉRISTIQUES</span><h2>{draft.features_title||""}</h2>{cards("features")}</section>;
if(id==="how")return <section><span className="bv3-kicker">ÉTAPES</span><h2>{draft.how_title||""}</h2><div className="bv3-steps">{list("how_steps").map((x:string,i:number)=><article key={i}><strong>{String(i+1).padStart(2,"0")}</strong><p>{x}</p></article>)}</div></section>;
if(id==="trust")return <section><span className="bv3-kicker">CONFIANCE</span><h2>{draft.trust_title||""}</h2>{cards("trust_points")}</section>;
if(id==="faq")return <section><span className="bv3-kicker">FAQ</span><h2>{draft.faq_title||""}</h2><div className="bv3-faq">{list("faq").map((x:any,i:number)=><details key={i}><summary>{typeof x==="string"?x:x.question}</summary>{typeof x!=="string"&&<p>{x.answer}</p>}</details>)}</div></section>;return <section><h2>{labels[id]||id}</h2></section>};
return <div className="bv3"><header className="bv3-top"><div><b>LandPro Builder V3</b><small>UI/UX Pro Max · WYSIWYG</small></div><div className="bv3-view"><button disabled={!history.length} onClick={undo}>↶</button><button disabled={!future.length} onClick={redo}>↷</button><button onClick={()=>setViewport("desktop")}>Desktop</button><button onClick={()=>setViewport("tablet")}>Tablet</button><button onClick={()=>setViewport("mobile")}>Mobile</button></div><div><button onClick={onClose}>Fermer</button><button onClick={()=>onSave(false)}>Enregistrer</button><button className="primary" onClick={()=>onSave(true)}>Publier</button></div></header><div className="bv3-body"><aside className="bv3-left"><h3>Structure</h3>{blocks.map(b=><div className="bv3-structure-row" draggable onDragStart={()=>drag.current=b.id} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag.current)move(drag.current,b.id);drag.current=null}} key={b.id}><span>⋮⋮</span><button className={selected===b.id?"active":""} onClick={()=>setSelected(b.id)}>{labels[b.id]||b.type}</button>{b.id.startsWith("custom-")&&<button title="Dupliquer" onClick={()=>duplicate(b.id)}>⧉</button>}{b.id!=="hero"&&b.id!=="order"&&<button title="Supprimer" onClick={()=>remove(b.id)}>×</button>}</div>)}<button className="bv3-add" onClick={()=>setShowLibrary(v=>!v)}>+ Ajouter une section</button>{showLibrary&&<div className="bv3-library">{library.filter(id=>!(draft.section_order||[]).includes(id)).map(id=><button key={id} onClick={()=>add(id)}>+ {labels[id]}</button>)}</div>}</aside><main className={"bv3-stage "+viewport}><div className="bv3-page" dir={editing.locale?.startsWith("ar")?"rtl":"ltr"} style={{"--v3-primary":colors.primary,"--v3-accent":colors.accent,"--v3-bg":colors.background,"--v3-fg":colors.foreground,"--v3-card":colors.card,"--v3-border":colors.border,"--v3-radius":ds.tokens?.radius,"--v3-head":fonts.heading,"--v3-body":fonts.body} as any}>{blocks.map(b=><div key={b.id} onClick={()=>setSelected(b.id)} className={"bv3-block "+(selected===b.id?"selected":"")}><span className="bv3-tag">{labels[b.id]||b.type}</span>{render(b.id)}</div>)}</div></main><aside className="bv3-right"><h3>Propriétés · {labels[selected]||selected}</h3>
{selected==="hero"&&<><label>Titre<input value={draft.headline||""} onChange={e=>patch("headline",e.target.value)}/></label><label>Sous-titre<textarea value={draft.subheadline||""} onChange={e=>patch("subheadline",e.target.value)}/></label><label>Prix<input type="number" value={draft.price||""} onChange={e=>patch("price",e.target.value)}/></label><label>Ancien prix<input type="number" value={draft.oldPrice||""} onChange={e=>patch("oldPrice",e.target.value)}/></label><label>CTA<input value={draft.cta||""} onChange={e=>patch("cta",e.target.value)}/></label><label>Image principale<input value={(draft.images||draft.product_images||[])[0]||""} placeholder="URL image" onChange={e=>{const imgs=[...(draft.images||draft.product_images||[])];imgs[0]=e.target.value;patch("images",imgs)}}/></label></>}
{selected==="benefits"&&<><label>Titre<input value={draft.benefits_title||""} onChange={e=>patch("benefits_title",e.target.value)}/></label><label>Description<textarea value={draft.description||""} onChange={e=>patch("description",e.target.value)}/></label><label>Bénéfices · 1 par ligne<textarea value={list("benefits").join("\n")} onChange={e=>patch("benefits",e.target.value.split("\n").filter(Boolean))}/></label></>}
{selected==="features"&&<><label>Titre<input value={draft.features_title||""} onChange={e=>patch("features_title",e.target.value)}/></label><label>Caractéristiques · 1 par ligne<textarea value={list("features").join("\n")} onChange={e=>patch("features",e.target.value.split("\n").filter(Boolean))}/></label></>}
{selected==="how"&&<><label>Titre<input value={draft.how_title||""} onChange={e=>patch("how_title",e.target.value)}/></label><label>Étapes · 1 par ligne<textarea value={list("how_steps").join("\n")} onChange={e=>patch("how_steps",e.target.value.split("\n").filter(Boolean))}/></label></>}
{selected==="problem"&&<><label>Titre<input value={draft.problem_title||""} onChange={e=>patch("problem_title",e.target.value)}/></label><label>Problème<textarea value={draft.problem||""} onChange={e=>patch("problem",e.target.value)}/></label><label>Solution<textarea value={draft.solution||""} onChange={e=>patch("solution",e.target.value)}/></label></>}
{selected==="order"&&<><label>Titre<input value={draft.order_title||""} onChange={e=>patch("order_title",e.target.value)}/></label><label>Texte livraison<input value={draft.delivery||""} onChange={e=>patch("delivery",e.target.value)}/></label><label>CTA<input value={draft.cta||""} onChange={e=>patch("cta",e.target.value)}/></label><label className="bv3-check"><input type="checkbox" checked={draft.order_show_address!==false} onChange={e=>patch("order_show_address",e.target.checked)}/> Afficher adresse</label></>}
{selected==="trust"&&<><label>Titre<input value={draft.trust_title||""} onChange={e=>patch("trust_title",e.target.value)}/></label><label>Points confiance · 1 par ligne<textarea value={list("trust_points").join("\n")} onChange={e=>patch("trust_points",e.target.value.split("\n").filter(Boolean))}/></label></>}
{selected==="faq"&&<><label>Titre<input value={draft.faq_title||""} onChange={e=>patch("faq_title",e.target.value)}/></label><div className="bv3-help">Les questions/réponses existantes sont affichées dans le canvas. L’éditeur FAQ avancé arrive dans le panneau suivant.</div></>}
<hr/><b>Design System</b><small>{ds.productType||"UI/UX Pro Max"}</small><small>{ds.style?.["Style Category"]||""}</small><small>{ds.landing?.["Pattern Name"]||""}</small></aside></div></div>}