// ─────────────────────────────────────────────────────────────
// 60 templates assemblés (n° 90 → 149) à partir des pièces combinables
// (components/landpro/pieces). Chaque template = un header + un hero + un
// footer + 3 versions de sections, sur un thème et un produit propres.
// Règles (vérifiées par tests/combos.test.ts) : aucun trio header/hero/footer
// répété, deux templates voisins ne partagent ni header, ni hero, ni footer.
// Fichier généré puis relu : modifier directement les lignes ci-dessous.
// ─────────────────────────────────────────────────────────────
import type { TemplateDef } from "./types";
import { darkTheme as D, lightTheme as L } from "./theme";

export const COMBO_DEFS: Omit<TemplateDef, "description">[] = [
  {
    number: 90,
    id: "combo-montre-orbite-360",
    name: "Montre Orbite 360",
    category: "Premium",
    demoProduct: "watch",
    lang: "fr",
    theme: D({
      primary: "#d4a24c",
      accent: "#f0c674",
      bg: "#0c0a08",
      surface: "#16130e",
      surface2: "#211c14",
      border: "#3a3020",
      heroBg: "radial-gradient(circle at 70% 30%,#2a2114,#0c0a08 70%)",
      font: "sans",
      heading: "serif",
      radius: 6,
      headingWeight: 500,
    }),
    hero: {
      variant: "split",
      eyebrow: "Édition limitée",
      title: "Elle brille sous tous les angles",
      highlight: "sous tous les angles",
    },
    sections: ["story", "showcase", "specs", "reviews", "guarantee", "order"],
    pieces: {
      header: "h11-prix",
      hero: "hero-3vues",
      footer: "f10-faq",
      sections: { reviews: "reviews-note-barres", guarantee: "guarantee-sceau", showcase: "showcase-defilante" },
    },
  },
  {
    number: 91,
    id: "combo-ecouteurs-eclates",
    name: "Écouteurs Éclatés",
    category: "Tech",
    demoProduct: "earbuds",
    lang: "fr",
    theme: D({
      primary: "#b8f028",
      accent: "#d9ff6b",
      bg: "#0a0a0a",
      surface: "#141414",
      surface2: "#1e1e1e",
      border: "#2a2a2a",
      font: "grotesk",
      heading: "tech",
      radius: 10,
      primaryText: "#0a0a0a",
    }),
    hero: {
      variant: "split",
      eyebrow: "Sous le capot",
      title: "Ce qu'il y a dans vos oreilles",
      highlight: "dans vos oreilles",
    },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h20-selecteur",
      hero: "hero-eclate",
      footer: "f12-rappel-prix",
      sections: { showcase: "showcase-zoom", specs: "specs-accordeon", offers: "offers-tableau" },
    },
  },
  {
    number: 92,
    id: "combo-hoodie-double-vue",
    name: "Hoodie Double Vue",
    category: "Mode",
    demoProduct: "hoodie",
    lang: "fr",
    theme: D({
      primary: "#ffffff",
      accent: "#ffffff",
      bg: "#000000",
      surface: "#0d0d0d",
      surface2: "#181818",
      border: "#2b2b2b",
      font: "grotesk",
      heading: "condensed",
      radius: 0,
      primaryText: "#000000",
      uppercaseHeadings: true,
    }),
    hero: { variant: "split", eyebrow: "Drop 02", title: "Porté. Détaillé.", highlight: "Détaillé." },
    sections: ["showcase", "variants", "benefits", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h14-onglets",
      hero: "hero-deux-photos",
      footer: "f14-defilant",
      sections: { faq: "faq-chat", offers: "offers-progressive", benefits: "benefits-numerote" },
    },
  },
  {
    number: 93,
    id: "combo-sneaker-pop",
    name: "Sneaker Pop",
    category: "Sport",
    demoProduct: "sneaker",
    lang: "fr",
    theme: L({
      primary: "#111111",
      accent: "#facc15",
      bg: "#facc15",
      surface: "#fde047",
      surface2: "#fef08a",
      text: "#111111",
      border: "#e5b800",
      font: "grotesk",
      heading: "condensed",
      radius: 0,
      primaryText: "#facc15",
      muted: "#3b3300",
      uppercaseHeadings: true,
    }),
    hero: {
      variant: "split",
      eyebrow: "Colorway exclusif",
      title: "Couleurs fortes, pas lourdes",
      highlight: "pas lourdes",
    },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h15-logo-geant",
      hero: "hero-multicolore",
      footer: "f16-ticket",
      sections: { order: "order-etapes", faq: "faq-cartes", benefits: "benefits-numerote" },
    },
  },
  {
    number: 94,
    id: "combo-plante-mot-doux",
    name: "Plante Mot Doux",
    category: "Maison",
    demoProduct: "plant",
    lang: "fr",
    theme: L({
      primary: "#4d7c0f",
      accent: "#65a30d",
      bg: "#fbfaf3",
      surface: "#f2f0e1",
      surface2: "#e7e4cd",
      text: "#232a14",
      border: "#e2dec4",
      font: "sans",
      heading: "elegant",
      radius: 16,
    }),
    hero: {
      variant: "split",
      eyebrow: "Livrée en pot",
      title: "Un peu de vert pour chaque matin",
      highlight: "chaque matin",
    },
    sections: ["problem", "features", "how", "stats", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h17-app",
      hero: "hero-manuscrit",
      footer: "f18-degrade",
      sections: { order: "order-plein-ecran", guarantee: "guarantee-carte", how: "how-schema" },
    },
  },
  {
    number: 95,
    id: "combo-gourde-manifeste",
    name: "Gourde Manifeste",
    category: "Maison",
    demoProduct: "bottle",
    lang: "fr",
    theme: D({
      primary: "#22c55e",
      accent: "#4ade80",
      bg: "#07120b",
      surface: "#0e1d13",
      surface2: "#15291b",
      border: "#1f3a27",
      font: "grotesk",
      heading: "condensed",
      radius: 6,
      primaryText: "#04110a",
      uppercaseHeadings: true,
    }),
    hero: {
      variant: "split",
      eyebrow: "Notre engagement",
      title: "Zéro plastique. Zéro excuse.",
      highlight: "Zéro excuse.",
    },
    sections: ["problem", "features", "how", "stats", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h18-asymetrique",
      hero: "hero-manifeste",
      footer: "f20-carte",
      sections: { reviews: "reviews-note-barres", guarantee: "guarantee-sceau", order: "order-etapes" },
    },
  },
  {
    number: 96,
    id: "combo-support-flash-stock",
    name: "Support Flash Stock",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: L({
      primary: "#16a34a",
      accent: "#16a34a",
      bg: "#ffffff",
      surface: "#f0fdf4",
      surface2: "#dcfce7",
      heroBg: "linear-gradient(180deg,#f0fdf4,#fff)",
      font: "display",
      heading: "display",
      radius: 14,
    }),
    hero: { variant: "split", eyebrow: "Vente flash", title: "Prix cassé, stock limité", highlight: "stock limité" },
    sections: [
      "announcement",
      "trust",
      "benefits",
      "showcase",
      "how",
      "reviews",
      "offers",
      "order",
      "guarantee",
      "faq",
    ],
    pieces: {
      header: "h19-whatsapp",
      hero: "hero-prix-stock",
      footer: "f11-whatsapp",
      sections: { showcase: "showcase-zoom", how: "how-schema", offers: "offers-tableau" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 97,
    id: "combo-spray-pack-maison",
    name: "Spray Pack Maison",
    category: "Maison",
    demoProduct: "spray",
    lang: "fr",
    theme: L({
      primary: "#0284c7",
      accent: "#0ea5e9",
      bg: "#f7fbff",
      surface: "#eaf5fd",
      surface2: "#d6ecfa",
      border: "#d0e6f5",
      font: "display",
      heading: "display",
      radius: 16,
    }),
    hero: {
      variant: "split",
      eyebrow: "Offre famille",
      title: "Plus vous prenez, moins vous payez",
      highlight: "moins vous payez",
    },
    sections: ["announcement", "trust", "benefits", "showcase", "how", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h13-rebours",
      hero: "hero-packs",
      footer: "f13-vague",
      sections: { guarantee: "guarantee-carte", faq: "faq-chat", showcase: "showcase-defilante" },
    },
    options: { countdownMinutes: 120 },
  },
  {
    number: 98,
    id: "combo-enceinte-bandes-son",
    name: "Enceinte Bandes Son",
    category: "Tech",
    demoProduct: "speaker",
    lang: "fr",
    theme: D({
      primary: "#facc15",
      accent: "#fde047",
      bg: "#0a0a0a",
      surface: "#141414",
      surface2: "#1f1f1f",
      border: "#2c2c2c",
      font: "grotesk",
      heading: "condensed",
      radius: 0,
      primaryText: "#0a0a0a",
      uppercaseHeadings: true,
    }),
    hero: { variant: "split", eyebrow: "Party mode", title: "Basses. Volume. Autonomie.", highlight: "Autonomie." },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h11-prix",
      hero: "hero-bandes",
      footer: "f15-avis",
      sections: { order: "order-plein-ecran", offers: "offers-progressive", faq: "faq-cartes" },
    },
  },
  {
    number: 99,
    id: "combo-serum-avant-apres",
    name: "Sérum Avant/Après",
    category: "Beauté",
    demoProduct: "serum",
    lang: "fr",
    theme: L({
      primary: "#e11d74",
      accent: "#f472b6",
      bg: "#ffffff",
      surface: "#fff4f8",
      surface2: "#ffe4ef",
      font: "sans",
      heading: "display",
      radius: 18,
    }),
    hero: {
      variant: "split",
      eyebrow: "Résultat visible",
      title: "La différence se voit en 14 jours",
      highlight: "en 14 jours",
    },
    sections: ["problem", "benefits", "how", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h19-whatsapp",
      hero: "hero-avant-apres",
      footer: "f17-etapes",
      sections: { benefits: "benefits-numerote", order: "order-etapes", guarantee: "guarantee-carte" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 100,
    id: "combo-ecouteurs-aurora",
    name: "Écouteurs Aurora",
    category: "Tech",
    demoProduct: "earbuds",
    lang: "fr",
    theme: D({
      primary: "#f472b6",
      accent: "#a78bfa",
      bg: "#0e0718",
      surface: "#170d26",
      surface2: "#211334",
      border: "#311c4a",
      heroBg: "linear-gradient(135deg,#3b0764,#831843)",
      font: "sans",
      heading: "display",
      radius: 22,
      glow: true,
    }),
    hero: {
      variant: "split",
      eyebrow: "Édition couleur",
      title: "Le son prend des couleurs",
      highlight: "des couleurs",
    },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h14-onglets",
      hero: "hero-degrade",
      footer: "f19-collant",
      sections: { reviews: "reviews-note-barres", showcase: "showcase-defilante", order: "order-plein-ecran" },
    },
  },
  {
    number: 101,
    id: "combo-plante-kraft",
    name: "Plante Kraft",
    category: "Maison",
    demoProduct: "plant",
    lang: "fr",
    theme: L({
      primary: "#5c4326",
      accent: "#8a6a3f",
      bg: "#efe3cc",
      surface: "#e6d6b7",
      surface2: "#dac7a2",
      text: "#2a1f12",
      border: "#d4c09b",
      font: "sans",
      heading: "serif",
      radius: 6,
    }),
    hero: {
      variant: "split",
      eyebrow: "Emballage recyclé",
      title: "Livrée dans du papier, pas du plastique",
      highlight: "pas du plastique",
    },
    sections: ["story", "benefits", "how", "reviews", "guarantee", "order"],
    pieces: {
      header: "h15-logo-geant",
      hero: "hero-papier",
      footer: "f10-faq",
      sections: { how: "how-schema", guarantee: "guarantee-sceau", reviews: "reviews-note-barres" },
    },
  },
  {
    number: 102,
    id: "combo-fauteuil-fiche-technique",
    name: "Fauteuil Fiche Technique",
    category: "Maison",
    demoProduct: "chair",
    lang: "fr",
    theme: L({
      primary: "#1e3a5f",
      accent: "#3b82f6",
      bg: "#f4f6f9",
      surface: "#e9edf3",
      surface2: "#dde3ec",
      text: "#0f1b2d",
      border: "#d6dde8",
      font: "sans",
      heading: "grotesk",
      radius: 8,
    }),
    hero: {
      variant: "split",
      eyebrow: "Ergonomie",
      title: "Ergonomie, mesurée point par point",
      highlight: "point par point",
    },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h17-app",
      hero: "hero-catalogue",
      footer: "f12-rappel-prix",
      sections: { specs: "specs-accordeon", faq: "faq-chat", showcase: "showcase-zoom" },
    },
  },
  {
    number: 103,
    id: "combo-bague-story",
    name: "Bague Story",
    category: "Premium",
    demoProduct: "ring",
    lang: "fr",
    theme: L({
      primary: "#b76e79",
      accent: "#d8a1a8",
      bg: "#fff9f8",
      surface: "#fbecea",
      surface2: "#f5dcd9",
      text: "#3a2326",
      border: "#f0d7d4",
      font: "sans",
      heading: "elegant",
      radius: 30,
      headingWeight: 600,
    }),
    hero: { variant: "split", eyebrow: "Vu sur Insta", title: "Faites défiler, elle brille", highlight: "elle brille" },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h18-asymetrique",
      hero: "hero-story",
      footer: "f14-defilant",
      sections: { offers: "offers-tableau", faq: "faq-cartes", benefits: "benefits-numerote" },
    },
  },
  {
    number: 104,
    id: "combo-sneaker-tour-complet",
    name: "Sneaker Tour Complet",
    category: "Sport",
    demoProduct: "sneaker",
    lang: "fr",
    theme: L({
      primary: "#e11d2e",
      accent: "#e11d2e",
      bg: "#ffffff",
      surface: "#f6f6f6",
      surface2: "#ececec",
      heroBg: "linear-gradient(180deg,#fff,#f4f4f4)",
      font: "grotesk",
      heading: "condensed",
      radius: 4,
      uppercaseHeadings: true,
    }),
    hero: {
      variant: "split",
      eyebrow: "Nouvelle saison",
      title: "Chaque angle pensé pour la route",
      highlight: "pour la route",
    },
    sections: ["stats", "features", "showcase", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h20-selecteur",
      hero: "hero-3vues",
      footer: "f16-ticket",
      sections: { offers: "offers-progressive", showcase: "showcase-defilante", order: "order-etapes" },
    },
  },
  {
    number: 105,
    id: "combo-manette-anatomie",
    name: "Manette Anatomie",
    category: "Tech",
    demoProduct: "gamepad",
    lang: "fr",
    theme: D({
      primary: "#8b5cf6",
      accent: "#c084fc",
      bg: "#0f0a1f",
      surface: "#171030",
      surface2: "#21173f",
      border: "#2e2252",
      heroBg: "radial-gradient(circle at 30% 20%,#2a1a55,#0f0a1f 65%)",
      font: "grotesk",
      heading: "tech",
      radius: 12,
      glow: true,
    }),
    hero: { variant: "split", eyebrow: "Pour les joueurs", title: "Chaque bouton, expliqué", highlight: "expliqué" },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h13-rebours",
      hero: "hero-eclate",
      footer: "f18-degrade",
      sections: { order: "order-plein-ecran", faq: "faq-chat", showcase: "showcase-zoom" },
    },
    options: { countdownMinutes: 120 },
  },
  {
    number: 106,
    id: "combo-abaya-deux-photos-ar",
    name: "عباية بصورتين",
    category: "Arabe",
    demoProduct: "abaya",
    lang: "ar",
    theme: L({
      primary: "#a87b3d",
      accent: "#c9a45a",
      bg: "#f7f1e6",
      surface: "#efe5d3",
      surface2: "#e5d7bd",
      text: "#2d2416",
      border: "#e0d1b6",
      font: "arabic",
      heading: "arabic",
      radius: 14,
    }),
    hero: { variant: "split", eyebrow: "تشكيلة جديدة", title: "أناقة تُرى من قريب ومن بعيد", highlight: "من قريب" },
    sections: ["showcase", "variants", "benefits", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h11-prix",
      hero: "hero-deux-photos",
      footer: "f20-carte",
      sections: { offers: "offers-tableau", faq: "faq-cartes", showcase: "showcase-zoom" },
    },
  },
  {
    number: 107,
    id: "combo-gourde-arc-en-ciel",
    name: "Gourde Arc-en-ciel",
    category: "Maison",
    demoProduct: "bottle",
    lang: "fr",
    theme: L({
      primary: "#0d9488",
      accent: "#14b8a6",
      bg: "#f0fdfa",
      surface: "#ccfbf1",
      surface2: "#99f6e4",
      border: "#bdf0e6",
      font: "display",
      heading: "display",
      radius: 24,
    }),
    hero: { variant: "split", eyebrow: "Sans BPA", title: "Hydratez-vous en couleur", highlight: "en couleur" },
    sections: [
      "announcement",
      "trust",
      "benefits",
      "showcase",
      "how",
      "reviews",
      "offers",
      "order",
      "guarantee",
      "faq",
    ],
    pieces: {
      header: "h13-rebours",
      hero: "hero-multicolore",
      footer: "f11-whatsapp",
      sections: { guarantee: "guarantee-carte", how: "how-schema", offers: "offers-progressive" },
    },
    options: { countdownMinutes: 60, orderMode: "both" },
  },
  {
    number: 108,
    id: "combo-perfume-manuscrit-ar",
    name: "عطر بخط اليد",
    category: "Arabe",
    demoProduct: "perfume",
    lang: "ar",
    theme: L({
      primary: "#7f1d36",
      accent: "#a8324f",
      bg: "#fbf7f0",
      surface: "#f3ece0",
      surface2: "#e9dfcd",
      text: "#2a1418",
      border: "#e6dccb",
      font: "arabic",
      heading: "arabic",
      radius: 12,
    }),
    hero: { variant: "split", eyebrow: "عطر شرقي", title: "عطر يُكتب على البشرة", highlight: "على البشرة" },
    sections: ["story", "showcase", "specs", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h14-onglets",
      hero: "hero-manuscrit",
      footer: "f13-vague",
      sections: { specs: "specs-accordeon", guarantee: "guarantee-sceau", order: "order-etapes" },
    },
  },
  {
    number: 109,
    id: "combo-manifeste-vert",
    name: "Manifeste Vert",
    category: "Maison",
    demoProduct: "plant",
    lang: "fr",
    theme: D({
      primary: "#a3e635",
      accent: "#bef264",
      bg: "#0f1f14",
      surface: "#16291c",
      surface2: "#1d3524",
      border: "#29462f",
      font: "sans",
      heading: "serif",
      radius: 14,
      primaryText: "#0f1f14",
    }),
    hero: {
      variant: "split",
      eyebrow: "Revenir à l'essentiel",
      title: "Moins d'écrans, plus de racines",
      highlight: "plus de racines",
    },
    sections: ["story", "benefits", "how", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h15-logo-geant",
      hero: "hero-manifeste",
      footer: "f15-avis",
      sections: { benefits: "benefits-numerote", order: "order-plein-ecran", guarantee: "guarantee-carte" },
    },
  },
  {
    number: 110,
    id: "combo-friteuse-dernieres-pieces",
    name: "Friteuse Dernières Pièces",
    category: "Maison",
    demoProduct: "airfryer",
    lang: "fr",
    theme: L({
      primary: "#dc2626",
      accent: "#f97316",
      bg: "#ffffff",
      surface: "#fff5f5",
      surface2: "#ffe4e4",
      heroBg: "linear-gradient(135deg,#fff1f1,#fff7ed)",
      font: "display",
      heading: "display",
      radius: 12,
    }),
    hero: {
      variant: "split",
      eyebrow: "Dernières pièces",
      title: "La cuisine sans huile à prix barré",
      highlight: "à prix barré",
    },
    sections: ["announcement", "countdown", "benefits", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h17-app",
      hero: "hero-prix-stock",
      footer: "f17-etapes",
      sections: { reviews: "reviews-note-barres", guarantee: "guarantee-sceau", faq: "faq-chat" },
    },
    options: { countdownMinutes: 45 },
  },
  {
    number: 111,
    id: "combo-shampoing-cure-3-mois",
    name: "Shampoing Cure 3 Mois",
    category: "Beauté",
    demoProduct: "shampoo",
    lang: "fr",
    theme: L({
      primary: "#0891b2",
      accent: "#06b6d4",
      bg: "#f3fbfd",
      surface: "#e0f5fa",
      surface2: "#c9eef6",
      border: "#c4e8f0",
      font: "sans",
      heading: "display",
      radius: 22,
    }),
    hero: {
      variant: "split",
      eyebrow: "Cure complète",
      title: "La cure complète en un seul colis",
      highlight: "un seul colis",
    },
    sections: ["problem", "benefits", "before_after", "how", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h18-asymetrique",
      hero: "hero-packs",
      footer: "f19-collant",
      sections: { how: "how-schema", faq: "faq-cartes", reviews: "reviews-note-barres" },
    },
  },
  {
    number: 112,
    id: "combo-smartphone-rayures",
    name: "Smartphone Rayures",
    category: "Tech",
    demoProduct: "smartphone",
    lang: "fr",
    theme: L({
      primary: "#111111",
      accent: "#111111",
      bg: "#ffffff",
      surface: "#f5f5f5",
      surface2: "#ebebeb",
      font: "grotesk",
      heading: "grotesk",
      radius: 0,
    }),
    hero: { variant: "split", eyebrow: "Fiche express", title: "Fin. Rapide. Endurant.", highlight: "Endurant." },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "offers", "order"],
    pieces: {
      header: "h19-whatsapp",
      hero: "hero-bandes",
      footer: "f10-faq",
      sections: { specs: "specs-accordeon", offers: "offers-tableau", showcase: "showcase-defilante" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 113,
    id: "combo-shampoing-resultat",
    name: "Shampoing Résultat",
    category: "Beauté",
    demoProduct: "shampoo",
    lang: "fr",
    theme: L({
      primary: "#059669",
      accent: "#10b981",
      bg: "#ffffff",
      surface: "#ecfdf5",
      surface2: "#d1fae5",
      font: "sans",
      heading: "display",
      radius: 16,
    }),
    hero: {
      variant: "split",
      eyebrow: "Soin réparateur",
      title: "Des cheveux qui revivent",
      highlight: "qui revivent",
    },
    sections: ["problem", "benefits", "how", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h18-asymetrique",
      hero: "hero-avant-apres",
      footer: "f12-rappel-prix",
      sections: { offers: "offers-progressive", benefits: "benefits-numerote", order: "order-etapes" },
    },
  },
  {
    number: 114,
    id: "combo-smartphone-nebuleuse",
    name: "Smartphone Nébuleuse",
    category: "Tech",
    demoProduct: "smartphone",
    lang: "fr",
    theme: D({
      primary: "#818cf8",
      accent: "#38bdf8",
      bg: "#060918",
      surface: "#0d1230",
      surface2: "#141a42",
      border: "#202a5c",
      heroBg: "linear-gradient(135deg,#1e1b4b,#0c4a6e)",
      font: "sans",
      heading: "grotesk",
      radius: 20,
    }),
    hero: { variant: "split", eyebrow: "Écran AMOLED", title: "Un écran qui fait rêver", highlight: "qui fait rêver" },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h20-selecteur",
      hero: "hero-degrade",
      footer: "f14-defilant",
      sections: { specs: "specs-accordeon", showcase: "showcase-defilante", order: "order-plein-ecran" },
    },
  },
  {
    number: 115,
    id: "combo-bague-atelier",
    name: "Bague Atelier",
    category: "Premium",
    demoProduct: "ring",
    lang: "fr",
    theme: L({
      primary: "#1a1a1a",
      accent: "#7a5c2e",
      bg: "#f6f1e7",
      surface: "#ede5d6",
      surface2: "#e1d6c2",
      text: "#1a1a1a",
      border: "#ddd2bd",
      font: "sans",
      heading: "elegant",
      radius: 0,
      headingWeight: 500,
    }),
    hero: {
      variant: "split",
      eyebrow: "Fait main",
      title: "Façonnée à la main, emballée avec soin",
      highlight: "avec soin",
    },
    sections: ["story", "showcase", "specs", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h11-prix",
      hero: "hero-papier",
      footer: "f16-ticket",
      sections: { guarantee: "guarantee-sceau", faq: "faq-chat", showcase: "showcase-zoom" },
    },
  },
  {
    number: 116,
    id: "combo-friteuse-annotee",
    name: "Friteuse Annotée",
    category: "Maison",
    demoProduct: "airfryer",
    lang: "fr",
    theme: L({
      primary: "#f97316",
      accent: "#fb923c",
      bg: "#ffffff",
      surface: "#fff7ef",
      surface2: "#ffedd9",
      font: "display",
      heading: "display",
      radius: 20,
    }),
    hero: { variant: "split", eyebrow: "Mode d'emploi", title: "Chaque fonction a sa raison", highlight: "sa raison" },
    sections: ["problem", "features", "how", "stats", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h14-onglets",
      hero: "hero-catalogue",
      footer: "f18-degrade",
      sections: { how: "how-schema", faq: "faq-cartes", guarantee: "guarantee-carte" },
    },
  },
  {
    number: 117,
    id: "combo-abaya-story-ar",
    name: "عباية ستوري",
    category: "Arabe",
    demoProduct: "abaya",
    lang: "ar",
    theme: D({
      primary: "#d4a24c",
      accent: "#f0c674",
      bg: "#0b0a08",
      surface: "#15130f",
      surface2: "#201c15",
      border: "#3a3122",
      font: "arabic",
      heading: "arabic",
      radius: 12,
      primaryText: "#0b0a08",
    }),
    hero: { variant: "split", eyebrow: "شوفي الستوري", title: "شوفيها كيف كتلبس", highlight: "كيف كتلبس" },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h15-logo-geant",
      hero: "hero-story",
      footer: "f20-carte",
      sections: { offers: "offers-tableau", faq: "faq-chat", showcase: "showcase-zoom" },
    },
  },
  {
    number: 118,
    id: "combo-casque-studio-rotatif",
    name: "Casque Studio Rotatif",
    category: "Tech",
    demoProduct: "headphones",
    lang: "fr",
    theme: D({
      primary: "#22d3ee",
      accent: "#67e8f9",
      bg: "#0d1117",
      surface: "#151b23",
      surface2: "#1d2530",
      border: "#263040",
      font: "grotesk",
      heading: "grotesk",
      radius: 14,
      glow: true,
    }),
    hero: { variant: "split", eyebrow: "Son studio", title: "Le son, vu sous trois angles", highlight: "trois angles" },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h17-app",
      hero: "hero-3vues",
      footer: "f11-whatsapp",
      sections: { specs: "specs-accordeon", offers: "offers-progressive", order: "order-etapes" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 119,
    id: "combo-enceinte-devoilee",
    name: "Enceinte Dévoilée",
    category: "Maison",
    demoProduct: "speaker",
    lang: "fr",
    theme: L({
      primary: "#ea580c",
      accent: "#f97316",
      bg: "#fbf6ef",
      surface: "#f4ece0",
      surface2: "#ebdfcd",
      text: "#2a2016",
      border: "#e6d8c3",
      font: "sans",
      heading: "display",
      radius: 18,
    }),
    hero: { variant: "split", eyebrow: "Conçue pour durer", title: "Ouvrez-la du regard", highlight: "du regard" },
    sections: ["problem", "features", "how", "stats", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h19-whatsapp",
      hero: "hero-eclate",
      footer: "f13-vague",
      sections: { order: "order-plein-ecran", guarantee: "guarantee-carte", how: "how-schema" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 120,
    id: "combo-parfum-duo",
    name: "Parfum Duo",
    category: "Premium",
    demoProduct: "perfume",
    lang: "fr",
    theme: D({
      primary: "#c6485f",
      accent: "#e8a0ae",
      bg: "#1a0a0e",
      surface: "#251015",
      surface2: "#31161d",
      border: "#47202a",
      heroBg: "linear-gradient(160deg,#3a1019,#1a0a0e)",
      font: "sans",
      heading: "elegant",
      radius: 4,
      headingWeight: 500,
    }),
    hero: { variant: "split", eyebrow: "Eau de parfum", title: "Le flacon, puis le sillage", highlight: "le sillage" },
    sections: ["story", "showcase", "specs", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h18-asymetrique",
      hero: "hero-deux-photos",
      footer: "f15-avis",
      sections: { reviews: "reviews-note-barres", guarantee: "guarantee-sceau", showcase: "showcase-defilante" },
    },
  },
  {
    number: 121,
    id: "combo-manette-arcade",
    name: "Manette Arcade",
    category: "Tech",
    demoProduct: "gamepad",
    lang: "fr",
    theme: D({
      primary: "#ff2bd6",
      accent: "#ff7ae8",
      bg: "#0b0612",
      surface: "#150c20",
      surface2: "#1f122e",
      border: "#2f1d44",
      font: "grotesk",
      heading: "tech",
      radius: 8,
      glow: true,
    }),
    hero: { variant: "split", eyebrow: "Mode turbo", title: "Jouez plus fort", highlight: "plus fort" },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h13-rebours",
      hero: "hero-multicolore",
      footer: "f17-etapes",
      sections: { offers: "offers-tableau", faq: "faq-cartes", benefits: "benefits-numerote" },
    },
    options: { countdownMinutes: 120 },
  },
  {
    number: 122,
    id: "combo-serum-carnet",
    name: "Sérum Carnet",
    category: "Beauté",
    demoProduct: "serum",
    lang: "fr",
    theme: L({
      primary: "#f97361",
      accent: "#fb923c",
      bg: "#fff6f1",
      surface: "#ffe9df",
      surface2: "#ffdccd",
      text: "#3b211a",
      border: "#f8d9cb",
      font: "sans",
      heading: "serif",
      radius: 20,
    }),
    hero: {
      variant: "split",
      eyebrow: "Routine du soir",
      title: "Ma peau, notée jour après jour",
      highlight: "jour après jour",
    },
    sections: ["problem", "benefits", "before_after", "how", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h11-prix",
      hero: "hero-manuscrit",
      footer: "f19-collant",
      sections: { offers: "offers-progressive", guarantee: "guarantee-carte", faq: "faq-chat" },
    },
  },
  {
    number: 123,
    id: "combo-manifeste-running",
    name: "Manifeste Running",
    category: "Sport",
    demoProduct: "sneaker",
    lang: "fr",
    theme: L({
      primary: "#dc2626",
      accent: "#dc2626",
      bg: "#ffffff",
      surface: "#fafafa",
      surface2: "#f1f1f1",
      font: "grotesk",
      heading: "condensed",
      radius: 0,
      uppercaseHeadings: true,
    }),
    hero: {
      variant: "split",
      eyebrow: "Run club",
      title: "Courir n'attend pas la motivation",
      highlight: "la motivation",
    },
    sections: ["stats", "features", "showcase", "reviews", "offers", "order", "guarantee"],
    pieces: {
      header: "h20-selecteur",
      hero: "hero-manifeste",
      footer: "f10-faq",
      sections: { order: "order-etapes", showcase: "showcase-zoom", offers: "offers-tableau" },
    },
  },
  {
    number: 124,
    id: "combo-serum-prix-stock-ar",
    name: "سيروم بسعر مكسور",
    category: "Arabe",
    demoProduct: "serum",
    lang: "ar",
    theme: L({
      primary: "#be185d",
      accent: "#ec4899",
      bg: "#fff5f9",
      surface: "#ffe8f1",
      surface2: "#ffd6e7",
      border: "#fbd0e2",
      font: "arabic",
      heading: "arabic",
      radius: 18,
    }),
    hero: { variant: "split", eyebrow: "عرض محدود", title: "سعر مكسور، كمية محدودة", highlight: "كمية محدودة" },
    sections: ["announcement", "countdown", "benefits", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h14-onglets",
      hero: "hero-prix-stock",
      footer: "f12-rappel-prix",
      sections: { benefits: "benefits-numerote", order: "order-plein-ecran", offers: "offers-progressive" },
    },
    options: { countdownMinutes: 90 },
  },
  {
    number: 125,
    id: "combo-serum-routine-x3",
    name: "Sérum Routine x3",
    category: "Beauté",
    demoProduct: "serum",
    lang: "fr",
    theme: L({
      primary: "#e0607e",
      accent: "#f0899f",
      bg: "#fffafa",
      surface: "#fff0f2",
      surface2: "#ffe2e7",
      text: "#3a1f25",
      border: "#f9dbe1",
      font: "sans",
      heading: "elegant",
      radius: 26,
      headingWeight: 600,
    }),
    hero: {
      variant: "split",
      eyebrow: "Routine éclat",
      title: "Une routine, trois flacons",
      highlight: "trois flacons",
    },
    sections: ["problem", "benefits", "before_after", "how", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h15-logo-geant",
      hero: "hero-packs",
      footer: "f14-defilant",
      sections: { reviews: "reviews-note-barres", guarantee: "guarantee-sceau", how: "how-schema" },
    },
  },
  {
    number: 126,
    id: "combo-casque-bandes",
    name: "Casque Bandes",
    category: "Tech",
    demoProduct: "headphones",
    lang: "fr",
    theme: D({
      primary: "#ef4444",
      accent: "#f87171",
      bg: "#0b0b0b",
      surface: "#151515",
      surface2: "#1f1f1f",
      border: "#2e2e2e",
      font: "grotesk",
      heading: "condensed",
      radius: 4,
      uppercaseHeadings: true,
    }),
    hero: { variant: "split", eyebrow: "Réduction de bruit", title: "Écouter, en grand", highlight: "en grand" },
    sections: ["stats", "features", "showcase", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h17-app",
      hero: "hero-bandes",
      footer: "f16-ticket",
      sections: { faq: "faq-cartes", showcase: "showcase-defilante", offers: "offers-tableau" },
    },
  },
  {
    number: 127,
    id: "combo-spray-avant-apres",
    name: "Spray Avant/Après",
    category: "Maison",
    demoProduct: "spray",
    lang: "fr",
    theme: L({
      primary: "#1d4ed8",
      accent: "#38bdf8",
      bg: "#ffffff",
      surface: "#f1f6ff",
      surface2: "#e1ecff",
      font: "display",
      heading: "display",
      radius: 12,
    }),
    hero: {
      variant: "split",
      eyebrow: "Nettoyant multi-surfaces",
      title: "Une pulvérisation, la tache disparaît",
      highlight: "la tache disparaît",
    },
    sections: [
      "announcement",
      "trust",
      "benefits",
      "showcase",
      "how",
      "reviews",
      "offers",
      "order",
      "guarantee",
      "faq",
    ],
    pieces: {
      header: "h13-rebours",
      hero: "hero-avant-apres",
      footer: "f18-degrade",
      sections: { guarantee: "guarantee-carte", faq: "faq-chat", showcase: "showcase-zoom" },
    },
    options: { countdownMinutes: 60 },
  },
  {
    number: 128,
    id: "combo-parfum-aube",
    name: "Parfum Aube",
    category: "Premium",
    demoProduct: "perfume",
    lang: "fr",
    theme: L({
      primary: "#e8590c",
      accent: "#f06595",
      bg: "#fff8f3",
      surface: "#ffeee3",
      surface2: "#ffe0cf",
      text: "#2e1a10",
      border: "#f8dccb",
      heroBg: "linear-gradient(135deg,#ffd8a8,#fcc2d7)",
      font: "sans",
      heading: "elegant",
      radius: 12,
      headingWeight: 600,
    }),
    hero: {
      variant: "split",
      eyebrow: "Notes solaires",
      title: "Une fragrance comme un lever de soleil",
      highlight: "un lever de soleil",
    },
    sections: ["story", "benefits", "how", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h19-whatsapp",
      hero: "hero-degrade",
      footer: "f20-carte",
      sections: { benefits: "benefits-numerote", order: "order-etapes", how: "how-schema" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 129,
    id: "combo-gourde-carnet-de-route",
    name: "Gourde Carnet de Route",
    category: "Maison",
    demoProduct: "bottle",
    lang: "fr",
    theme: L({
      primary: "#1e40af",
      accent: "#3b82f6",
      bg: "#efe5d2",
      surface: "#e5d8bf",
      surface2: "#d8c8a8",
      text: "#1c1a14",
      border: "#d3c3a2",
      font: "grotesk",
      heading: "serif",
      radius: 8,
    }),
    hero: { variant: "split", eyebrow: "Aventure", title: "Elle vous suit partout", highlight: "partout" },
    sections: ["problem", "features", "how", "stats", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h18-asymetrique",
      hero: "hero-papier",
      footer: "f11-whatsapp",
      sections: { order: "order-plein-ecran", faq: "faq-cartes", reviews: "reviews-note-barres" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 130,
    id: "combo-support-plan-technique",
    name: "Support Plan Technique",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: D({
      primary: "#7dd3fc",
      accent: "#bae6fd",
      bg: "#0a2342",
      surface: "#0f2d55",
      surface2: "#143868",
      text: "#e6f1ff",
      border: "#1e4878",
      font: "grotesk",
      heading: "grotesk",
      radius: 4,
      primaryText: "#0a2342",
    }),
    hero: { variant: "split", eyebrow: "Ingénierie", title: "Conçu au millimètre", highlight: "au millimètre" },
    sections: [
      "announcement",
      "trust",
      "benefits",
      "showcase",
      "how",
      "reviews",
      "offers",
      "order",
      "guarantee",
      "faq",
    ],
    pieces: {
      header: "h20-selecteur",
      hero: "hero-catalogue",
      footer: "f13-vague",
      sections: { guarantee: "guarantee-sceau", showcase: "showcase-defilante", offers: "offers-progressive" },
    },
  },
  {
    number: 131,
    id: "combo-parfum-story",
    name: "Parfum Story",
    category: "Premium",
    demoProduct: "perfume",
    lang: "fr",
    theme: L({
      primary: "#8b5e34",
      accent: "#c08552",
      bg: "#f8f2ea",
      surface: "#efe5d8",
      surface2: "#e4d5c2",
      text: "#2b1f14",
      border: "#e2d3bf",
      font: "sans",
      heading: "serif",
      radius: 20,
    }),
    hero: {
      variant: "split",
      eyebrow: "Tendance",
      title: "Le parfum dont tout le monde parle",
      highlight: "tout le monde parle",
    },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h13-rebours",
      hero: "hero-story",
      footer: "f15-avis",
      sections: { showcase: "showcase-zoom", offers: "offers-tableau", faq: "faq-cartes" },
    },
    options: { countdownMinutes: 60 },
  },
  {
    number: 132,
    id: "combo-smartphone-trois-faces",
    name: "Smartphone Trois Faces",
    category: "Tech",
    demoProduct: "smartphone",
    lang: "fr",
    theme: L({
      primary: "#2563eb",
      accent: "#3b82f6",
      bg: "#ffffff",
      surface: "#f5f8ff",
      surface2: "#e8efff",
      heroBg: "linear-gradient(180deg,#f5f8ff,#fff)",
      font: "sans",
      heading: "sans",
      radius: 20,
    }),
    hero: {
      variant: "split",
      eyebrow: "Nouveau modèle",
      title: "Recto, profil, verso : aucun défaut",
      highlight: "aucun défaut",
    },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h14-onglets",
      hero: "hero-3vues",
      footer: "f17-etapes",
      sections: { specs: "specs-accordeon", faq: "faq-chat", offers: "offers-progressive" },
    },
  },
  {
    number: 133,
    id: "combo-seche-cheveux-revele",
    name: "Sèche-cheveux Révélé",
    category: "Beauté",
    demoProduct: "dryer",
    lang: "fr",
    theme: L({
      primary: "#db2777",
      accent: "#ec4899",
      bg: "#fff7fa",
      surface: "#fdeef4",
      surface2: "#fbe1eb",
      border: "#f6d5e2",
      heroBg: "linear-gradient(160deg,#fff7fa,#fde4ee)",
      font: "sans",
      heading: "serif",
      radius: 22,
    }),
    hero: {
      variant: "split",
      eyebrow: "Technologie ionique",
      title: "La technologie derrière le brushing",
      highlight: "le brushing",
    },
    sections: ["problem", "benefits", "before_after", "how", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h15-logo-geant",
      hero: "hero-eclate",
      footer: "f19-collant",
      sections: { benefits: "benefits-numerote", order: "order-etapes", guarantee: "guarantee-carte" },
    },
  },
  {
    number: 134,
    id: "combo-fauteuil-deux-regards",
    name: "Fauteuil Deux Regards",
    category: "Maison",
    demoProduct: "chair",
    lang: "fr",
    theme: L({
      primary: "#3f6b4a",
      accent: "#5d8c68",
      bg: "#f5f2ea",
      surface: "#ece7da",
      surface2: "#e1dac7",
      text: "#1e2a21",
      border: "#ddd5c2",
      font: "sans",
      heading: "serif",
      radius: 10,
    }),
    hero: { variant: "split", eyebrow: "Salon & bureau", title: "Le confort, en situation", highlight: "en situation" },
    sections: ["problem", "features", "how", "stats", "reviews", "order", "guarantee"],
    pieces: {
      header: "h17-app",
      hero: "hero-deux-photos",
      footer: "f10-faq",
      sections: { order: "order-plein-ecran", how: "how-schema", reviews: "reviews-note-barres" },
    },
  },
  {
    number: 135,
    id: "combo-hoodie-graffiti",
    name: "Hoodie Graffiti",
    category: "Mode",
    demoProduct: "hoodie",
    lang: "fr",
    theme: L({
      primary: "#ff5a1f",
      accent: "#ff5a1f",
      bg: "#f3f0ea",
      surface: "#e9e4da",
      surface2: "#ddd6c8",
      text: "#141414",
      border: "#d8d0c0",
      font: "grotesk",
      heading: "condensed",
      radius: 2,
      uppercaseHeadings: true,
    }),
    hero: { variant: "split", eyebrow: "Streetwear", title: "Le hoodie qui parle avant vous", highlight: "avant vous" },
    sections: ["showcase", "variants", "benefits", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h11-prix",
      hero: "hero-multicolore",
      footer: "f12-rappel-prix",
      sections: { showcase: "showcase-defilante", reviews: "reviews-note-barres", benefits: "benefits-numerote" },
    },
  },
  {
    number: 136,
    id: "combo-bague-mot-ecrit",
    name: "Bague Mot Écrit",
    category: "Premium",
    demoProduct: "ring",
    lang: "fr",
    theme: L({
      primary: "#9a7432",
      accent: "#c19a4e",
      bg: "#fdfaf3",
      surface: "#f6efdf",
      surface2: "#ede2c9",
      text: "#2a2216",
      border: "#ebe0c8",
      font: "sans",
      heading: "elegant",
      radius: 2,
      headingWeight: 500,
    }),
    hero: {
      variant: "split",
      eyebrow: "Argent 925",
      title: "Pour dire ce qu'on n'écrit pas",
      highlight: "ce qu'on n'écrit pas",
    },
    sections: ["story", "showcase", "specs", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h19-whatsapp",
      hero: "hero-manuscrit",
      footer: "f14-defilant",
      sections: { specs: "specs-accordeon", guarantee: "guarantee-sceau", showcase: "showcase-zoom" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 137,
    id: "combo-manifeste-cheveux",
    name: "Manifeste Cheveux",
    category: "Beauté",
    demoProduct: "shampoo",
    lang: "fr",
    theme: L({
      primary: "#7c3aed",
      accent: "#a78bfa",
      bg: "#faf7ff",
      surface: "#f1ebff",
      surface2: "#e5dbff",
      border: "#e2d8fb",
      font: "sans",
      heading: "display",
      radius: 18,
    }),
    hero: {
      variant: "split",
      eyebrow: "Formule propre",
      title: "Vos cheveux méritent mieux que des promesses",
      highlight: "mieux",
    },
    sections: ["problem", "benefits", "before_after", "how", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h18-asymetrique",
      hero: "hero-manifeste",
      footer: "f16-ticket",
      sections: { guarantee: "guarantee-carte", faq: "faq-chat", how: "how-schema" },
    },
  },
  {
    number: 138,
    id: "combo-montre-stock-final",
    name: "Montre Stock Final",
    category: "Premium",
    demoProduct: "watch",
    lang: "fr",
    theme: D({
      primary: "#e2b659",
      accent: "#f5d58c",
      bg: "#080808",
      surface: "#121212",
      surface2: "#1b1b1b",
      border: "#2d2a22",
      font: "sans",
      heading: "serif",
      radius: 2,
      primaryText: "#0a0a0a",
    }),
    hero: { variant: "split", eyebrow: "Fin de série", title: "Dernières montres à ce prix", highlight: "à ce prix" },
    sections: ["story", "showcase", "specs", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h20-selecteur",
      hero: "hero-prix-stock",
      footer: "f18-degrade",
      sections: { specs: "specs-accordeon", order: "order-etapes", faq: "faq-cartes" },
    },
  },
  {
    number: 139,
    id: "combo-holder-packs-ar",
    name: "حامل الهاتف باك العائلة",
    category: "Arabe",
    demoProduct: "holder",
    lang: "ar",
    theme: L({
      primary: "#15803d",
      accent: "#22c55e",
      bg: "#ffffff",
      surface: "#f0fdf4",
      surface2: "#dcfce7",
      font: "arabic",
      heading: "arabic",
      radius: 14,
    }),
    hero: { variant: "split", eyebrow: "باك العائلة", title: "باك لكل سيارة في العائلة", highlight: "في العائلة" },
    sections: ["announcement", "trust", "benefits", "showcase", "how", "reviews", "order", "guarantee", "faq"],
    pieces: {
      header: "h13-rebours",
      hero: "hero-packs",
      footer: "f20-carte",
      sections: { showcase: "showcase-defilante", order: "order-plein-ecran", guarantee: "guarantee-sceau" },
    },
    options: { countdownMinutes: 60 },
  },
  {
    number: 140,
    id: "combo-hoodie-lignes",
    name: "Hoodie Lignes",
    category: "Mode",
    demoProduct: "hoodie",
    lang: "fr",
    theme: L({
      primary: "#4b5320",
      accent: "#6b7a2a",
      bg: "#f1efe6",
      surface: "#e6e3d4",
      surface2: "#d9d5bf",
      text: "#1d1f12",
      border: "#d6d1bb",
      font: "grotesk",
      heading: "condensed",
      radius: 4,
      uppercaseHeadings: true,
    }),
    hero: { variant: "split", eyebrow: "Coton épais", title: "Épais. Doux. Durable.", highlight: "Durable." },
    sections: ["showcase", "variants", "benefits", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h14-onglets",
      hero: "hero-bandes",
      footer: "f11-whatsapp",
      sections: { offers: "offers-tableau", reviews: "reviews-note-barres", showcase: "showcase-defilante" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 141,
    id: "combo-brushing-avant-apres",
    name: "Brushing Avant/Après",
    category: "Beauté",
    demoProduct: "dryer",
    lang: "fr",
    theme: D({
      primary: "#e879f9",
      accent: "#f0abfc",
      bg: "#160a1a",
      surface: "#211026",
      surface2: "#2d1634",
      border: "#3d1f47",
      font: "sans",
      heading: "serif",
      radius: 18,
      primaryText: "#160a1a",
    }),
    hero: {
      variant: "split",
      eyebrow: "Lissage rapide",
      title: "Du frisottis au lisse en 10 minutes",
      highlight: "en 10 minutes",
    },
    sections: ["problem", "benefits", "how", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h15-logo-geant",
      hero: "hero-avant-apres",
      footer: "f13-vague",
      sections: { offers: "offers-progressive", how: "how-schema", faq: "faq-cartes" },
    },
  },
  {
    number: 142,
    id: "combo-manette-neon",
    name: "Manette Néon",
    category: "Tech",
    demoProduct: "gamepad",
    lang: "fr",
    theme: D({
      primary: "#22d3ee",
      accent: "#e879f9",
      bg: "#05060f",
      surface: "#0c0f20",
      surface2: "#141832",
      border: "#1f2548",
      heroBg: "linear-gradient(135deg,#0e7490,#86198f)",
      font: "grotesk",
      heading: "tech",
      radius: 10,
      glow: true,
    }),
    hero: { variant: "split", eyebrow: "RGB intégré", title: "Lumière, réflexes, victoire", highlight: "victoire" },
    sections: ["announcement", "countdown", "benefits", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h17-app",
      hero: "hero-degrade",
      footer: "f15-avis",
      sections: { guarantee: "guarantee-carte", faq: "faq-chat", offers: "offers-tableau" },
    },
    options: { countdownMinutes: 45 },
  },
  {
    number: 143,
    id: "combo-abaya-papier-ar",
    name: "عباية ورق كرافت",
    category: "Arabe",
    demoProduct: "abaya",
    lang: "ar",
    theme: L({
      primary: "#7c4a1e",
      accent: "#a16207",
      bg: "#f1e6d0",
      surface: "#e7d8ba",
      surface2: "#dbc8a3",
      text: "#2a1d10",
      border: "#d6c3a0",
      font: "arabic",
      heading: "arabic",
      radius: 8,
    }),
    hero: { variant: "split", eyebrow: "خياطة يدوية", title: "خياطة يدوية، تغليف بعناية", highlight: "بعناية" },
    sections: ["story", "benefits", "how", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h11-prix",
      hero: "hero-papier",
      footer: "f17-etapes",
      sections: { benefits: "benefits-numerote", order: "order-etapes", guarantee: "guarantee-sceau" },
    },
  },
  {
    number: 144,
    id: "combo-enceinte-catalogue",
    name: "Enceinte Catalogue",
    category: "Tech",
    demoProduct: "speaker",
    lang: "fr",
    theme: D({
      primary: "#fb923c",
      accent: "#fdba74",
      bg: "#0c0a09",
      surface: "#171412",
      surface2: "#211c19",
      border: "#302824",
      font: "grotesk",
      heading: "grotesk",
      radius: 6,
      primaryText: "#0c0a09",
    }),
    hero: {
      variant: "split",
      eyebrow: "Fiche complète",
      title: "La fiche complète, sans jargon",
      highlight: "sans jargon",
    },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "offers", "order", "faq"],
    pieces: {
      header: "h19-whatsapp",
      hero: "hero-catalogue",
      footer: "f19-collant",
      sections: { specs: "specs-accordeon", order: "order-plein-ecran", showcase: "showcase-zoom" },
    },
    options: { orderMode: "both" },
  },
  {
    number: 145,
    id: "combo-casque-story",
    name: "Casque Story",
    category: "Tech",
    demoProduct: "headphones",
    lang: "fr",
    theme: L({
      primary: "#6d28d9",
      accent: "#facc15",
      bg: "#fffbea",
      surface: "#fff3c4",
      surface2: "#ffe98a",
      text: "#1e1036",
      border: "#f5e199",
      font: "grotesk",
      heading: "display",
      radius: 24,
    }),
    hero: {
      variant: "split",
      eyebrow: "Format vertical",
      title: "Format vertical, son immersif",
      highlight: "son immersif",
    },
    sections: ["ugc", "benefits", "showcase", "reviews", "offers", "order"],
    pieces: {
      header: "h18-asymetrique",
      hero: "hero-story",
      footer: "f10-faq",
      sections: { offers: "offers-progressive", reviews: "reviews-note-barres", showcase: "showcase-defilante" },
    },
  },
  {
    number: 146,
    id: "combo-ecouteurs-fin-de-serie",
    name: "Écouteurs Fin de Série",
    category: "Tech",
    demoProduct: "earbuds",
    lang: "fr",
    theme: D({
      primary: "#3b82f6",
      accent: "#60a5fa",
      bg: "#050b1a",
      surface: "#0b1630",
      surface2: "#112045",
      border: "#1b2d5a",
      heroBg: "radial-gradient(circle at 70% 20%,#123070,#050b1a 65%)",
      font: "grotesk",
      heading: "grotesk",
      radius: 16,
      glow: true,
    }),
    hero: {
      variant: "split",
      eyebrow: "Destockage",
      title: "Le son premium, le prix en moins",
      highlight: "le prix en moins",
    },
    sections: ["announcement", "countdown", "benefits", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h20-selecteur",
      hero: "hero-prix-stock",
      footer: "f12-rappel-prix",
      sections: { offers: "offers-tableau", faq: "faq-cartes", guarantee: "guarantee-sceau" },
    },
    options: { countdownMinutes: 45 },
  },
  {
    number: 147,
    id: "combo-smartphone-packs",
    name: "Smartphone Packs",
    category: "Tech",
    demoProduct: "smartphone",
    lang: "fr",
    theme: D({
      primary: "#a78bfa",
      accent: "#c4b5fd",
      bg: "#0c0a1a",
      surface: "#141128",
      surface2: "#1c1836",
      border: "#2a2450",
      font: "sans",
      heading: "grotesk",
      radius: 18,
      primaryText: "#0c0a1a",
    }),
    hero: {
      variant: "split",
      eyebrow: "Livré demain",
      title: "Choisissez votre pack, on livre demain",
      highlight: "on livre demain",
    },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "order", "faq"],
    pieces: {
      header: "h11-prix",
      hero: "hero-packs",
      footer: "f14-defilant",
      sections: { specs: "specs-accordeon", faq: "faq-chat", showcase: "showcase-zoom" },
    },
  },
  {
    number: 148,
    id: "combo-serum-avant-apres-ar",
    name: "سيروم قبل وبعد",
    category: "Arabe",
    demoProduct: "serum",
    lang: "ar",
    theme: L({
      primary: "#b45309",
      accent: "#f59e0b",
      bg: "#fffbf3",
      surface: "#fdf1dc",
      surface2: "#fbe5bd",
      text: "#2b1d0b",
      border: "#f3e0bd",
      font: "arabic",
      heading: "arabic",
      radius: 16,
    }),
    hero: { variant: "split", eyebrow: "نتيجة واضحة", title: "الفرق يبان من أول أسبوعين", highlight: "من أول أسبوعين" },
    sections: ["benefits", "how", "reviews", "offers", "order", "guarantee", "faq"],
    pieces: {
      header: "h14-onglets",
      hero: "hero-avant-apres",
      footer: "f16-ticket",
      sections: { benefits: "benefits-numerote", order: "order-etapes", guarantee: "guarantee-carte" },
    },
  },
  {
    number: 149,
    id: "combo-montre-calibre",
    name: "Montre Calibre",
    category: "Premium",
    demoProduct: "watch",
    lang: "fr",
    theme: L({
      primary: "#0f0f0f",
      accent: "#8c7a5b",
      bg: "#fafaf8",
      surface: "#f1f0ec",
      surface2: "#e6e4dd",
      font: "sans",
      heading: "elegant",
      radius: 0,
      headingWeight: 500,
    }),
    hero: { variant: "split", eyebrow: "Mouvement automatique", title: "Le calibre, détaillé", highlight: "détaillé" },
    sections: ["story", "showcase", "specs", "reviews", "guarantee", "order", "faq"],
    pieces: {
      header: "h15-logo-geant",
      hero: "hero-catalogue",
      footer: "f18-degrade",
      sections: { specs: "specs-accordeon", order: "order-plein-ecran", showcase: "showcase-defilante" },
    },
  },
];
