// ─────────────────────────────────────────────────────────────
// Produits de DÉMONSTRATION : utilisés uniquement par la galerie
// de templates et l'aperçu avant création. Les vraies pages
// utilisent toujours le contenu enregistré (content / ai_content).
// ─────────────────────────────────────────────────────────────
import type { DemoProduct as Product, DemoReview as Review, DemoCopy as ProductCopy } from "./demo-types";

const DEFAULT_WHATSAPP = "212600000000"; // ← votre numéro WhatsApp

const reviewers: [string, string][] = [
  ["Yassine B.", "Casablanca"],
  ["Salma E.", "Rabat"],
  ["Mehdi A.", "Marrakech"],
  ["Imane K.", "Tanger"],
  ["Omar T.", "Fès"],
  ["Hajar M.", "Agadir"],
];

const reviews = (texts: string[]): Review[] =>
  texts.map((text, i) => ({
    name: reviewers[i % reviewers.length][0],
    city: reviewers[i % reviewers.length][1],
    rating: i === 3 ? 4 : 5,
    text,
    date: `il y a ${i + 2} jours`,
  }));

const codFaq = [
  { q: "Comment se passe le paiement ?", a: "Vous payez à la livraison (cash on delivery), après avoir vérifié votre colis." },
  { q: "Quel est le délai de livraison ?", a: "24 à 48h dans les grandes villes, 2 à 4 jours ailleurs au Maroc." },
  { q: "La livraison est-elle gratuite ?", a: "Oui, la livraison est offerte partout au Maroc pour toute commande." },
  { q: "Puis-je retourner le produit ?", a: "Oui, vous disposez de 7 jours satisfait ou remboursé." },
];

const codSteps = [
  { title: "Commandez", text: "Remplissez le formulaire en 30 secondes." },
  { title: "Confirmation", text: "Notre équipe vous appelle pour confirmer." },
  { title: "Livraison", text: "Recevez votre colis en 24–48h." },
  { title: "Payez à la réception", text: "Vous payez seulement à la livraison." },
];

const defaultComparison = (us: string[]) =>
  us.map((label) => ({ label, us: true as const, them: false as const }));

const arFaq = [
  { q: "كيفاش كنخلص؟", a: "كتخلص عند الاستلام، من بعد ما تشوف السلعة ديالك." },
  { q: "شحال كياخد التوصيل؟", a: "من 24 حتى 48 ساعة فالمدن الكبرى." },
  { q: "واش التوصيل مجاني؟", a: "إيه، التوصيل مجاني لجميع المدن المغربية." },
];

const arReviews: Review[] = [
  { name: "ياسين", city: "الدار البيضاء", rating: 5, text: "منتوج زوين بزاف والتوصيل كان سريع. أنصح بيه!" },
  { name: "سلمى", city: "الرباط", rating: 5, text: "الجودة ممتازة وكيف ما فالصور بالضبط." },
  { name: "مهدي", city: "مراكش", rating: 5, text: "خدمة زوينة وتعامل محترم. شكرا ليكم." },
];

function product(p: Omit<Product, "whatsapp" | "currency"> & { currency?: string; whatsapp?: string }): Product {
  return { currency: "DH", whatsapp: DEFAULT_WHATSAPP, ...p };
}

const copy = (c: ProductCopy) => c;

export const products: Record<string, Product> = {
  holder: product({
    id: "holder",
    sku: "LP-HOLD-01",
    category: "Accessoires auto",
    price: 199,
    oldPrice: 349,
    images: ["/template-assets/landpro/holder.svg", "/template-assets/landpro/smartphone.svg", "/template-assets/landpro/holder.svg", "/template-assets/landpro/smartphone.svg"],
    rating: 4.9,
    reviewsCount: 1248,
    stock: 17,
    specs: [
      { label: "Charge", value: "Sans fil 15W" },
      { label: "Fixation", value: "Ventouse + grille d'aération" },
      { label: "Compatibilité", value: "Smartphones 4.7\" à 6.9\"" },
      { label: "Rotation", value: "360°" },
      { label: "Garantie", value: "12 mois" },
    ],
    bundles: [
      { qty: 1, label: "1 pièce", price: 199 },
      { qty: 2, label: "2 pièces", price: 349, badge: "Le plus populaire" },
      { qty: 3, label: "3 pièces", price: 449, badge: "Meilleure offre" },
    ],
    variants: [
      { name: "Noir", color: "#16181c" },
      { name: "Argent", color: "#c9ccd3" },
      { name: "Bleu nuit", color: "#1d2a6b" },
    ],
    comparison: [
      { label: "Charge sans fil rapide 15W", us: true, them: false },
      { label: "Serrage automatique", us: true, them: false },
      { label: "Rotation 360°", us: true, them: "Partielle" },
      { label: "Ventouse renforcée", us: true, them: false },
      { label: "Garantie 12 mois", us: true, them: false },
    ],
    stats: [
      { value: "+12 000", label: "Clients satisfaits" },
      { value: "4.9/5", label: "Note moyenne" },
      { value: "24h", label: "Livraison rapide" },
    ],
    steps: codSteps,
    problem: {
      pains: ["Téléphone qui tombe à chaque virage", "Batterie vide pendant le GPS", "Câbles emmêlés partout"],
      solution: "Un support qui tient fermement votre téléphone et le recharge pendant que vous roulez.",
    },
    copy: copy({
      name: "Support Voiture Chargeur Sans Fil",
      tagline: "Rechargez en roulant, en toute sécurité.",
      description:
        "Support magnétique à serrage automatique avec charge sans fil rapide 15W. Installation en 10 secondes, compatible avec tous les smartphones.",
      benefits: ["Charge rapide 15W", "Serrage automatique", "Rotation 360°", "Installation facile"],
      features: [
        { icon: "⚡", title: "Charge rapide", text: "15W sans fil, batterie pleine plus vite." },
        { icon: "🔒", title: "Fixation solide", text: "Ne bouge pas, même sur les routes difficiles." },
        { icon: "🔄", title: "Rotation 360°", text: "Portrait ou paysage en un geste." },
        { icon: "🚗", title: "Universel", text: "Compatible avec toutes les voitures." },
      ],
      reviews: reviews([
        "Très bonne qualité, la charge est rapide et le téléphone ne bouge pas du tout.",
        "Livraison en 24h à Rabat, produit conforme. Je recommande !",
        "Installé en 2 minutes, parfait pour le GPS.",
        "Bon produit, juste la ventouse à bien nettoyer avant de coller.",
        "J'en ai commandé un deuxième pour ma femme 👌",
        "Service client au top, ils m'ont appelé tout de suite.",
      ]),
      faq: codFaq,
    }),
    i18n: {
      ar: {
        name: "حامل الهاتف للسيارة مع شاحن لاسلكي",
        tagline: "شارج تيليفونك وانت سايق بكل أمان",
        description: "حامل أوتوماتيكي مع شحن لاسلكي سريع 15W، كيتركب ف 10 ثواني ومتوافق مع جميع الهواتف.",
        benefits: ["شحن سريع 15W", "تثبيت أوتوماتيكي", "دوران 360°", "تركيب سهل"],
        features: [
          { icon: "⚡", title: "شحن سريع", text: "15W بلا خيوط" },
          { icon: "🔒", title: "تثبيت قوي", text: "ما كيتحركش حتى ف الطريق الصعيبة" },
          { icon: "🔄", title: "دوران 360°", text: "عمودي ولا أفقي" },
          { icon: "🚗", title: "لجميع السيارات", text: "كيتركب ف أي طوموبيل" },
        ],
        reviews: arReviews,
        faq: arFaq,
      },
    },
  }),

  earbuds: product({
    id: "earbuds",
    category: "Audio",
    price: 299,
    oldPrice: 499,
    images: ["/template-assets/landpro/earbuds.svg", "/template-assets/landpro/headphones.svg", "/template-assets/landpro/earbuds.svg"],
    rating: 4.8,
    reviewsCount: 864,
    stock: 23,
    specs: [
      { label: "Autonomie", value: "32h avec boîtier" },
      { label: "Réduction de bruit", value: "Active (ANC)" },
      { label: "Bluetooth", value: "5.3" },
      { label: "Étanchéité", value: "IPX5" },
    ],
    bundles: [
      { qty: 1, label: "1 paire", price: 299 },
      { qty: 2, label: "2 paires", price: 499, badge: "Économisez 99 DH" },
    ],
    variants: [{ name: "Blanc", color: "#f1f2f5" }, { name: "Noir", color: "#1a1b1f" }],
    comparison: defaultComparison(["Réduction de bruit active", "32h d'autonomie", "Bluetooth 5.3", "Résistant à l'eau"]),
    stats: [{ value: "32h", label: "Autonomie" }, { value: "-35dB", label: "Réduction de bruit" }, { value: "4.8/5", label: "Avis clients" }],
    steps: codSteps,
    copy: copy({
      name: "Écouteurs Sans Fil Pro ANC",
      tagline: "Le silence, puis votre musique.",
      description: "Écouteurs à réduction de bruit active, son haute fidélité et 32h d'autonomie avec le boîtier.",
      benefits: ["Réduction de bruit active", "32h d'autonomie", "Son HD", "Résistants à l'eau"],
      features: [
        { icon: "🎧", title: "ANC", text: "Coupez le bruit extérieur." },
        { icon: "🔋", title: "32h", text: "Une semaine sans recharger." },
        { icon: "💧", title: "IPX5", text: "Sport et pluie, aucun souci." },
        { icon: "📶", title: "BT 5.3", text: "Connexion stable et instantanée." },
      ],
      reviews: reviews([
        "Le son est incroyable pour ce prix.",
        "La réduction de bruit marche vraiment dans le tram.",
        "Autonomie top, je recharge une fois par semaine.",
        "Bons écouteurs, boîtier un peu grand.",
      ]),
      faq: codFaq,
    }),
  }),

  perfume: product({
    id: "perfume",
    category: "Parfum",
    price: 390,
    oldPrice: 590,
    images: ["/template-assets/landpro/perfume.svg", "/template-assets/landpro/perfume.svg", "/template-assets/landpro/ring.svg"],
    rating: 4.9,
    reviewsCount: 532,
    stock: 9,
    specs: [
      { label: "Contenance", value: "100 ml" },
      { label: "Famille", value: "Oriental boisé" },
      { label: "Tenue", value: "12h+" },
      { label: "Notes", value: "Oud, ambre, vanille" },
    ],
    bundles: [
      { qty: 1, label: "1 flacon", price: 390 },
      { qty: 2, label: "Coffret duo", price: 690, badge: "Idée cadeau" },
    ],
    comparison: defaultComparison(["Tenue 12h+", "Ingrédients nobles", "Flacon premium", "Coffret cadeau"]),
    steps: codSteps,
    copy: copy({
      name: "Élixir d'Oud – Eau de Parfum",
      tagline: "Un parfum qui raconte votre histoire.",
      description: "Une fragrance orientale boisée aux notes d'oud, d'ambre et de vanille, d'une tenue exceptionnelle.",
      benefits: ["Tenue 12h+", "Notes rares", "Sillage intense", "Flacon de luxe"],
      features: [
        { icon: "✨", title: "Notes rares", text: "Oud, ambre et vanille." },
        { icon: "⏳", title: "Tenue 12h", text: "Du matin au soir." },
        { icon: "🎁", title: "Coffret", text: "Prêt à offrir." },
        { icon: "🌿", title: "Qualité", text: "Ingrédients sélectionnés." },
      ],
      reviews: reviews([
        "Sillage magnifique, on me demande toujours le nom.",
        "Tient toute la journée, très élégant.",
        "Le coffret est superbe pour offrir.",
        "Très bon parfum, un peu fort au début.",
      ]),
      faq: codFaq,
    }),
    i18n: {
      ar: {
        name: "إكسير العود – عطر فاخر",
        tagline: "فخامة وجودة في كل تفصيلة",
        description: "عطر شرقي خشبي بنوتات العود والعنبر والفانيلا، ثبات كيدوم أكثر من 12 ساعة.",
        benefits: ["ثبات +12 ساعة", "نوتات نادرة", "فوحان قوي", "قارورة فاخرة"],
        features: [
          { icon: "✨", title: "نوتات نادرة", text: "عود، عنبر و فانيلا" },
          { icon: "⏳", title: "ثبات طويل", text: "من الصباح حتى الليل" },
          { icon: "🎁", title: "علبة هدية", text: "واجد للإهداء" },
          { icon: "🌿", title: "جودة عالية", text: "مكونات مختارة" },
        ],
        reviews: arReviews,
        faq: arFaq,
      },
    },
  }),

  watch: product({
    id: "watch",
    category: "Montres",
    price: 1290,
    oldPrice: 1890,
    images: ["/template-assets/landpro/watch.svg", "/template-assets/landpro/watch.svg", "/template-assets/landpro/ring.svg"],
    rating: 4.9,
    reviewsCount: 318,
    stock: 6,
    specs: [
      { label: "Mouvement", value: "Automatique" },
      { label: "Boîtier", value: "Acier 42 mm" },
      { label: "Verre", value: "Saphir" },
      { label: "Étanchéité", value: "100 m" },
    ],
    bundles: [{ qty: 1, label: "1 montre", price: 1290 }, { qty: 1, label: "Montre + bracelet cuir", price: 1490, badge: "Pack premium" }],
    variants: [{ name: "Noir & or", color: "#1a1a1a" }, { name: "Acier", color: "#bfc3ca" }, { name: "Bleu", color: "#1e2f5a" }],
    comparison: defaultComparison(["Verre saphir", "Mouvement automatique", "Étanche 100 m", "Garantie 2 ans"]),
    steps: codSteps,
    copy: copy({
      name: "Montre Automatique Héritage",
      tagline: "L'excellence au quotidien.",
      description: "Une montre automatique au boîtier acier 42 mm, verre saphir et finitions dorées.",
      benefits: ["Verre saphir", "Mouvement automatique", "Étanche 100 m", "Garantie 2 ans"],
      features: [
        { icon: "⌚", title: "Automatique", text: "Aucune pile nécessaire." },
        { icon: "💎", title: "Saphir", text: "Résiste aux rayures." },
        { icon: "🌊", title: "100 m", text: "Étanchéité plongée." },
        { icon: "🛡️", title: "2 ans", text: "Garantie constructeur." },
      ],
      reviews: reviews(["Finitions superbes.", "Très élégante au poignet.", "Livraison soignée, coffret magnifique.", "Bracelet un peu rigide au début."]),
      faq: codFaq,
    }),
  }),

  serum: product({
    id: "serum",
    category: "Soin visage",
    price: 189,
    oldPrice: 290,
    images: ["/template-assets/landpro/serum.svg", "/template-assets/landpro/serum.svg", "/template-assets/landpro/shampoo.svg"],
    rating: 4.8,
    reviewsCount: 2104,
    stock: 31,
    specs: [
      { label: "Contenance", value: "30 ml" },
      { label: "Actif", value: "Acide hyaluronique 2% + B5" },
      { label: "Peau", value: "Tous types" },
      { label: "Testé", value: "Dermatologiquement" },
    ],
    bundles: [
      { qty: 1, label: "1 flacon", price: 189 },
      { qty: 2, label: "2 flacons", price: 329, badge: "Populaire" },
      { qty: 3, label: "Cure 3 mois", price: 449, badge: "Meilleure offre" },
    ],
    comparison: defaultComparison(["Testé dermatologiquement", "Sans parfum", "Résultats en 14 jours", "Vegan"]),
    stats: [{ value: "94%", label: "Peau plus hydratée" }, { value: "14 j", label: "Premiers résultats" }, { value: "+20 000", label: "Clientes" }],
    steps: [
      { title: "Nettoyez", text: "Visage propre et sec." },
      { title: "Appliquez", text: "3 gouttes matin et soir." },
      { title: "Massez", text: "Mouvements circulaires." },
      { title: "Protégez", text: "Finissez par une crème SPF." },
    ],
    problem: {
      pains: ["Peau terne et déshydratée", "Ridules visibles", "Teint irrégulier"],
      solution: "Un sérum concentré qui hydrate en profondeur et révèle l'éclat naturel de votre peau.",
    },
    copy: copy({
      name: "Sérum Éclat Hyaluronique",
      tagline: "Une peau plus belle chaque jour.",
      description: "Sérum à l'acide hyaluronique et vitamine B5 : hydratation intense, peau repulpée, teint lumineux.",
      benefits: ["Hydratation 72h", "Peau repulpée", "Teint lumineux", "Sans parfum"],
      features: [
        { icon: "💧", title: "Hydratation", text: "Jusqu'à 72h." },
        { icon: "✨", title: "Éclat", text: "Teint unifié et lumineux." },
        { icon: "🧪", title: "Clinique", text: "Testé dermatologiquement." },
        { icon: "🌱", title: "Vegan", text: "Sans ingrédients animaux." },
      ],
      reviews: reviews([
        "Ma peau n'a jamais été aussi douce.",
        "Résultats visibles après 2 semaines.",
        "Texture légère, pénètre vite.",
        "Bien mais il faut être régulière.",
        "Je suis à mon 3e flacon !",
      ]),
      faq: codFaq,
    }),
    i18n: {
      ar: {
        name: "سيروم الإشراقة بحمض الهيالورونيك",
        tagline: "منتوج رائع و فعال!",
        description: "سيروم كيرطب البشرة بعمق وكيعطيها إشراقة طبيعية من أول أسبوعين.",
        benefits: ["ترطيب 72 ساعة", "بشرة ممتلئة", "إشراقة طبيعية", "بلا عطر"],
        features: [
          { icon: "💧", title: "ترطيب عميق", text: "حتى 72 ساعة" },
          { icon: "✨", title: "إشراقة", text: "بشرة موحدة" },
          { icon: "🧪", title: "مجرب", text: "من طرف أطباء الجلد" },
          { icon: "🌱", title: "طبيعي", text: "مكونات نباتية" },
        ],
        reviews: arReviews,
        faq: arFaq,
      },
    },
  }),

  headphones: product({
    id: "headphones",
    category: "Audio",
    price: 549,
    oldPrice: 799,
    images: ["/template-assets/landpro/headphones.svg", "/template-assets/landpro/earbuds.svg", "/template-assets/landpro/headphones.svg"],
    rating: 4.8,
    reviewsCount: 641,
    specs: [{ label: "Autonomie", value: "40h" }, { label: "ANC", value: "Hybride" }, { label: "Poids", value: "250 g" }],
    bundles: [{ qty: 1, label: "1 casque", price: 549 }, { qty: 2, label: "2 casques", price: 949, badge: "Duo" }],
    comparison: defaultComparison(["ANC hybride", "40h d'autonomie", "Pliable", "Micro HD"]),
    steps: codSteps,
    copy: copy({
      name: "Casque Studio Sans Fil",
      tagline: "Un son exceptionnel.",
      description: "Casque circum-auriculaire à réduction de bruit hybride, 40h d'autonomie et confort premium.",
      benefits: ["Son studio", "40h d'autonomie", "Confort mémoire de forme", "Pliable"],
      features: [
        { icon: "🎵", title: "Son studio", text: "Basses profondes, aigus précis." },
        { icon: "🔋", title: "40h", text: "Autonomie record." },
        { icon: "🤫", title: "ANC", text: "Réduction de bruit hybride." },
        { icon: "☁️", title: "Confort", text: "Coussinets mémoire de forme." },
      ],
      reviews: reviews(["Son incroyable.", "Très confortable pour de longues sessions.", "Autonomie folle.", "Un peu lourd après 3h."]),
      faq: codFaq,
    }),
  }),

  smartphone: product({
    id: "smartphone",
    category: "Smartphones",
    price: 3990,
    oldPrice: 4590,
    images: ["/template-assets/landpro/smartphone.svg", "/template-assets/landpro/smartphone.svg", "/template-assets/landpro/earbuds.svg"],
    rating: 4.9,
    reviewsCount: 1502,
    specs: [
      { label: "Écran", value: "6.7\" AMOLED 120Hz" },
      { label: "Stockage", value: "256 Go" },
      { label: "Caméra", value: "50 MP triple capteur" },
      { label: "Batterie", value: "5000 mAh" },
    ],
    bundles: [{ qty: 1, label: "128 Go", price: 3590 }, { qty: 1, label: "256 Go", price: 3990, badge: "Recommandé" }, { qty: 1, label: "512 Go", price: 4590 }],
    variants: [{ name: "Titane", color: "#c9ccd3" }, { name: "Violet", color: "#6e2ca8" }, { name: "Noir", color: "#111" }],
    comparison: defaultComparison(["Écran 120Hz", "Caméra 50 MP", "Charge rapide 65W", "Garantie 2 ans"]),
    steps: codSteps,
    copy: copy({
      name: "Smartphone Pro X",
      tagline: "L'innovation dans vos mains.",
      description: "Écran AMOLED 120Hz, triple caméra 50 MP et batterie 5000 mAh dans un design titane.",
      benefits: ["Écran 120Hz", "Caméra 50 MP", "Batterie 2 jours", "Design titane"],
      features: [
        { icon: "📱", title: "AMOLED 120Hz", text: "Fluidité extrême." },
        { icon: "📷", title: "50 MP", text: "Photos de nuit nettes." },
        { icon: "🔋", title: "5000 mAh", text: "Deux jours d'autonomie." },
        { icon: "⚡", title: "65W", text: "100% en 35 minutes." },
      ],
      reviews: reviews(["Fluide et rapide.", "Les photos de nuit sont bluffantes.", "Batterie qui tient 2 jours.", "Un peu glissant sans coque."]),
      faq: codFaq,
    }),
  }),

  sneaker: product({
    id: "sneaker",
    category: "Sport",
    price: 690,
    oldPrice: 990,
    images: ["/template-assets/landpro/sneaker.svg", "/template-assets/landpro/sneaker.svg", "/template-assets/landpro/hoodie.svg"],
    rating: 4.8,
    reviewsCount: 789,
    stock: 12,
    specs: [{ label: "Tailles", value: "39 → 46" }, { label: "Semelle", value: "Mousse réactive" }, { label: "Poids", value: "280 g" }],
    bundles: [{ qty: 1, label: "1 paire", price: 690 }, { qty: 2, label: "2 paires", price: 1190, badge: "Duo" }],
    variants: [{ name: "Black/Red", color: "#111" }, { name: "White", color: "#f4f4f4" }, { name: "Grey", color: "#8b8f97" }],
    comparison: defaultComparison(["Amorti réactif", "Mesh respirant", "Semelle antidérapante", "Ultra légère"]),
    steps: codSteps,
    copy: copy({
      name: "Runner Velocity",
      tagline: "Repoussez vos limites.",
      description: "Chaussure de running ultra-légère avec amorti réactif et tige en mesh respirant.",
      benefits: ["Amorti réactif", "Ultra légère", "Respirante", "Accroche maximale"],
      features: [
        { icon: "🏃", title: "Réactive", text: "Restitution d'énergie." },
        { icon: "🪶", title: "280 g", text: "Ultra légère." },
        { icon: "🌬️", title: "Mesh", text: "Respirabilité totale." },
        { icon: "🧲", title: "Grip", text: "Semelle antidérapante." },
      ],
      reviews: reviews(["Très confortables pour courir.", "Légères et stylées.", "Taille normalement.", "Bonne qualité pour le prix."]),
      faq: codFaq,
    }),
  }),

  ring: product({
    id: "ring",
    category: "Bijoux",
    price: 890,
    oldPrice: 1290,
    images: ["/template-assets/landpro/ring.svg", "/template-assets/landpro/ring.svg", "/template-assets/landpro/watch.svg"],
    rating: 5,
    reviewsCount: 214,
    specs: [{ label: "Métal", value: "Argent 925 plaqué or 18k" }, { label: "Pierre", value: "Zircon taille brillant" }, { label: "Tailles", value: "48 → 60" }],
    bundles: [{ qty: 1, label: "1 bague", price: 890 }, { qty: 2, label: "Duo alliances", price: 1590, badge: "Couple" }],
    comparison: defaultComparison(["Argent 925", "Plaqué or 18k", "Hypoallergénique", "Écrin offert"]),
    steps: codSteps,
    copy: copy({
      name: "Bague Solitaire Éternelle",
      tagline: "Timeless elegance.",
      description: "Bague en argent 925 plaqué or 18 carats, sertie d'un zircon taille brillant.",
      benefits: ["Argent 925", "Or 18k", "Hypoallergénique", "Écrin offert"],
      features: [
        { icon: "💍", title: "Or 18k", text: "Éclat durable." },
        { icon: "💎", title: "Zircon", text: "Taille brillant." },
        { icon: "🤍", title: "Hypoallergénique", text: "Peaux sensibles." },
        { icon: "🎁", title: "Écrin", text: "Prêt à offrir." },
      ],
      reviews: reviews(["Magnifique, elle brille énormément.", "Parfaite pour une demande.", "L'écrin est très beau.", "Taille un peu petite, prenez une au-dessus."]),
      faq: codFaq,
    }),
  }),

  airfryer: product({
    id: "airfryer",
    category: "Cuisine",
    price: 799,
    oldPrice: 1199,
    images: ["/template-assets/landpro/airfryer.svg", "/template-assets/landpro/airfryer.svg", "/template-assets/landpro/plant.svg"],
    rating: 4.8,
    reviewsCount: 1873,
    stock: 14,
    specs: [{ label: "Capacité", value: "6 L" }, { label: "Puissance", value: "1700 W" }, { label: "Programmes", value: "8 automatiques" }],
    bundles: [{ qty: 1, label: "Air fryer", price: 799 }, { qty: 1, label: "Air fryer + kit accessoires", price: 899, badge: "Pack chef" }],
    comparison: defaultComparison(["90% de gras en moins", "8 programmes", "Panier antiadhésif", "Lavable au lave-vaisselle"]),
    stats: [{ value: "-90%", label: "de matières grasses" }, { value: "6 L", label: "Capacité familiale" }, { value: "15 min", label: "Frites croustillantes" }],
    steps: codSteps,
    copy: copy({
      name: "Air Fryer Digital 6L",
      tagline: "Cuisinez plus sain, chaque jour.",
      description: "Friteuse sans huile 6L avec écran tactile et 8 programmes : frites, poulet, gâteaux et plus.",
      benefits: ["Sans huile", "6 litres", "8 programmes", "Nettoyage facile"],
      features: [
        { icon: "🍟", title: "Sans huile", text: "Croustillant, sans gras." },
        { icon: "👨‍👩‍👧", title: "6 L", text: "Pour toute la famille." },
        { icon: "📲", title: "Tactile", text: "8 programmes auto." },
        { icon: "🧽", title: "Facile", text: "Panier lave-vaisselle." },
      ],
      reviews: reviews(["Les frites sont parfaites.", "On l'utilise tous les jours.", "Grande capacité, idéal famille.", "Un peu bruyant mais efficace."]),
      faq: codFaq,
    }),
  }),

  spray: product({
    id: "spray",
    category: "Entretien",
    price: 99,
    oldPrice: 149,
    images: ["/template-assets/landpro/spray.svg", "/template-assets/landpro/spray.svg", "/template-assets/landpro/bottle.svg"],
    rating: 4.7,
    reviewsCount: 956,
    specs: [{ label: "Contenance", value: "750 ml" }, { label: "Surfaces", value: "Toutes" }, { label: "Formule", value: "Biodégradable" }],
    bundles: [{ qty: 1, label: "1 spray", price: 99 }, { qty: 3, label: "Lot de 3", price: 229, badge: "Économique" }],
    comparison: defaultComparison(["Dégraissant puissant", "Sans traces", "Biodégradable", "Odeur fraîche"]),
    steps: codSteps,
    problem: { pains: ["Graisse incrustée", "Traces sur les vitres", "Produits toxiques"], solution: "Un nettoyant puissant, biodégradable et sans traces." },
    copy: copy({
      name: "Nettoyant Multi-Surfaces Pro",
      tagline: "Un nettoyage puissant, en toute simplicité.",
      description: "Dégraissant multi-surfaces biodégradable, sans traces, au parfum frais.",
      benefits: ["Dégraisse en 1 passage", "Sans traces", "Biodégradable", "Parfum frais"],
      features: [
        { icon: "🧼", title: "Puissant", text: "Graisse éliminée." },
        { icon: "✨", title: "Sans traces", text: "Vitres impeccables." },
        { icon: "🌍", title: "Bio", text: "Formule biodégradable." },
        { icon: "🍋", title: "Frais", text: "Odeur citronnée." },
      ],
      reviews: reviews(["Efficace sur la hotte !", "Pas de traces sur le miroir.", "Odeur agréable.", "Très bon rapport qualité/prix."]),
      faq: codFaq,
    }),
  }),

  chair: product({
    id: "chair",
    category: "Mobilier",
    price: 1890,
    oldPrice: 2490,
    images: ["/template-assets/landpro/chair.svg", "/template-assets/landpro/chair.svg", "/template-assets/landpro/plant.svg"],
    rating: 4.8,
    reviewsCount: 402,
    specs: [{ label: "Dimensions", value: "78 × 72 × 85 cm" }, { label: "Tissu", value: "Bouclette" }, { label: "Pieds", value: "Hêtre massif" }],
    bundles: [{ qty: 1, label: "1 fauteuil", price: 1890 }, { qty: 2, label: "2 fauteuils", price: 3390, badge: "-390 DH" }],
    variants: [{ name: "Caramel", color: "#c89463" }, { name: "Crème", color: "#efe6d8" }, { name: "Vert sauge", color: "#9caf88" }],
    comparison: defaultComparison(["Bois massif", "Tissu déhoussable", "Montage 5 min", "Garantie 5 ans"]),
    steps: codSteps,
    copy: copy({
      name: "Fauteuil Lounge Bouclette",
      tagline: "Du mobilier moderne pour une maison meilleure.",
      description: "Fauteuil au design organique, tissu bouclette doux et pieds en hêtre massif.",
      benefits: ["Bois massif", "Ultra confortable", "Déhoussable", "Livraison montée"],
      features: [
        { icon: "🪵", title: "Hêtre massif", text: "Solide et durable." },
        { icon: "🛋️", title: "Confort", text: "Assise moelleuse." },
        { icon: "🧺", title: "Déhoussable", text: "Entretien facile." },
        { icon: "🚚", title: "Livré", text: "Livraison offerte." },
      ],
      reviews: reviews(["Magnifique dans mon salon.", "Très confortable.", "Couleur fidèle aux photos.", "Livraison un peu longue mais ça valait le coup."]),
      faq: codFaq,
    }),
  }),

  dryer: product({
    id: "dryer",
    category: "Beauté tech",
    price: 1490,
    oldPrice: 2190,
    images: ["/template-assets/landpro/dryer.svg", "/template-assets/landpro/dryer.svg", "/template-assets/landpro/shampoo.svg"],
    rating: 4.9,
    reviewsCount: 733,
    specs: [{ label: "Moteur", value: "110 000 tr/min" }, { label: "Température", value: "Contrôle intelligent" }, { label: "Embouts", value: "5 magnétiques" }],
    bundles: [{ qty: 1, label: "Sèche-cheveux", price: 1490 }, { qty: 1, label: "+ étui de voyage", price: 1590, badge: "Coffret" }],
    comparison: defaultComparison(["Moteur digital", "Protection anti-chaleur", "Séchage 2× plus rapide", "5 embouts"]),
    steps: codSteps,
    copy: copy({
      name: "Sèche-Cheveux Supersonic",
      tagline: "Puissant. Intelligent. Beau.",
      description: "Moteur digital ultra-rapide et contrôle intelligent de la chaleur pour protéger vos cheveux.",
      benefits: ["Séchage ultra-rapide", "Cheveux protégés", "Silencieux", "5 embouts"],
      features: [
        { icon: "🌀", title: "110k tr/min", text: "Moteur digital." },
        { icon: "🌡️", title: "Chaleur maîtrisée", text: "40 mesures/seconde." },
        { icon: "🔇", title: "Silencieux", text: "Confort d'utilisation." },
        { icon: "🧲", title: "Magnétique", text: "5 embouts." },
      ],
      reviews: reviews(["Séchage en 5 minutes !", "Mes cheveux sont plus brillants.", "Très beau design.", "Cher mais vaut le coup."]),
      faq: codFaq,
    }),
  }),

  gamepad: product({
    id: "gamepad",
    category: "Gaming",
    price: 449,
    oldPrice: 649,
    images: ["/template-assets/landpro/gamepad.svg", "/template-assets/landpro/gamepad.svg", "/template-assets/landpro/headphones.svg"],
    rating: 4.8,
    reviewsCount: 1120,
    specs: [{ label: "Connexion", value: "Sans fil 2.4G + BT" }, { label: "Autonomie", value: "30h" }, { label: "Compatibilité", value: "PC / Console / Mobile" }],
    bundles: [{ qty: 1, label: "1 manette", price: 449 }, { qty: 2, label: "2 manettes", price: 799, badge: "Multijoueur" }],
    comparison: defaultComparison(["Latence < 1 ms", "Joysticks à effet Hall", "RGB personnalisable", "30h d'autonomie"]),
    steps: codSteps,
    copy: copy({
      name: "Manette Pro RGB",
      tagline: "Play without limits.",
      description: "Manette sans fil à latence ultra-faible, joysticks anti-drift et éclairage RGB.",
      benefits: ["Latence < 1ms", "Anti-drift", "RGB", "Multi-plateforme"],
      features: [
        { icon: "🎮", title: "Pro", text: "Gâchettes réglables." },
        { icon: "⚡", title: "< 1 ms", text: "Latence minimale." },
        { icon: "🌈", title: "RGB", text: "16M couleurs." },
        { icon: "🔋", title: "30h", text: "Sessions sans fin." },
      ],
      reviews: reviews(["Réactive et précise.", "Le RGB est magnifique.", "Compatible PC sans souci.", "Un peu lourde."]),
      faq: codFaq,
    }),
  }),

  hoodie: product({
    id: "hoodie",
    category: "Streetwear",
    price: 349,
    oldPrice: 499,
    images: ["/template-assets/landpro/hoodie.svg", "/template-assets/landpro/hoodie.svg", "/template-assets/landpro/sneaker.svg"],
    rating: 4.8,
    reviewsCount: 567,
    stock: 8,
    specs: [{ label: "Matière", value: "Coton 400 g/m²" }, { label: "Coupe", value: "Oversize" }, { label: "Tailles", value: "S → XXL" }],
    bundles: [{ qty: 1, label: "1 hoodie", price: 349 }, { qty: 2, label: "2 hoodies", price: 599, badge: "Duo" }],
    variants: [{ name: "Noir", color: "#121214" }, { name: "Gris", color: "#7b7f86" }, { name: "Crème", color: "#ece3d3" }],
    comparison: defaultComparison(["Coton épais 400 g", "Coupe oversize", "Édition limitée", "Broderie premium"]),
    steps: codSteps,
    copy: copy({
      name: "Hoodie Oversize Édition Limitée",
      tagline: "Limited drop.",
      description: "Hoodie oversize en coton épais 400 g/m², broderie ton sur ton. Quantités limitées.",
      benefits: ["Coton épais", "Oversize", "Édition limitée", "Broderie"],
      features: [
        { icon: "🧵", title: "400 g/m²", text: "Coton premium." },
        { icon: "📐", title: "Oversize", text: "Coupe moderne." },
        { icon: "🔥", title: "Limité", text: "Pas de réassort." },
        { icon: "🏷️", title: "Brodé", text: "Finitions soignées." },
      ],
      reviews: reviews(["Qualité incroyable.", "La coupe est parfaite.", "Très épais, idéal hiver.", "Prenez votre taille habituelle."]),
      faq: codFaq,
    }),
  }),

  bottle: product({
    id: "bottle",
    category: "Maison",
    price: 179,
    oldPrice: 249,
    images: ["/template-assets/landpro/bottle.svg", "/template-assets/landpro/bottle.svg", "/template-assets/landpro/spray.svg"],
    rating: 4.7,
    reviewsCount: 640,
    specs: [{ label: "Contenance", value: "1 L" }, { label: "Isolation", value: "24h froid / 12h chaud" }, { label: "Matière", value: "Inox 18/8" }],
    bundles: [{ qty: 1, label: "1 gourde", price: 179 }, { qty: 2, label: "2 gourdes", price: 299, badge: "Famille" }],
    comparison: defaultComparison(["Inox sans BPA", "24h froid", "Anti-fuite", "Lave-vaisselle"]),
    steps: codSteps,
    copy: copy({
      name: "Gourde Isotherme Inox 1L",
      tagline: "Une maison plus propre, plus facilement.",
      description: "Gourde isotherme double paroi : 24h froid, 12h chaud, sans BPA.",
      benefits: ["24h froid", "Sans BPA", "Anti-fuite", "Écologique"],
      features: [
        { icon: "❄️", title: "24h", text: "Boissons fraîches." },
        { icon: "♻️", title: "Éco", text: "Zéro plastique." },
        { icon: "🔒", title: "Anti-fuite", text: "Dans le sac sans souci." },
        { icon: "🧼", title: "Facile", text: "Lave-vaisselle." },
      ],
      reviews: reviews(["L'eau reste froide toute la journée.", "Solide et belle.", "Parfaite pour le sport.", "Un peu lourde pleine."]),
      faq: codFaq,
    }),
  }),

  speaker: product({
    id: "speaker",
    category: "Maison connectée",
    price: 599,
    oldPrice: 849,
    images: ["/template-assets/landpro/speaker.svg", "/template-assets/landpro/smartphone.svg", "/template-assets/landpro/speaker.svg"],
    rating: 4.8,
    reviewsCount: 488,
    specs: [{ label: "Connexion", value: "Wi-Fi + Bluetooth" }, { label: "Assistant", value: "Commande vocale" }, { label: "Application", value: "iOS & Android" }],
    bundles: [{ qty: 1, label: "1 enceinte", price: 599 }, { qty: 2, label: "Pack 2 pièces", price: 999, badge: "Multiroom" }],
    comparison: defaultComparison(["Contrôle vocal", "Multiroom", "Pilotage maison", "Son 360°"]),
    steps: codSteps,
    copy: copy({
      name: "Hub Maison Intelligente",
      tagline: "Une maison plus intelligente pour une vie meilleure.",
      description: "Enceinte connectée qui pilote lumières, prises et caméras à la voix ou depuis l'application.",
      benefits: ["Commande vocale", "Pilotage à distance", "Son 360°", "Installation 2 min"],
      features: [
        { icon: "🗣️", title: "Vocal", text: "Contrôle à la voix." },
        { icon: "💡", title: "Lumières", text: "Scènes automatiques." },
        { icon: "📱", title: "Appli", text: "Partout, tout le temps." },
        { icon: "🔊", title: "360°", text: "Son immersif." },
      ],
      reviews: reviews(["Installation super simple.", "Toute la maison est connectée.", "Le son est bon.", "L'appli pourrait être plus rapide."]),
      faq: codFaq,
    }),
  }),

  shampoo: product({
    id: "shampoo",
    category: "Cheveux",
    price: 149,
    oldPrice: 229,
    images: ["/template-assets/landpro/shampoo.svg", "/template-assets/landpro/shampoo.svg", "/template-assets/landpro/serum.svg"],
    rating: 4.8,
    reviewsCount: 1390,
    specs: [{ label: "Contenance", value: "300 ml" }, { label: "Actif", value: "Huile d'argan + kératine" }, { label: "Cheveux", value: "Abîmés, secs" }],
    bundles: [{ qty: 1, label: "1 flacon", price: 149 }, { qty: 2, label: "Shampoing + masque", price: 249, badge: "Routine" }],
    comparison: defaultComparison(["Huile d'argan du Maroc", "Sans sulfates", "Anti-casse", "Brillance"]),
    steps: codSteps,
    problem: { pains: ["Cheveux secs et cassants", "Frisottis", "Pointes fourchues"], solution: "Une formule réparatrice à l'argan qui transforme vos cheveux dès la 1re utilisation." },
    copy: copy({
      name: "Soin Réparateur Argan & Kératine",
      tagline: "Transformez vos cheveux.",
      description: "Shampoing sans sulfates à l'huile d'argan et kératine : répare, nourrit, fait briller.",
      benefits: ["Répare", "Nourrit", "Anti-frisottis", "Sans sulfates"],
      features: [
        { icon: "🌰", title: "Argan", text: "Origine Maroc." },
        { icon: "💪", title: "Kératine", text: "Anti-casse." },
        { icon: "✨", title: "Brillance", text: "Dès le 1er lavage." },
        { icon: "🚫", title: "Sans sulfates", text: "Doux pour le cuir chevelu." },
      ],
      reviews: reviews(["Mes cheveux sont doux comme jamais.", "Plus de frisottis !", "Odeur divine.", "Bien, mousse peu (normal sans sulfates)."]),
      faq: codFaq,
    }),
  }),

  abaya: product({
    id: "abaya",
    category: "Mode modeste",
    price: 459,
    oldPrice: 650,
    images: ["/template-assets/landpro/abaya.svg", "/template-assets/landpro/abaya.svg", "/template-assets/landpro/abaya.svg"],
    rating: 4.9,
    reviewsCount: 377,
    specs: [{ label: "Tissu", value: "Crêpe fluide" }, { label: "Tailles", value: "S → XXL" }, { label: "Entretien", value: "Lavable 30°" }],
    bundles: [{ qty: 1, label: "1 abaya", price: 459 }, { qty: 2, label: "2 abayas", price: 799, badge: "Duo" }],
    variants: [{ name: "Prune", color: "#6a3352" }, { name: "Noir", color: "#141414" }, { name: "Taupe", color: "#8f7a6a" }, { name: "Rose poudré", color: "#d9a7b4" }],
    comparison: defaultComparison(["Crêpe premium", "Coupe fluide", "Finitions main", "Lavable machine"]),
    steps: codSteps,
    copy: copy({
      name: "Abaya Élégance Modeste",
      tagline: "L'élégance en toute simplicité.",
      description: "Abaya en crêpe fluide, coupe ample et finitions délicates. Disponible en 4 coloris.",
      benefits: ["Crêpe fluide", "Coupe ample", "4 coloris", "Finitions soignées"],
      features: [
        { icon: "🧕", title: "Modeste", text: "Coupe ample." },
        { icon: "🪡", title: "Finitions", text: "Cousue avec soin." },
        { icon: "🎨", title: "4 coloris", text: "Pour toutes les occasions." },
        { icon: "🧺", title: "Facile", text: "Lavable 30°." },
      ],
      reviews: reviews(["Tissu magnifique et fluide.", "Taille parfaitement.", "Couleur prune sublime.", "Un peu longue pour moi (1m58)."]),
      faq: codFaq,
    }),
    i18n: {
      ar: {
        name: "عباية الأناقة",
        tagline: "أناقة و بساطة",
        description: "عباية بثوب كريب خفيف، قصة واسعة و تفاصيل راقية. متوفرة ب 4 ألوان.",
        benefits: ["ثوب خفيف", "قصة واسعة", "4 ألوان", "خياطة متقنة"],
        reviews: arReviews,
        faq: arFaq,
      },
    },
  }),

  plant: product({
    id: "plant",
    category: "Bien-être naturel",
    price: 229,
    oldPrice: 329,
    images: ["/template-assets/landpro/plant.svg", "/template-assets/landpro/serum.svg", "/template-assets/landpro/plant.svg"],
    rating: 4.8,
    reviewsCount: 812,
    specs: [{ label: "Format", value: "60 gélules" }, { label: "Composition", value: "Plantes bio" }, { label: "Cure", value: "1 mois" }],
    bundles: [{ qty: 1, label: "1 mois", price: 229 }, { qty: 3, label: "Cure 3 mois", price: 549, badge: "Recommandé" }],
    comparison: defaultComparison(["100% naturel", "Certifié bio", "Sans additifs", "Fabriqué au Maroc"]),
    steps: codSteps,
    copy: copy({
      name: "Complément Vitalité Bio",
      tagline: "Pur. Naturel. Efficace.",
      description: "Complément aux plantes bio pour l'énergie et le bien-être au quotidien.",
      benefits: ["100% naturel", "Énergie", "Bio certifié", "Sans additifs"],
      features: [
        { icon: "🌿", title: "Bio", text: "Plantes certifiées." },
        { icon: "⚡", title: "Énergie", text: "Vitalité durable." },
        { icon: "🧘", title: "Équilibre", text: "Bien-être global." },
        { icon: "🇲🇦", title: "Local", text: "Fabriqué au Maroc." },
      ],
      reviews: reviews(["Je me sens plus en forme.", "Produit naturel, ça rassure.", "Livraison rapide.", "Résultats après 3 semaines."]),
      faq: codFaq,
    }),
  }),
};

export function getDemoProduct(id: string): Product {
  return products[id] ?? products.holder;
}
