// ─────────────────────────────────────────────────────────────
// LES 60 TEMPLATES LANDPRO
// Pour modifier un template : couleurs dans `theme`, style d'en-tête
// dans `hero.variant`, sections par défaut dans `sections`.
// Les identifiants 01→35 sont ceux déjà enregistrés dans les pages
// existantes : ne pas les renommer (sinon ajouter un alias).
// ─────────────────────────────────────────────────────────────
import type { SectionKey, TemplateDef } from "./types";
import { darkTheme as D, lightTheme as L } from "./theme";

const raw: Omit<TemplateDef, "description">[] = [
  // ════════════════ 01 → 30 : COD & conversion ════════════════
  {
    number: 1,
    id: "cod-direct",
    name: "COD Direct S11 Style",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: L({
      primary: "#16a34a",
      accent: "#16a34a",
      heroBg: "linear-gradient(180deg,#f0fdf4,#fff)",
      font: "display",
      heading: "display",
    }),
    hero: {
      variant: "split",
      eyebrow: "🔥 Best-seller au Maroc",
      title: "Rechargez en roulant, en toute sécurité",
      highlight: "en toute sécurité",
      badge: "-43%",
    },
    sections: [
      "announcement",
      "trust",
      "features",
      "showcase",
      "how",
      "reviews",
      "offers",
      "order",
      "guarantee",
      "faq",
    ],
  },
  {
    number: 2,
    id: "premium-product",
    name: "Premium Product",
    category: "Premium",
    demoProduct: "perfume",
    lang: "fr",
    theme: D({
      bg: "#0e0b07",
      surface: "#17120b",
      surface2: "#211a10",
      border: "#3a2e1c",
      primary: "#c9a45a",
      primaryText: "#140f08",
      accent: "#e3c27a",
      font: "sans",
      heading: "serif",
      headingWeight: 400,
      radius: 6,
    }),
    hero: {
      variant: "luxury",
      eyebrow: "Collection signature",
      title: "Élégance Naturelle",
      subtitle: "Une fragrance orientale boisée, pensée pour durer.",
    },
    sections: ["features", "story", "specs", "reviews", "order", "guarantee", "faq"],
  },
  {
    number: 3,
    id: "ugc-social",
    name: "UGC Social Ads",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: L({
      primary: "#2563eb",
      accent: "#f97316",
      surface: "#fff7ed",
      surface2: "#ffedd5",
      heading: "display",
      radius: 18,
    }),
    hero: { variant: "ugc", eyebrow: "Vu sur les réseaux 📱", title: "Le choix des créateurs", highlight: "créateurs" },
    sections: ["ugc", "features", "reviews", "offers", "order", "faq"],
  },
  {
    number: 4,
    id: "problem-solver",
    name: "Problem Solution",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#e11d48", accent: "#e11d48", surface: "#fff1f2", surface2: "#ffe4e6", heading: "display" }),
    hero: {
      variant: "problem",
      title: "Fini le téléphone qui tombe !",
      highlight: "qui tombe !",
      subtitle: "Marre de chercher votre GPS par terre à chaque virage ? Il existe une solution simple.",
    },
    sections: ["problem", "features", "before_after", "reviews", "order", "faq"],
  },
  {
    number: 5,
    id: "marketplace-cod",
    name: "Marketplace COD",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#2563eb", accent: "#ea580c", radius: 10 }),
    hero: {
      variant: "marketplace",
      eyebrow: "⭐ N°1 des ventes",
      title: "Support Voiture Chargeur Sans Fil 15W – Serrage Automatique",
    },
    sections: ["trust", "features", "specs", "how", "comparison", "reviews", "order", "faq"],
  },
  {
    number: 6,
    id: "flash-sale",
    name: "Flash Sale",
    category: "Conversion",
    demoProduct: "earbuds",
    lang: "fr",
    theme: L({
      primary: "#e11d48",
      accent: "#e11d48",
      heroBg: "linear-gradient(135deg,#e11d48,#be123c)",
      heading: "display",
    }),
    hero: { variant: "flash", eyebrow: "OFFRE FLASH – STOCK LIMITÉ", title: "-40% aujourd'hui seulement" },
    sections: ["trust", "features", "offers", "reviews", "countdown", "order", "faq"],
    options: { countdownMinutes: 240 },
  },
  {
    number: 7,
    id: "minimal-clean",
    name: "Minimal Clean",
    category: "Premium",
    demoProduct: "earbuds",
    lang: "fr",
    theme: L({
      primary: "#111318",
      accent: "#111318",
      surface: "#fafafa",
      surface2: "#f1f1f1",
      heading: "grotesk",
      headingWeight: 500,
      radius: 22,
    }),
    hero: {
      variant: "minimal",
      title: "Moins, mais mieux.",
      subtitle: "Un design épuré, une technologie pensée pour l'essentiel.",
    },
    sections: ["features", "showcase", "specs", "reviews", "order", "faq"],
  },
  {
    number: 8,
    id: "luxury-black",
    name: "Luxury Black",
    category: "Premium",
    demoProduct: "watch",
    lang: "fr",
    theme: D({
      bg: "#070707",
      surface: "#111",
      surface2: "#1a1a1a",
      border: "#2a2418",
      primary: "#d4af37",
      primaryText: "#0a0a0a",
      accent: "#e3c27a",
      heading: "serif",
      headingWeight: 400,
      uppercaseHeadings: true,
      radius: 4,
    }),
    hero: {
      variant: "luxury",
      eyebrow: "Maison horlogère",
      title: "L'excellence au quotidien",
      subtitle: "Mouvement automatique, verre saphir, finitions dorées.",
    },
    sections: ["features", "story", "specs", "reviews", "order", "guarantee", "faq"],
  },
  {
    number: 9,
    id: "beauty-glow",
    name: "Beauty Glow",
    category: "Beauté",
    demoProduct: "serum",
    lang: "fr",
    theme: L({
      primary: "#db2777",
      accent: "#db2777",
      surface: "#fdf2f8",
      surface2: "#fce7f3",
      heroBg: "linear-gradient(180deg,#fdf2f8,#fff)",
      heading: "serif",
      radius: 22,
    }),
    hero: {
      variant: "split",
      eyebrow: "✨ Testé dermatologiquement",
      title: "Une peau plus belle chaque jour",
      highlight: "plus belle",
    },
    sections: ["features", "before_after", "how", "reviews", "offers", "order", "faq"],
  },
  {
    number: 10,
    id: "health-trust",
    name: "Health Trust",
    category: "Beauté",
    demoProduct: "plant",
    lang: "fr",
    theme: L({ primary: "#0f9d76", accent: "#0f9d76", surface: "#f0fdf9", surface2: "#dcfcef", heading: "display" }),
    hero: {
      variant: "split",
      eyebrow: "👨‍⚕️ Recommandé par des experts",
      title: "Prenez soin de vous, naturellement",
      highlight: "naturellement",
      badge: "Bio",
    },
    sections: ["trust", "features", "stats", "how", "reviews", "order", "guarantee", "faq"],
  },
  {
    number: 11,
    id: "auto-gear",
    name: "Auto Gear",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: L({
      primary: "#f97316",
      accent: "#f97316",
      surface: "#fff7ed",
      surface2: "#ffedd5",
      heading: "display",
      radius: 20,
    }),
    hero: {
      variant: "split",
      eyebrow: "🚗 Pour tous vos trajets",
      title: "La route devient plus simple",
      highlight: "plus simple",
    },
    sections: ["story", "features", "reviews", "offers", "order", "faq"],
  },
  {
    number: 12,
    id: "tech-gadget",
    name: "Tech Gadget",
    category: "Tech",
    demoProduct: "earbuds",
    lang: "fr",
    theme: D({
      bg: "#0a0b1e",
      surface: "#12143a",
      surface2: "#1a1d4f",
      border: "#272b66",
      primary: "#7c3aed",
      accent: "#f43f5e",
      heroBg: "radial-gradient(circle at 70% 30%,#3b1d8f,#0a0b1e 60%)",
      heading: "grotesk",
    }),
    hero: {
      variant: "split",
      eyebrow: "Nouvelle génération",
      title: "La technologie au service de vous",
      highlight: "au service de vous",
    },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "order", "faq"],
  },
  {
    number: 13,
    id: "before-after",
    name: "Before After",
    category: "Beauté",
    demoProduct: "serum",
    lang: "fr",
    theme: L({ primary: "#16a34a", accent: "#e11d48", surface: "#f7fee7", surface2: "#ecfccb", heading: "display" }),
    hero: {
      variant: "beforeAfter",
      title: "Des résultats visibles",
      highlight: "visibles",
      subtitle: "94% des clientes constatent une peau plus hydratée en 14 jours.",
    },
    sections: ["stats", "before_after", "features", "reviews", "order", "faq"],
  },
  {
    number: 14,
    id: "story-selling",
    name: "Story Selling",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#0284c7", accent: "#ea580c", surface: "#f0f9ff", surface2: "#e0f2fe", heading: "display" }),
    hero: {
      variant: "fullbleed",
      title: "Une vraie histoire de transformation",
      subtitle: "De la galère au confort : découvrez comment nos clients ont changé leurs trajets.",
    },
    sections: ["story", "features", "showcase", "reviews", "order", "faq"],
  },
  {
    number: 15,
    id: "video-first",
    name: "Video First",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: D({ primary: "#f97316", accent: "#f97316", heroBg: "linear-gradient(180deg,#14161b,#0b0c0f)" }),
    hero: {
      variant: "video",
      title: "Découvrez en vidéo",
      highlight: "en vidéo",
      subtitle: "30 secondes pour comprendre pourquoi +12 000 conducteurs l'ont adopté.",
    },
    sections: ["features", "ugc", "reviews", "offers", "order", "faq"],
  },
  {
    number: 16,
    id: "image-first",
    name: "Image First",
    category: "Tech",
    demoProduct: "headphones",
    lang: "fr",
    theme: D({
      bg: "#08090c",
      primary: "#2563eb",
      accent: "#60a5fa",
      heroBg: "radial-gradient(circle at 50% 35%,#1e293b,#08090c 65%)",
    }),
    hero: { variant: "fullbleed", title: "Un son exceptionnel" },
    sections: ["features", "showcase", "specs", "reviews", "order", "faq"],
  },
  {
    number: 17,
    id: "benefit-cards",
    name: "Benefit Cards",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#1d4ed8", accent: "#dc2626", surface: "#eff6ff", surface2: "#dbeafe", heading: "display" }),
    hero: { variant: "centered", title: "Pourquoi choisir notre produit ?", highlight: "notre produit" },
    sections: ["benefits", "features", "reviews", "order", "faq"],
  },
  {
    number: 18,
    id: "feature-showcase",
    name: "Feature Showcase",
    category: "Tech",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#0ea5e9", accent: "#0284c7", surface: "#f0f9ff", surface2: "#e0f2fe", heading: "grotesk" }),
    hero: { variant: "split", title: "Des fonctionnalités qui font la différence", highlight: "la différence" },
    sections: ["features", "benefits", "specs", "comparison", "reviews", "order", "faq"],
  },
  {
    number: 19,
    id: "social-proof",
    name: "Social Proof",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#2563eb", accent: "#f59e0b", heading: "display" }),
    hero: {
      variant: "centered",
      eyebrow: "⭐ 4.9/5 – 1 248 avis",
      title: "Ils nous font confiance",
      highlight: "confiance",
    },
    sections: ["stats", "reviews", "ugc", "features", "order", "faq"],
  },
  {
    number: 20,
    id: "influencer-pick",
    name: "Influencer Pick",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: L({
      primary: "#e11d48",
      accent: "#e11d48",
      surface: "#fff1f2",
      surface2: "#ffe4e6",
      heroBg: "linear-gradient(180deg,#fff1f2,#fff)",
      heading: "display",
      radius: 20,
    }),
    hero: { variant: "ugc", eyebrow: "Coup de cœur influenceur 💖", title: "Mon coup de cœur !" },
    sections: ["ugc", "features", "reviews", "offers", "order", "faq"],
  },
  {
    number: 21,
    id: "one-screen-cod",
    name: "One Screen COD",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#dc2626", accent: "#dc2626", surface: "#f8fafc", surface2: "#eef2f7", heading: "display" }),
    hero: { variant: "oneScreen", title: "Tout ce dont vous avez besoin !" },
    sections: ["order", "reviews", "faq"],
    options: { orderMode: "both" },
  },
  {
    number: 22,
    id: "long-sales",
    name: "Long Sales Page",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#2563eb", accent: "#16a34a", heading: "display" }),
    hero: { variant: "split", title: "Une performance que vous méritez", highlight: "méritez" },
    sections: [
      "trust",
      "problem",
      "story",
      "features",
      "benefits",
      "showcase",
      "stats",
      "comparison",
      "reviews",
      "how",
      "offers",
      "order",
      "guarantee",
      "faq",
      "final_cta",
    ],
  },
  {
    number: 23,
    id: "comparison-pro",
    name: "Comparison Pro",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#16a34a", accent: "#16a34a", surface: "#f0fdf4", surface2: "#dcfce7", heading: "display" }),
    hero: { variant: "split", title: "Notre produit vs les autres", highlight: "vs les autres" },
    sections: ["comparison", "features", "specs", "reviews", "order", "faq"],
  },
  {
    number: 24,
    id: "bundle-offer",
    name: "Bundle Offer",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: L({ primary: "#e11d48", accent: "#e11d48", surface: "#fff1f2", surface2: "#ffe4e6", heading: "display" }),
    hero: { variant: "split", title: "Plus vous achetez, plus vous économisez !", highlight: "économisez !" },
    sections: ["offers", "features", "reviews", "countdown", "order", "faq"],
  },
  {
    number: 25,
    id: "fashion-editorial",
    name: "Fashion Editorial",
    category: "Mode",
    demoProduct: "abaya",
    lang: "fr",
    theme: L({
      bg: "#faf6f2",
      surface: "#f3ebe3",
      surface2: "#ebe0d4",
      border: "#e2d4c6",
      primary: "#7a3b5c",
      accent: "#7a3b5c",
      heading: "serif",
      headingWeight: 400,
      radius: 4,
    }),
    hero: { variant: "editorial", eyebrow: "Nouvelle collection", title: "Élégance Modeste" },
    sections: ["variants", "showcase", "features", "reviews", "order", "faq"],
  },
  {
    number: 26,
    id: "home-solution",
    name: "Home Solution",
    category: "Maison",
    demoProduct: "bottle",
    lang: "fr",
    theme: L({ primary: "#0891b2", accent: "#16a34a", surface: "#ecfeff", surface2: "#cffafe", heading: "display" }),
    hero: { variant: "split", title: "Une maison plus propre, plus facilement", highlight: "plus facilement" },
    sections: ["features", "how", "showcase", "reviews", "order", "faq"],
  },
  {
    number: 27,
    id: "arabic-cod",
    name: "Arabic COD",
    category: "Arabe",
    demoProduct: "holder",
    lang: "ar",
    theme: L({
      primary: "#ea580c",
      accent: "#dc2626",
      surface: "#fff7ed",
      surface2: "#ffedd5",
      font: "arabic",
      heading: "arabic",
    }),
    hero: { variant: "split", title: "منتوج عالي الجودة بثمن مناسب", highlight: "عالي الجودة" },
    sections: ["trust", "features", "showcase", "reviews", "order", "faq"],
  },
  {
    number: 28,
    id: "darija-morocco",
    name: "Darija Morocco",
    category: "Arabe",
    demoProduct: "holder",
    lang: "ar",
    theme: L({
      primary: "#dc2626",
      accent: "#dc2626",
      surface: "#fef2f2",
      surface2: "#fee2e2",
      font: "arabic",
      heading: "arabic",
    }),
    hero: { variant: "split", eyebrow: "🇲🇦 التوصيل لجميع المدن", title: "أحسن جودة بأحسن ثمن", highlight: "أحسن ثمن" },
    sections: ["trust", "features", "how", "reviews", "offers", "order", "faq"],
  },
  {
    number: 29,
    id: "whatsapp-commerce",
    name: "WhatsApp Commerce",
    category: "COD",
    demoProduct: "bottle",
    lang: "fr",
    theme: L({ primary: "#16a34a", accent: "#16a34a", surface: "#f0fdf4", surface2: "#dcfce7", heading: "display" }),
    hero: { variant: "whatsapp", title: "Commandez facilement via WhatsApp", highlight: "via WhatsApp" },
    sections: ["features", "how", "reviews", "whatsapp", "order", "faq"],
    options: { orderMode: "whatsapp" },
  },
  {
    number: 30,
    id: "conversion-max",
    name: "Conversion Max",
    category: "Conversion",
    demoProduct: "holder",
    lang: "fr",
    theme: D({ primary: "#ef4444", accent: "#ef4444", heroBg: "linear-gradient(180deg,#1a0a0a,#0b0c0f)" }),
    hero: { variant: "flash", eyebrow: "OFFRE SPÉCIALE", title: "Offre spéciale aujourd'hui !" },
    sections: ["trust", "features", "offers", "reviews", "countdown", "order", "faq"],
    options: { countdownMinutes: 120 },
  },

  // ════════════════ 31 → 60 : thématiques & international ════════════════
  {
    number: 31,
    id: "pro-device-launch",
    name: "Pro Device Launch",
    category: "Tech",
    demoProduct: "smartphone",
    lang: "fr",
    theme: L({
      primary: "#0071e3",
      accent: "#111318",
      surface: "#f5f5f7",
      surface2: "#ebebef",
      heading: "grotesk",
      headingWeight: 700,
      radius: 22,
    }),
    hero: {
      variant: "centered",
      title: "L'innovation dans vos mains",
      subtitle: "Écran 120Hz, caméra 50 MP et deux jours d'autonomie.",
    },
    sections: ["features", "showcase", "specs", "reviews", "order", "faq"],
  },
  {
    number: 32,
    id: "flagship-launch",
    name: "Flagship Launch",
    category: "Tech",
    demoProduct: "smartphone",
    lang: "fr",
    theme: D({
      bg: "#060818",
      surface: "#0e1230",
      surface2: "#151a44",
      border: "#232a63",
      primary: "#4f46e5",
      accent: "#a78bfa",
      heroBg: "radial-gradient(circle at 75% 40%,#4c1d95,#060818 60%)",
      heading: "grotesk",
    }),
    hero: {
      variant: "split",
      eyebrow: "Lancement officiel",
      title: "La nouvelle génération technologique",
      highlight: "nouvelle génération",
    },
    sections: ["features", "showcase", "variants", "specs", "reviews", "offers", "order", "faq"],
  },
  {
    number: 33,
    id: "premium-appliance",
    name: "Premium Appliance",
    category: "Premium",
    demoProduct: "dryer",
    lang: "fr",
    theme: L({
      primary: "#be185d",
      accent: "#be185d",
      surface: "#f7f7f8",
      surface2: "#efeff1",
      heading: "display",
      headingWeight: 700,
    }),
    hero: { variant: "split", title: "Puissant. Intelligent. Beau.", highlight: "Intelligent." },
    sections: ["features", "showcase", "specs", "comparison", "reviews", "order", "faq"],
  },
  {
    number: 34,
    id: "transparent-tech",
    name: "Transparent Tech",
    category: "Tech",
    demoProduct: "earbuds",
    lang: "fr",
    theme: L({
      bg: "#f4f4f2",
      surface: "#ebebe8",
      surface2: "#e2e2de",
      border: "#d6d6d1",
      primary: "#111111",
      accent: "#d71921",
      heading: "grotesk",
      headingWeight: 500,
      radius: 24,
    }),
    hero: { variant: "minimal", title: "Design pur. Vraie innovation." },
    sections: ["features", "showcase", "specs", "reviews", "order", "faq"],
  },
  {
    number: 35,
    id: "gaming-neon",
    name: "Gaming Neon",
    category: "Tech",
    demoProduct: "gamepad",
    lang: "fr",
    theme: D({
      bg: "#07041a",
      surface: "#100a2e",
      surface2: "#1a1145",
      border: "#2d1f6b",
      primary: "#ff2bd6",
      accent: "#22d3ee",
      heroBg: "radial-gradient(circle at 60% 40%,#4a0e8f,#07041a 65%)",
      heading: "tech",
      glow: true,
      uppercaseHeadings: true,
    }),
    hero: { variant: "neon", title: "Jouez sans limites", highlight: "sans limites" },
    sections: ["features", "showcase", "specs", "reviews", "offers", "order", "faq"],
  },
  {
    number: 36,
    id: "fashion-editorial-pro",
    name: "Fashion Editorial Pro",
    category: "Mode",
    demoProduct: "hoodie",
    lang: "fr",
    theme: L({
      bg: "#f7f3ee",
      surface: "#efe8df",
      surface2: "#e6ddd1",
      border: "#ddd2c4",
      primary: "#1c1917",
      accent: "#1c1917",
      heading: "elegant",
      headingWeight: 500,
      radius: 0,
      uppercaseHeadings: true,
    }),
    hero: { variant: "editorial", eyebrow: "Automne – Hiver", title: "Nouvelle collection" },
    sections: ["showcase", "variants", "features", "reviews", "order", "faq"],
  },
  {
    number: 37,
    id: "sport-drop",
    name: "Sport Drop",
    category: "Mode",
    demoProduct: "sneaker",
    lang: "fr",
    theme: L({
      primary: "#111111",
      accent: "#e11d48",
      surface: "#f5f5f5",
      surface2: "#ececec",
      heading: "condensed",
      headingWeight: 400,
      radius: 6,
      uppercaseHeadings: true,
    }),
    hero: { variant: "sport", title: "Repoussez vos limites" },
    sections: ["features", "showcase", "variants", "specs", "reviews", "order", "faq"],
  },
  {
    number: 38,
    id: "streetwear-drop",
    name: "Streetwear Drop",
    category: "Mode",
    demoProduct: "hoodie",
    lang: "fr",
    theme: D({
      bg: "#0a0a0a",
      surface: "#141414",
      surface2: "#1d1d1d",
      primary: "#e11d48",
      accent: "#e11d48",
      heading: "condensed",
      headingWeight: 400,
      radius: 4,
      uppercaseHeadings: true,
    }),
    hero: { variant: "sport", eyebrow: "🔥 Drop #07", title: "Édition limitée" },
    sections: ["countdown", "showcase", "variants", "features", "reviews", "order", "faq"],
    options: { countdownMinutes: 1440 },
  },
  {
    number: 39,
    id: "jewelry-atelier",
    name: "Jewelry Atelier",
    category: "Premium",
    demoProduct: "ring",
    lang: "fr",
    theme: L({
      bg: "#fbf6ef",
      surface: "#f5ece0",
      surface2: "#efe2d0",
      border: "#e8d8c2",
      primary: "#a2742c",
      accent: "#a2742c",
      heroBg: "linear-gradient(180deg,#f5e6cf,#fbf6ef)",
      heading: "elegant",
      headingWeight: 500,
      radius: 4,
    }),
    hero: {
      variant: "luxury",
      eyebrow: "Atelier joaillier",
      title: "Élégance intemporelle",
      subtitle: "Argent 925 plaqué or 18 carats, façonné à la main.",
    },
    sections: ["features", "showcase", "story", "reviews", "order", "faq"],
  },
  {
    number: 40,
    id: "luxury-fragrance",
    name: "Luxury Fragrance",
    category: "Premium",
    demoProduct: "perfume",
    lang: "fr",
    theme: D({
      bg: "#0b0806",
      surface: "#15100b",
      surface2: "#1f1810",
      border: "#33281a",
      primary: "#c9a45a",
      primaryText: "#140f08",
      accent: "#e3c27a",
      heroBg: "radial-gradient(circle at 50% 50%,#3b2a14,#0b0806 65%)",
      heading: "elegant",
      headingWeight: 500,
      uppercaseHeadings: true,
      radius: 2,
    }),
    hero: {
      variant: "luxury",
      eyebrow: "Eau de parfum",
      title: "Un parfum qui raconte votre histoire",
      subtitle: "Oud, ambre et vanille. Une signature qui reste.",
    },
    sections: ["story", "features", "showcase", "reviews", "offers", "order", "faq"],
  },
  {
    number: 41,
    id: "skincare-clinical",
    name: "Skincare Clinical",
    category: "Beauté",
    demoProduct: "serum",
    lang: "fr",
    theme: L({ primary: "#0d9488", accent: "#0d9488", surface: "#f0fdfa", surface2: "#ccfbf1", heading: "display" }),
    hero: {
      variant: "split",
      eyebrow: "🧪 Prouvé cliniquement",
      title: "Des résultats réels pour une peau plus saine",
      highlight: "résultats réels",
    },
    sections: ["stats", "before_after", "features", "how", "reviews", "order", "faq"],
  },
  {
    number: 42,
    id: "beauty-routine",
    name: "Beauty Routine",
    category: "Beauté",
    demoProduct: "serum",
    lang: "fr",
    theme: L({
      bg: "#fff7f8",
      surface: "#ffe9ee",
      surface2: "#ffdbe3",
      border: "#fbd0da",
      primary: "#e85d84",
      accent: "#e85d84",
      heroBg: "linear-gradient(135deg,#ffd6e0,#fff7f8)",
      heading: "serif",
      radius: 22,
    }),
    hero: { variant: "split", title: "Votre routine beauté quotidienne", highlight: "routine beauté" },
    sections: ["how", "features", "showcase", "reviews", "offers", "order", "faq"],
  },
  {
    number: 43,
    id: "hair-transformation",
    name: "Hair Transformation",
    category: "Beauté",
    demoProduct: "shampoo",
    lang: "fr",
    theme: L({
      bg: "#fffaf5",
      surface: "#faefe4",
      surface2: "#f3e2d1",
      border: "#ecd8c3",
      primary: "#9a5b2e",
      accent: "#9a5b2e",
      heading: "serif",
    }),
    hero: { variant: "beforeAfter", title: "Transformez vos cheveux", highlight: "vos cheveux" },
    sections: ["problem", "before_after", "features", "reviews", "offers", "order", "faq"],
  },
  {
    number: 44,
    id: "wellness-expert",
    name: "Wellness Expert",
    category: "Beauté",
    demoProduct: "plant",
    lang: "fr",
    theme: L({
      bg: "#f7faf5",
      surface: "#eef5ea",
      surface2: "#e1eedb",
      border: "#d4e5cc",
      primary: "#4d7c3a",
      accent: "#4d7c3a",
      heroBg: "linear-gradient(180deg,#e1eedb,#f7faf5)",
      heading: "display",
    }),
    hero: { variant: "fullbleed", title: "Un corps en forme, un esprit heureux" },
    sections: ["features", "stats", "how", "reviews", "offers", "order", "faq"],
  },
  {
    number: 45,
    id: "natural-organic",
    name: "Natural Organic",
    category: "Beauté",
    demoProduct: "plant",
    lang: "fr",
    theme: L({
      bg: "#fbfdf7",
      surface: "#f1f7e8",
      surface2: "#e4efd3",
      border: "#d7e6c1",
      primary: "#3f7d20",
      accent: "#e8a33d",
      heading: "serif",
    }),
    hero: { variant: "split", eyebrow: "🌿 100% naturel", title: "Pur. Naturel. Efficace.", highlight: "Naturel." },
    sections: ["features", "story", "comparison", "reviews", "order", "faq"],
  },
  {
    number: 46,
    id: "kitchen-demo",
    name: "Kitchen Demo",
    category: "Maison",
    demoProduct: "airfryer",
    lang: "fr",
    theme: L({
      bg: "#fffaf3",
      surface: "#fdf0df",
      surface2: "#fbe3c5",
      border: "#f3d9b6",
      primary: "#ea580c",
      accent: "#ea580c",
      heading: "display",
    }),
    hero: { variant: "split", title: "Cuisinez mieux, chaque jour", highlight: "chaque jour" },
    sections: ["video", "stats", "features", "showcase", "reviews", "offers", "order", "faq"],
  },
  {
    number: 47,
    id: "home-makeover",
    name: "Home Makeover",
    category: "Maison",
    demoProduct: "chair",
    lang: "fr",
    theme: L({
      bg: "#faf7f2",
      surface: "#f2ece2",
      surface2: "#e9e0d2",
      border: "#e0d5c3",
      primary: "#8b5e34",
      accent: "#8b5e34",
      heading: "serif",
    }),
    hero: { variant: "fullbleed", title: "Transformez votre maison en foyer" },
    sections: ["showcase", "variants", "features", "reviews", "order", "faq"],
  },
  {
    number: 48,
    id: "smart-home",
    name: "Smart Home",
    category: "Maison",
    demoProduct: "speaker",
    lang: "fr",
    theme: L({
      primary: "#2563eb",
      accent: "#0ea5e9",
      surface: "#f1f6ff",
      surface2: "#e2ecff",
      heroBg: "linear-gradient(180deg,#e8f0ff,#fff)",
      heading: "grotesk",
    }),
    hero: {
      variant: "split",
      title: "Une maison plus intelligente pour une vie meilleure",
      highlight: "plus intelligente",
    },
    sections: ["features", "how", "specs", "reviews", "offers", "order", "faq"],
  },
  {
    number: 49,
    id: "cleaning-solution",
    name: "Cleaning Solution",
    category: "Maison",
    demoProduct: "spray",
    lang: "fr",
    theme: L({
      primary: "#0284c7",
      accent: "#16a34a",
      surface: "#f0f9ff",
      surface2: "#e0f2fe",
      heroBg: "linear-gradient(135deg,#e0f2fe,#ecfdf5)",
      heading: "display",
    }),
    hero: { variant: "split", title: "Un nettoyage puissant, en toute simplicité", highlight: "puissant" },
    sections: ["problem", "before_after", "features", "reviews", "offers", "order", "faq"],
  },
  {
    number: 50,
    id: "furniture-studio",
    name: "Furniture Studio",
    category: "Maison",
    demoProduct: "chair",
    lang: "fr",
    theme: L({
      bg: "#fbf8f4",
      surface: "#f4eee6",
      surface2: "#ebe2d6",
      border: "#e3d8ca",
      primary: "#1f2937",
      accent: "#b07a4b",
      heading: "serif",
      headingWeight: 600,
      radius: 8,
    }),
    hero: { variant: "split", title: "Mobilier moderne pour une maison meilleure", highlight: "moderne" },
    sections: ["showcase", "variants", "features", "specs", "reviews", "order", "faq"],
  },
  {
    number: 51,
    id: "morocco-cod-pro",
    name: "Morocco COD Pro",
    category: "COD",
    demoProduct: "holder",
    lang: "fr",
    theme: L({
      primary: "#c1272d",
      accent: "#006233",
      surface: "#fdf6f0",
      surface2: "#f8e9dc",
      heroBg: "linear-gradient(180deg,#c1272d,#a01f24)",
      heading: "display",
    }),
    hero: { variant: "flash", eyebrow: "🇲🇦 PAIEMENT À LA LIVRAISON", title: "Livraison partout au Maroc" },
    sections: ["announcement", "trust", "features", "how", "reviews", "offers", "order", "faq"],
    options: { announcement: "🚚 Livraison gratuite dans toutes les villes du Maroc – Paiement à la livraison" },
  },
  {
    number: 52,
    id: "darija-viral",
    name: "Darija Viral",
    category: "Arabe",
    demoProduct: "serum",
    lang: "ar",
    theme: L({
      bg: "#fff7f9",
      surface: "#ffe9ef",
      surface2: "#ffd9e3",
      border: "#fbcfdb",
      primary: "#e11d74",
      accent: "#16a34a",
      font: "arabic",
      heading: "arabic",
      radius: 22,
    }),
    hero: { variant: "ugc", title: "منتوج رائع و فعال!", highlight: "فعال!" },
    sections: ["ugc", "features", "reviews", "offers", "order", "faq"],
  },
  {
    number: 53,
    id: "arabic-luxury-cod",
    name: "Arabic Luxury COD",
    category: "Arabe",
    demoProduct: "perfume",
    lang: "ar",
    theme: D({
      bg: "#0c0905",
      surface: "#17110a",
      surface2: "#21190e",
      border: "#3a2c18",
      primary: "#c9a45a",
      primaryText: "#140f08",
      accent: "#e3c27a",
      heroBg: "radial-gradient(circle at 50% 40%,#3b2a14,#0c0905 65%)",
      font: "arabic",
      heading: "arabic",
    }),
    hero: {
      variant: "luxury",
      title: "فخامة وجودة في كل تفصيلة",
      subtitle: "عطر شرقي بنوتات العود والعنبر، ثبات طويل.",
    },
    sections: ["features", "showcase", "reviews", "order", "faq"],
  },
  {
    number: 54,
    id: "whatsapp-direct-pro",
    name: "WhatsApp Direct Pro",
    category: "COD",
    demoProduct: "smartphone",
    lang: "fr",
    theme: L({
      primary: "#128c4a",
      accent: "#128c4a",
      surface: "#ecfdf3",
      surface2: "#d1fadf",
      heroBg: "linear-gradient(180deg,#d1fadf,#fff)",
      heading: "display",
    }),
    hero: { variant: "whatsapp", title: "Commandez via WhatsApp en 1 clic" },
    sections: ["whatsapp", "features", "reviews", "order", "faq"],
    options: { orderMode: "both" },
  },
  {
    number: 55,
    id: "viral-video-product",
    name: "Viral Video Product",
    category: "Conversion",
    demoProduct: "earbuds",
    lang: "fr",
    theme: D({
      bg: "#0a0a0f",
      surface: "#13131c",
      surface2: "#1c1c29",
      primary: "#fe2c55",
      accent: "#25f4ee",
      heading: "display",
    }),
    hero: { variant: "ugc", eyebrow: "🔥 +2M de vues", title: "Viral sur les réseaux", highlight: "Viral" },
    sections: ["ugc", "features", "stats", "reviews", "offers", "order", "faq"],
  },
  {
    number: 56,
    id: "social-ads-killer",
    name: "Social Ads Killer",
    category: "Conversion",
    demoProduct: "serum",
    lang: "fr",
    theme: L({
      primary: "#e11d48",
      accent: "#e11d48",
      surface: "#fff1f4",
      surface2: "#ffe4ea",
      heroBg: "linear-gradient(135deg,#ff4d7a,#e11d48)",
      heading: "display",
    }),
    hero: { variant: "flash", eyebrow: "OFFRE RÉSERVÉE AUX VISITEURS DU JOUR", title: "Offre spéciale aujourd'hui" },
    sections: ["features", "before_after", "reviews", "offers", "countdown", "order", "faq"],
    options: { countdownMinutes: 60 },
  },
  {
    number: 57,
    id: "single-product-store",
    name: "Single Product Store",
    category: "Premium",
    demoProduct: "speaker",
    lang: "fr",
    theme: L({
      primary: "#111318",
      accent: "#111318",
      surface: "#f7f7f7",
      surface2: "#efefef",
      heading: "grotesk",
      headingWeight: 600,
      radius: 20,
    }),
    hero: { variant: "split", title: "Le produit qui change votre quotidien" },
    sections: ["features", "showcase", "story", "specs", "reviews", "order", "faq"],
  },
  {
    number: 58,
    id: "multi-variant-product",
    name: "Multi-Variant Product",
    category: "Mode",
    demoProduct: "watch",
    lang: "fr",
    theme: L({ primary: "#1e3a8a", accent: "#1e3a8a", surface: "#f5f7fb", surface2: "#e9eef7", heading: "display" }),
    hero: { variant: "marketplace", title: "Choisissez votre style" },
    sections: ["variants", "features", "showcase", "specs", "reviews", "order", "faq"],
  },
  {
    number: 59,
    id: "high-ticket-sales",
    name: "High Ticket Sales",
    category: "Premium",
    demoProduct: "watch",
    lang: "fr",
    theme: D({
      bg: "#0a0908",
      surface: "#141210",
      surface2: "#1d1a16",
      border: "#33291b",
      primary: "#c9a45a",
      primaryText: "#140f08",
      accent: "#e3c27a",
      heading: "serif",
      headingWeight: 600,
    }),
    hero: {
      variant: "split",
      eyebrow: "Édition numérotée",
      title: "Un investissement pour votre avenir",
      highlight: "votre avenir",
    },
    sections: ["story", "features", "specs", "comparison", "reviews", "guarantee", "order", "faq"],
  },
  {
    number: 60,
    id: "conversion-engine",
    name: "Conversion Engine",
    category: "Conversion",
    demoProduct: "shampoo",
    lang: "fr",
    theme: L({
      primary: "#ef4444",
      accent: "#ef4444",
      surface: "#fff5f5",
      surface2: "#ffe4e4",
      heroBg: "linear-gradient(135deg,#ef4444,#f97316)",
      heading: "display",
    }),
    hero: { variant: "flash", eyebrow: "DERNIÈRES PIÈCES", title: "Offre limitée !" },
    sections: [
      "announcement",
      "trust",
      "problem",
      "features",
      "offers",
      "reviews",
      "countdown",
      "order",
      "guarantee",
      "faq",
    ],
    options: { countdownMinutes: 90, announcement: "⚡ -35% aujourd'hui seulement · Livraison gratuite" },
  },
];

/** Anciens identifiants → nouveaux (pages déjà publiées). */
export const TEMPLATE_ALIASES: Record<string, string> = {
  "apple-product": "pro-device-launch",
  "samsung-launch": "flagship-launch",
  "dyson-premium": "premium-appliance",
  "nothing-tech": "transparent-tech",
};

export const SECTION_LABELS: Record<SectionKey, string> = {
  hero: "Hero",
  order: "Formulaire COD",
  benefits: "Bénéfices",
  problem: "Problème / Solution",
  features: "Caractéristiques",
  how: "Comment ça marche",
  trust: "Confiance",
  faq: "FAQ",
  announcement: "Barre d'annonce",
  showcase: "Galerie produit",
  story: "Histoire / Présentation",
  before_after: "Avant / Après",
  stats: "Chiffres clés",
  ugc: "Vidéos créateurs (UGC)",
  reviews: "Avis clients",
  comparison: "Comparatif",
  specs: "Fiche technique",
  variants: "Variantes / Couleurs",
  offers: "Offres groupées",
  countdown: "Compte à rebours",
  video: "Vidéo produit",
  whatsapp: "Bloc WhatsApp",
  guarantee: "Garantie",
  final_cta: "Appel à l'action final",
};

const heroLabel: Record<string, string> = {
  split: "Hero image + texte",
  centered: "Hero centré",
  fullbleed: "Hero plein écran",
  luxury: "Hero luxe",
  ugc: "Hero créateur UGC",
  problem: "Hero problème",
  flash: "Hero promo flash",
  video: "Hero vidéo",
  beforeAfter: "Hero avant/après",
  whatsapp: "Hero WhatsApp",
  editorial: "Hero éditorial",
  neon: "Hero néon",
  sport: "Hero sport",
  marketplace: "Fiche marketplace",
  minimal: "Hero minimal",
  oneScreen: "Tout sur un écran",
};

export const TEMPLATES: TemplateDef[] = raw.map((t) => {
  const sections = (t.sections.includes("order") ? t.sections : [...t.sections, "order"]) as SectionKey[];
  const highlights = sections
    .filter((s) => !["order", "faq", "trust", "announcement"].includes(s))
    .slice(0, 3)
    .map((s) => SECTION_LABELS[s].toLowerCase());
  return { ...t, sections, description: `${heroLabel[t.hero.variant]} · ${highlights.join(", ")} · formulaire COD.` };
});

export function resolveTemplateId(id: string): string {
  const k = String(id || "").trim();
  return TEMPLATE_ALIASES[k] || k;
}

export function getTemplate(id: string): TemplateDef {
  const k = resolveTemplateId(id);
  return TEMPLATES.find((t) => t.id === k) || TEMPLATES[0];
}

/** Ordre par défaut stocké dans content.section_order à la création. */
export const defaultSectionOrder = (t: TemplateDef): string[] => ["hero", ...t.sections];
