"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

const DEMOS=[
["Running Pro","Sneakers","Performance"],["Casa Essentials","Maison","Nouveautés"],["Marrakech Style","Mode","Collection"],["Pure Minimal","Lifestyle","Essentiels"],["Night Gear","Tech","Premium"],
["Noor Collection","Abaya","Modeste"],["Medina Edit","Fashion","Tendance"],["Maison Luxe","Premium","Signature"],["Golden Shine","Bijoux","Best sellers"],["Chrono","Montres","Collection"],
["Vision","Lunettes","Nouveaux"],["Urban Bags","Sacs","Collection"],["Glow","Beauté","Routine"],["Privé","Parfum","Signature"],["Petit Monde","Bébé","Douceur"],
["Street Run","Sneakers","Performance"],["Fit Lab","Fitness","Énergie"],["Sport Club","Sport","Performance"],["Natural Care","Bien-être","Naturel"],["Casa Living","Maison","Inspiration"],
["Chef Store","Cuisine","Essentiels"],["Next Tech","Tech","Innovation"],["Smart Life","Gadgets","Top ventes"],["Drive Pro","Auto","Équipement"],["Ride X","Moto","Road"],
["Hero Product","Best seller","Offre"],["Hot Deals","Promos","Flash"],["Trend Shop","Social","Viral"],["Noir Edition","Premium","Exclusive"],["Mega Store","Multi-catégories","Top ventes"]
];
const TEMPLATES=[
["Atlas COD","COD Maroc","🛍️"],["Casa Market","Général","🏪"],["Marrakech Shop","Général","🌴"],["Rabat Minimal","Minimal","◻️"],["Sahara Dark","Dark","🌙"],
["Noor Abaya","Mode","🧕"],["Medina Fashion","Mode","👗"],["Luxe Maroc","Luxe","✦"],["Bijoux Gold","Bijoux","💎"],["Time Store","Montres","⌚"],
["Vision Optic","Lunettes","🕶️"],["Bag House","Sacs","👜"],["Beauty Glow","Beauté","✨"],["Parfum Privé","Parfums","🌸"],["Baby Care","Bébé","🧸"],
["Sneaker Hub","Chaussures","👟"],["Fit Market","Fitness","🏋️"],["Sport Pro","Sport","⚽"],["Wellness Care","Bien-être","🌿"],["Home Living","Maison","🏠"],
["Kitchen Plus","Cuisine","🍳"],["Tech Zone","Électronique","💻"],["Gadget Lab","Gadgets","⚡"],["Auto Gear","Automobile","🚗"],["Moto Ride","Moto","🏍️"],
["One Product","One product","🎯"],["Flash Deals","Promotions","🔥"],["Social Shop","Social","♥"],["Premium Black","Premium","◆"],["Marketplace","Multi-produit","▦"]
].map((x,i)=>({id:"free-"+String(i+1).padStart(2,"0"),name:x[0],category:x[1],icon:x[2],demo:DEMOS[i]}));

type Store={id:string;name:string;templateId:string;language:string;createdAt:string;slug?:string;status?:string};
export default function Stores(){
 const [stores,setStores]=useState<Store[]>([]),[selected,setSelected]=useState(TEMPLATES[0].id),[name,setName]=useState(""),[language,setLanguage]=useState("darija"),[filter,setFilter]=useState("Tous");
 useEffect(()=>{fetch("/api/stores",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"Stores indisponibles");setStores((x.stores||[]).map((v:any)=>({id:v.id,name:v.name,templateId:v.template_id,language:v.locale,createdAt:v.created_at,slug:v.slug,status:v.status}))) }).catch(e=>console.error(e))},[]);
 const cats=["Tous",...Array.from(new Set(TEMPLATES.map(t=>t.category)))];
 const visible=useMemo(()=>filter==="Tous"?TEMPLATES:TEMPLATES.filter(t=>t.category===filter),[filter]);
 async function createStore(){const n=name.trim();if(!n)return alert("Entre le nom de la boutique.");const r=await fetch("/api/stores",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:n,templateId:selected,locale:language})}),x=await r.json();if(!r.ok)return alert(x.error||"Erreur lors de la création");const v=x.store;setStores(cur=>[{id:v.id,name:v.name,templateId:v.template_id,language:v.locale,createdAt:v.created_at,slug:v.slug,status:v.status},...cur]);setName("");alert("Boutique créée en brouillon et enregistrée dans ton espace LandPro.");}
 const current=TEMPLATES.find(t=>t.id===selected)!;
 return <main className="dash-shell"><aside className="dash-side"><div className="dash-brand"><div className="brand-mark">M</div><div><b>Landing Motor</b><small>AI COD BUILDER</small></div></div><nav className="dash-nav"><Link href="/">⌂ Dashboard</Link><Link href="/pages">▣ Landing Pages</Link><Link className="active" href="/stores">▦ Stores</Link><Link href="/orders">◎ Commandes</Link><Link href="/delivery">🚚 Livraison</Link><Link href="/products">◇ Mes produits</Link><Link href="/domains">⌁ Domaines</Link><Link href="/analytics">↗ Analytics</Link><Link href="/settings">⚙ Paramètres</Link></nav></aside>
 <section className="dash-content stores-dashboard"><header className="dash-header"><div><span className="eyebrow">STORE BUILDER</span><h1>Générateur de boutiques</h1><p>Crée une boutique COD Maroc à partir de 30 templates gratuits.</p></div><span className="stores-free-badge">30 TEMPLATES GRATUITS</span></header>
 {stores.length>0&&<section className="stores-existing"><div className="stores-section-head"><div><small>MES STORES</small><h2>Boutiques en brouillon</h2></div><b>{stores.length}</b></div><div className="stores-drafts">{stores.slice(0,4).map(s=>{const t=TEMPLATES.find(x=>x.id===s.templateId);return <article key={s.id}><span>{t?.icon}</span><div><b>{s.name}</b><small>{t?.name} · {s.language}</small></div><em>{s.status==="PUBLISHED"?"PUBLIÉ":"BROUILLON"}</em><Link className="store-edit-link" href={"/stores/"+s.id}>Modifier →</Link></article>})}</div></section>}
 <section className="store-create-panel"><div className="store-create-copy"><small>ÉTAPE 1</small><h2>Configure ta boutique</h2><p>Choisis un template puis renseigne les informations de base.</p><label>Nom de la boutique<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Motorix Store"/></label><label>Langue<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="darija">Darija Maroc</option><option value="ar">العربية</option><option value="fr">Français</option></select></label><div className="store-selected"><span>{current.icon}</span><div><small>TEMPLATE SÉLECTIONNÉ</small><b>{current.name}</b></div></div><button type="button" className="new-page-btn" onClick={createStore}>Créer la boutique →</button></div>
 <div className="store-preview"><div className="store-browser"><i/><i/><i/><span>{name||current.demo[0]}</span></div><div className={"store-pro-demo demo-"+selected}><div className="demo-ann">🚚 Livraison partout au Maroc · Paiement à la livraison</div><header><b>{name||current.demo[0]}</b><nav>Accueil&nbsp;&nbsp; Boutique&nbsp;&nbsp; Nouveautés&nbsp;&nbsp; Contact</nav><span>Panier (0)</span></header><section className="demo-hero"><div><small>{current.demo[2]}</small><h3>{current.name}</h3><p>Découvrez notre sélection pensée pour votre quotidien.</p><button>Découvrir la collection</button></div><div className="demo-hero-art"><span>{current.icon}</span></div></section><div className="demo-cats"><span>{current.demo[1]}</span><span>Best sellers</span><span>Nouveautés</span></div><section className="demo-products"><div className="demo-title"><div><small>SHOP</small><h4>Produits populaires</h4></div><b>Voir tout →</b></div><div className="demo-product-grid">{[1,2,3,4].map((n)=><article key={n}><div className={"demo-product-photo photo-"+n}><span>{current.icon}</span>{n===1&&<em>-20%</em>}</div><small>{current.demo[1]}</small><strong>{["Collection Essential","Premium Edition","Daily Choice","Best Seller"][n-1]}</strong><div><b>{149+n*50} DH</b>{n===1&&<s>299 DH</s>}</div><button>Ajouter au panier</button></article>)}</div></section><div className="demo-benefits"><span>🚚<b>Livraison Maroc</b><small>Rapide & suivie</small></span><span>💵<b>Paiement COD</b><small>À la livraison</small></span><span>✓<b>Qualité</b><small>Produits sélectionnés</small></span></div><footer><b>{name||current.demo[0]}</b><small>Boutique · Livraison · Contact · FAQ</small></footer></div></div></section>
 <div className="stores-section-head"><div><small>BIBLIOTHÈQUE</small><h2>30 templates gratuits</h2></div><span>Sélectionne un design pour voir l’aperçu.</span></div><div className="store-filters">{cats.map(c=><button key={c} className={filter===c?"active":""} onClick={()=>setFilter(c)}>{c}</button>)}</div>
 <div className="store-template-grid">{visible.map((t,i)=><button type="button" key={t.id} className={"store-template-card "+(selected===t.id?"selected":"")} onClick={()=>setSelected(t.id)}><div className={"store-template-thumb pro-thumb demo-"+t.id}><div className="thumb-top"><b>{t.demo[0]}</b><i/></div><div className="thumb-hero"><span>{t.icon}</span><small>{t.demo[2]}</small></div><div className="thumb-products"><i/><i/><i/></div></div><div className="store-template-meta"><span><b>{t.name}</b><small>{t.category}</small></span><em>GRATUIT</em></div></button>)}</div>
 </section></main>
}