"use client";
import type {ReactNode} from "react";

type Props={mode:string;content:any;data:any;images:string[];sectionStyle:any;imageAlt:(x:string,i:number)=>string;whatsapp?:string;onCta?:()=>void};
const CTA=({c,data,onCta}:{c:any;data:any;onCta?:()=>void})=><a className="lp-cta" href="#order" onClick={onCta}>{c.cta||"اطلب الآن"} — {data.price} DH</a>;
const Price=({data}:{data:any})=><div className="lp-price"><b>{data.price} DH</b>{data.oldPrice&&<s>{data.oldPrice} DH</s>}</div>;
const Copy=({c,data,onCta,extra}:{c:any;data:any;onCta?:()=>void;extra?:ReactNode})=><div className="lp-copy"><span className="lp-badge">الدفع عند الاستلام</span><small className="lp-category">{c.product_category}</small><h1>{c.headline||data.name}</h1><p className="lp-sub">{c.subheadline||c.description}</p><Price data={data}/><CTA c={c} data={data} onCta={onCta}/>{extra}</div>;
const Img=({src,alt,cls=""}:{src?:string;alt:string;cls?:string})=>src?<img className={"lp-hero-img "+cls} src={src} alt={alt} loading="eager" fetchPriority="high"/>:null;
export default function HeroRenderer({mode,c:never,content,data,images,sectionStyle,imageAlt,whatsapp,onCta}:Props&{c?:never}){
 const c=content||{},m=mode||"conversion",wa=whatsapp?<a className="lp-whatsapp" target="_blank" rel="noreferrer" href={"https://wa.me/"+whatsapp+"?text="+encodeURIComponent("سلام، بغيت معلومات على "+data.name)}>واتساب</a>:null;
 const shell=(body:ReactNode,cls="")=><section className={"lp-hero lp-hero-real lp-hero-real-"+m+" "+cls} style={sectionStyle("hero")} data-hero-module={m}>{body}</section>;
 if(m==="fullscreen")return shell(<><div className="hero-full-media"><Img src={images[0]} alt={imageAlt(images[0],0)}/></div><div className="lp-wrap hero-full-overlay"><Copy c={c} data={data} onCta={onCta} extra={wa}/></div></>);
 if(m==="center-product")return shell(<div className="lp-wrap hero-center"><Copy c={c} data={data} onCta={onCta}/><Img src={images[0]} alt={imageAlt(images[0],0)}/><div className="hero-proof"><span>✓ Livraison Maroc</span><span>✓ Paiement à la livraison</span><span>✓ Commande sécurisée</span></div></div>);
 if(m==="gallery-commerce")return shell(<div className="lp-wrap hero-commerce"><div className="hero-commerce-gallery"><Img src={images[0]} alt={imageAlt(images[0],0)}/><div>{images.slice(1,4).map((x,i)=><img key={x+i} src={x} alt={imageAlt(x,i+1)}/>)}</div></div><aside><Copy c={c} data={data} onCta={onCta} extra={<><div className="hero-mini-benefits">{(c.benefits||[]).slice(0,3).map((x:any,i:number)=><span key={i}>✓ {typeof x==="string"?x:x?.title}</span>)}</div>{wa}</>}/></aside></div>);
 if(m==="minimal")return shell(<div className="lp-wrap hero-minimal"><div><small>{c.product_category}</small><h1>{c.headline||data.name}</h1><p>{c.subheadline||c.description}</p><Price data={data}/><CTA c={c} data={data} onCta={onCta}/></div><Img src={images[0]} alt={imageAlt(images[0],0)}/></div>);
 if(m==="editorial")return shell(<div className="lp-wrap hero-editorial"><div className="hero-editorial-index">01</div><Img src={images[0]} alt={imageAlt(images[0],0)}/><div><small>{c.product_category}</small><h1>{c.headline||data.name}</h1><p className="lp-sub">{c.subheadline||c.description}</p><Price data={data}/><CTA c={c} data={data} onCta={onCta}/></div></div>);
 if(m==="form-integrated")return shell(<div className="lp-wrap hero-form"><Copy c={c} data={data} onCta={onCta}/><div className="hero-form-card"><b>Commande rapide</b><span>Nom complet</span><span>Téléphone</span><span>Ville</span><a href="#order">Continuer la commande →</a><small>Paiement à la livraison</small></div></div>);
 if(m==="background")return shell(<><div className="hero-bg"><Img src={images[0]} alt={imageAlt(images[0],0)}/></div><div className="lp-wrap hero-bg-copy"><Copy c={c} data={data} onCta={onCta} extra={wa}/></div></>);
 if(m==="luxury")return shell(<div className="lp-wrap hero-luxury"><div className="hero-luxury-media"><Img src={images[0]} alt={imageAlt(images[0],0)}/><span>COLLECTION</span></div><div><small>PREMIUM SELECTION</small><h1>{c.headline||data.name}</h1><p>{c.subheadline||c.description}</p><Price data={data}/><CTA c={c} data={data} onCta={onCta}/></div></div>);
 if(m==="lifestyle")return shell(<div className="lp-wrap hero-ugc"><div className="hero-ugc-media"><Img src={images[0]} alt={imageAlt(images[0],0)}/><span className="hero-ugc-chip">UGC · REAL USE</span></div><div><div className="hero-stars">★★★★★ <small>Clients satisfaits</small></div><h1>{c.headline||data.name}</h1><p>{c.subheadline||c.description}</p><div className="hero-testimonial">“Simple, pratique et exactement ce qu’il me fallait.”</div><Price data={data}/><CTA c={c} data={data} onCta={onCta}/></div></div>);
 if(m==="mobile-first")return shell(<div className="hero-phone"><Img src={images[0]} alt={imageAlt(images[0],0)}/><span className="lp-badge">الدفع عند الاستلام</span><h1>{c.headline||data.name}</h1><Price data={data}/><div className="hero-mobile-benefits">{(c.benefits||[]).slice(0,2).map((x:any,i:number)=><span key={i}>✓ {typeof x==="string"?x:x?.title}</span>)}</div><CTA c={c} data={data} onCta={onCta}/>{wa}</div>);
 if(m==="split-product")return shell(<div className="lp-wrap hero-split"><div><Copy c={c} data={data} onCta={onCta} extra={<div className="hero-proof"><span>🚚 Livraison</span><span>💵 COD</span></div>}/></div><div className="hero-product-stage"><Img src={images[0]} alt={imageAlt(images[0],0)}/>{images[1]&&<img className="hero-product-detail" src={images[1]} alt={imageAlt(images[1],1)}/>}</div></div>);
 return shell(<div className="lp-wrap hero-cod"><div><span className="hero-offer">OFFRE COD</span><h1>{c.headline||data.name}</h1><p>{c.subheadline||c.description}</p><div className="hero-cod-benefits">{(c.benefits||[]).slice(0,3).map((x:any,i:number)=><span key={i}>✓ {typeof x==="string"?x:x?.title}</span>)}</div></div><div className="hero-offer-card"><Img src={images[0]} alt={imageAlt(images[0],0)}/><Price data={data}/><CTA c={c} data={data} onCta={onCta}/><small>🚚 Livraison partout au Maroc · 💵 Paiement à la livraison</small>{wa}</div></div>,"hero-conversion");
}
