import {NextResponse} from "next/server";import {authContext} from "../../../lib/server-auth";
export async function GET(req:Request){try{
 const {s,workspaceId}=await authContext(req),url=new URL(req.url),days=Math.min(90,Math.max(1,Number(url.searchParams.get("days")||30))),fromParam=url.searchParams.get("from"),toParam=url.searchParams.get("to"),productId=url.searchParams.get("product_id"),from=fromParam?new Date(fromParam+"T00:00:00").toISOString():new Date(Date.now()-(days-1)*86400000).toISOString(),to=toParam?new Date(toParam+"T23:59:59.999").toISOString():null;
 const {data,error}=await s.rpc("analytics_dashboard_aggregate",{p_workspace_id:workspaceId,p_from:from});
 if(error)throw error;
 let result:any=data||{};if(to||productId){let allowed:string[]|null=null;if(productId){const {data:pages,error:pe}=await s.from("landing_pages").select("id").eq("workspace_id",workspaceId).eq("product_id",productId);if(pe)throw pe;allowed=(pages||[]).map((x:any)=>x.id)}result.landings=(Array.isArray(result.landings)?result.landings:[]).filter((r:any)=>!allowed||allowed.includes(r.landing_page_id));if(to){const end=new Date(to).getTime();result.landings=result.landings.filter((r:any)=>!r.last_event_at||new Date(r.last_event_at).getTime()<=end)}const sum=(k:string)=>result.landings.reduce((a:number,r:any)=>a+Number(r[k]||0),0);result.totals={views:sum("views"),visitors:sum("visitors"),formStarts:sum("form_starts"),orders:sum("orders"),confirmed:sum("confirmed"),shipped:sum("shipped"),delivered:sum("delivered"),returned:sum("returned"),revenue:sum("revenue"),deliveredRevenue:sum("delivered_revenue")}}const t:any=result.totals||{};
 const views=Number(t.views||0),orders=Number(t.orders||0),confirmed=Number(t.confirmed||0),shipped=Number(t.shipped||0),delivered=Number(t.delivered||0),returned=Number(t.returned||0);
 return NextResponse.json({days,totals:{...t,views,visitors:Number(t.visitors||0),formStarts:Number(t.formStarts||0),orders,confirmed,shipped,delivered,returned,revenue:Number(t.revenue||0),deliveredRevenue:Number(t.deliveredRevenue||0),conversion:views?orders/views*100:0,confirmationRate:orders?confirmed/orders*100:0,deliveryRate:shipped?delivered/shipped*100:0,returnRate:shipped?returned/shipped*100:0},landings:Array.isArray(result.landings)?result.landings:[]});
}catch(e:any){return NextResponse.json({error:e.message,landings:[]},{status:e.message==="Non autorisé"?401:500})}}
