"use client";import Link from "next/link";import {useEffect,useState} from "react";
const Icon=({children}:{children:string})=><span className="dash-icon">{children}</span>;
const money=(n:any)=>Number(n||0).toLocaleString("fr-MA",{maximumFractionDigits:0})+" DH";
const pct=(n:any)=>Number(n||0).toLocaleString("fr-MA",{maximumFractionDigits:1})+"%";
export default function Home(){
 const [data,setData]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/dashboard",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"Dashboard indisponible");setData(x)}).catch(e=>setError(e.message))},[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.href="/login"}
 const t=data?.totals||{},recent=data?.recentOrders||[],top=data?.topLandings||[];
 return <main className="dash-shell"><aside className="dash-side"><div className="dash-brand"><div className="brand-mark">M</div><div><b>Landing Motor</b><small>AI COD BUILDER</small></div></div><nav className="dash-nav"><Link className="active" href="/"><Icon>⌂</Icon>Dashboard</Link><Link href="/pages"><Icon>▣</Icon>Landing Pages</Link><Link href="/orders"><Icon>◎</Icon>Commandes</Link><Link href="/products"><Icon>◇</Icon>Produits</Link><Link href="/domains"><Icon>⌁</Icon>Domaines</Link><Link href="/analytics"><Icon>↗</Icon>Analytics</Link></nav><div className="dash-side-bottom"><Link href="/settings"><Icon>⚙</Icon>Settings</Link><div className="dash-plan"><small>PLAN ACTUEL</small><b>Motor Starter</b><span>Jusqu'à 50 pages</span></div></div></aside>
 <section className="dash-content home-dashboard"><header className="dash-header"><div><span className="eyebrow">LANDING PAGE MOTOR</span><h1>Dashboard</h1><p>Vue d'ensemble de ton activité COD sur les 30 derniers jours.</p></div><div className="dash-header-actions"><Link href="/pages" className="primary dashboard-new">+ Nouvelle landing</Link><button type="button" className="ghost-btn" onClick={logout}>Déconnexion</button><span className="avatar">M</span></div></header>
 {error&&<div className="dash-error dashboard-error">{error}</div>}
 {!data?<div className="dashboard-loading">Chargement du dashboard…</div>:<>
 <div className="dashboard-kpis"><article><small>CHIFFRE D'AFFAIRES</small><b>{money(t.revenue)}</b><span>Commandes · 30 jours</span></article><article><small>COMMANDES</small><b>{t.orders}</b><span>{t.newLeads} nouvelles à traiter</span></article><article><small>CONFIRMATION</small><b>{pct(t.confirmationRate)}</b><span>{t.confirmed} confirmées</span></article><article><small>LIVRAISON</small><b>{pct(t.deliveryRate)}</b><span>{money(t.deliveredRevenue)} livré</span></article><article><small>CONVERSION</small><b>{pct(t.conversion)}</b><span>{Number(t.views||0).toLocaleString("fr-MA")} vues</span></article></div>
 <div className="dashboard-main-grid"><section className="dashboard-card dashboard-recent"><div className="dashboard-card-head"><div><small>ACTIVITÉ</small><h2>Commandes récentes</h2></div><Link href="/orders">Voir toutes →</Link></div>{recent.length?<div className="dashboard-order-list">{recent.map((o:any)=><Link href="/orders" className="dashboard-order" key={o.id}><div><b>{o.lead?.full_name||"Client"}</b><small>{o.product?.name||"Produit"} · {o.lead?.city_name||"Ville non renseignée"}</small></div><div><b>{money(o.total)}</b><small>{o.lead?.status==="CONFIRMED"?"Confirmée":o.lead?.status==="NEW"?"Nouvelle":o.lead?.status||"—"} · {new Date(o.created_at).toLocaleDateString("fr-MA")}</small></div></Link>)}</div>:<p className="dashboard-empty">Aucune commande récente.</p>}</section>
 <section className="dashboard-card"><div className="dashboard-card-head"><div><small>LANDINGS</small><h2>Performance</h2></div><Link href="/analytics">Analytics →</Link></div><div className="dashboard-mini-stats"><div><b>{t.landings}</b><span>Landings</span></div><div><b>{t.published}</b><span>Publiées</span></div><div><b>{t.products}</b><span>Produits</span></div></div>{top.length?<div className="dashboard-top-list">{top.map((x:any,i:number)=><div key={x.id||x.landing_page_id||i}><span>{x.name||x.landing_name||"Landing"}</span><b>{Number(x.orders||0)} cmd.</b></div>)}</div>:<p className="dashboard-empty">Les performances apparaîtront ici avec les données Analytics.</p>}</section></div>
 <div className="dashboard-bottom-grid"><section className="dashboard-card"><div className="dashboard-card-head"><div><small>ACTIONS RAPIDES</small><h2>Continuer le travail</h2></div></div><div className="dashboard-actions"><Link href="/pages">+ Créer une landing</Link><Link href="/products">+ Ajouter un produit</Link><Link href="/orders">Gérer les commandes</Link><Link href="/analytics">Voir les analytics</Link></div></section><section className="dashboard-card dashboard-attention"><div className="dashboard-card-head"><div><small>À TRAITER</small><h2>Priorités</h2></div></div><Link href="/orders"><b>{t.newLeads}</b><span> nouvelles commandes / leads à traiter</span></Link><Link href="/pages"><b>{Math.max(0,Number(t.landings||0)-Number(t.published||0))}</b><span> landing(s) en brouillon</span></Link></section></div>
 </>}</section></main>
}