"use client";
import React from "react";
import type {LandingV4Data} from "./LandingTemplateV4";
import {landingTemplate} from "../lib/landing-template-presets";
type P={data:LandingV4Data;preview?:boolean;onSubmit?:(e:React.FormEvent<HTMLFormElement>,qty:number)=>void};
export default function LandingTemplates01to05({data,preview=false,onSubmit}:P){
 const c=data.content||{},t=landingTemplate(data.templateId),imgs=data.images||[],offers=Array.isArray(c.quantity_offers)&&c.quantity_offers.length?c.quantity_offers:[{qty:1,price:data.price,label:"1 pièce"},{qty:2,price:data.price*2,label:"2 pièces"},{qty:3,price:data.price*3,label:"3 pièces"}], [qty,setQty]=React.useState(Number(offers[0]?.qty||1));
 const pic=(i:number,cl="")=>imgs[i]?<img className={cl} src={imgs[i]} alt={data.name}/>:<div className={"v45-ph "+cl}><b>{data.name}</b></div>;
 const price=<div className="v45-price"><b>{data.price} DH</b>{data.oldPrice&&<del>{data.oldPrice} DH</del>}</div>;
 const form=(compact=false)=><div className={"v45-form "+(compact?"compact":"")} id="order"><h3>Commandez maintenant</h3><form onSubmit={e=>{if(preview){e.preventDefault();return}onSubmit?.(e,qty)}}><input name="name" required={!preview} placeholder="Nom complet"/><input name="phone" required={!preview} placeholder="Téléphone" inputMode="tel"/><input name="city" required={!preview} placeholder="Ville"/><input name="address" placeholder="Adresse"/><div className="v45-packs">{offers.slice(0,3).map((o:any)=><button type="button" className={qty===Number(o.qty)?"active":""} onClick={()=>setQty(Number(o.qty))} key={o.qty}>{o.qty} pièce{o.qty>1?"s":""}<b>{o.price} DH</b></button>)}</div><button className="v45-submit" type={preview?"button":"submit"}>Confirmer la commande</button></form><small>✓ Paiement à la livraison　✓ Livraison partout au Maroc</small></div>;
 const head=(minimal=false)=><><div className="v45-top">Livraison partout au Maroc · Paiement à la livraison</div><header className={minimal?"minimal":""}><b>{minimal?"LANDPRO SELECT":t.name}</b><nav>Accueil　Avantages　Avis　FAQ</nav><a href="#order">Commander</a></header></>;
 const benefits=<div className="v45-benefits">{["Livraison rapide","Paiement à la livraison","Produit contrôlé","Satisfait ou remboursé"].map((x,i)=><article key={i}><i>0{i+1}</i><b>{x}</b></article>)}</div>;
 const faq=<section className="v45-faq"><h2>Questions fréquentes</h2>{["Comment commander ?","Quand vais-je recevoir ma commande ?","Comment payer ?"].map((x,i)=><details key={x} open={i===0}><summary>{x}</summary><p>Notre équipe confirme votre commande avant l'expédition. Le paiement se fait à la livraison.</p></details>)}</section>;
 const foot=<footer className="v45-footer"><b>{data.name}</b><span>Livraison · Paiement COD · Support client</span></footer>;
 if(data.templateId==="cod-direct")return <main className="v45 v45-cod">{head()}<section className="v45-cod-hero"><div><span className="v45-kicker">N°1 AU MAROC</span><h1>{c.headline||data.name}</h1><p>{c.subheadline||data.description||"Une offre directe, claire et rassurante."}</p>{price}{benefits}</div>{pic(0)}{form(true)}</section><section className="v45-iconbar">{["Charge rapide","Capteur intelligent","Rotation 360°","Fixation solide"].map(x=><b key={x}>{x}</b>)}</section><section className="v45-split">{pic(1)}<div><small>LE PRODUIT</small><h2>Un produit complet pour votre quotidien</h2><p>{data.description||t.description}</p><ul><li>✓ Installation simple</li><li>✓ Utilisation intuitive</li><li>✓ Conception durable</li><li>✓ Pensé pour le quotidien</li></ul></div></section><section className="v45-steps"><h2>Comment ça marche ?</h2><div>{[1,2,3,4].map((n,i)=><article key={n}>{pic(i)}<b>{n}. Étape simple</b></article>)}</div></section><section className="v45-reviews"><h2>Ils nous font confiance</h2><div>{["Yassine · Casablanca","Sara · Rabat","Karim · Marrakech"].map(x=><article key={x}>★★★★★<b>{x}</b><p>Très pratique et conforme à la description.</p></article>)}</div></section>{faq}{foot}</main>;
 if(data.templateId==="premium-product")return <main className="v45 v45-premium">{head(true)}<section className="v45-premium-hero">{pic(0)}<div><small>COLLECTION SIGNATURE</small><h1>{c.headline||data.name}</h1><p>{data.description||"Un produit choisi pour son design, sa finition et son expérience."}</p>{price}<a href="#order">Découvrir</a></div></section><section className="v45-editorial"><blockquote>“Moins de bruit. Plus de matière, de détails et d'émotion.”</blockquote><div>{pic(1)}{pic(2)}</div></section><section className="v45-premium-story"><div><small>NOTRE SÉLECTION</small><h2>Conçu pour être remarqué</h2><p>{t.description}</p></div>{pic(3)}</section><section className="v45-premium-proof"><h2>Les détails font la différence</h2><div>{["Finition","Confort","Durabilité"].map(x=><article key={x}><b>{x}</b><p>Une présentation premium et rassurante.</p></article>)}</div></section>{form()}{faq}{foot}</main>;
 if(data.templateId==="ugc-social")return <main className="v45 v45-ugc">{head()}<section className="v45-ugc-hero"><div><span className="v45-kicker">VU SUR TIKTOK</span><h1>Le produit préféré des créateurs</h1><p>{data.description||t.description}</p>{price}<a href="#order">Je le veux</a></div><div className="v45-phone">{pic(0)}<span>▶ UGC</span></div></section><section className="v45-avatars">{[1,2,3,4,5].map(i=><div key={i}>{pic(i)}<b>Créateur {i}</b></div>)}</section><section className="v45-feed"><h2>Testé en conditions réelles</h2><div>{[1,2,3].map(i=><article key={i}>{pic(i)}<p>“Simple à utiliser et très pratique.”</p><b>★★★★★</b></article>)}</div></section><section className="v45-ugc-proof"><b>4.8/5</b><span>+1 200 avis vérifiés</span><span>Contenu authentique</span><span>Livraison Maroc</span></section>{form()}{faq}{foot}</main>;
 if(data.templateId==="problem-solver")return <main className="v45 v45-problem">{head()}<section className="v45-problem-hero"><div><span className="v45-kicker">LE PROBLÈME</span><h1>Vous connaissez cette situation ?</h1><p>Une difficulté quotidienne qui fait perdre du temps, du confort ou de l'énergie.</p></div>{pic(0)}</section><section className="v45-pain"><article><b>01</b><h3>Le problème</h3><p>Identifiez clairement la frustration du client.</p></article><article><b>02</b><h3>Pourquoi ça continue</h3><p>Les anciennes solutions ne répondent pas au besoin.</p></article><article><b>03</b><h3>La conséquence</h3><p>Le besoin d'une solution simple devient évident.</p></article></section><section className="v45-solution">{pic(1)}<div><span className="v45-kicker">LA SOLUTION</span><h2>{data.name}</h2><p>{data.description||t.description}</p>{price}<a href="#order">Résoudre le problème</a></div></section><section className="v45-result"><h2>Avant → Après</h2><div><article>{pic(2)}<b>Avant</b></article><article>{pic(3)}<b>Après</b></article></div></section>{benefits}{form()}{faq}{foot}</main>;
 return <main className="v45 v45-market">{head()}<section className="v45-market-main"><div className="v45-gallery"><div className="v45-thumbs">{[1,2,3,4].map(i=><button key={i}>{pic(i)}</button>)}</div>{pic(0,"v45-mainpic")}</div><div className="v45-buybox"><small>En stock · Livraison Maroc</small><h1>{data.name}</h1><div className="v45-stars">★★★★★ <span>4.8 (1200+ avis)</span></div><p>{data.description||t.description}</p>{price}<div className="v45-market-points"><span>✓ Produit vérifié</span><span>✓ Paiement COD</span><span>✓ Livraison rapide</span></div>{form(true)}</div></section><section className="v45-market-tabs"><b>Description</b><b>Caractéristiques</b><b>Livraison</b><b>Avis</b></section><section className="v45-specs"><h2>Tout ce qu'il faut savoir</h2><div>{["Qualité contrôlée","Utilisation facile","Design pratique","Support client"].map(x=><article key={x}><b>{x}</b><p>Information produit claire avant votre commande.</p></article>)}</div></section><section className="v45-reviews"><h2>Avis clients</h2><div>{["Client vérifié","Acheteur Maroc","Commande confirmée"].map(x=><article key={x}>★★★★★<b>{x}</b><p>Produit reçu et conforme.</p></article>)}</div></section>{faq}{foot}</main>
}