import { NextResponse } from "next/server";
export const dynamic = "force-dynamic";
export async function GET(req: Request) {
  const id = new URL(req.url).searchParams.get("id") || "";
  const js = `(()=>{const LANDING_ID=${JSON.stringify(id)};if(!LANDING_ID)return;const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"");const aliases={name:["name","nom","fullname","full_name","customer","client","الاسم","الإسم"],phone:["phone","tel","telephone","mobile","whatsapp","الهاتف","رقم"],city:["city","ville","town","مدينة","المدينة"],address:["address","adresse","location","العنوان"],quantity:["quantity","qty","quantite","qte","عدد"]};function find(form,key){const a=aliases[key];for(const el of form.querySelectorAll("input,select,textarea")){const label=el.id?document.querySelector('label[for="'+CSS.escape(el.id)+'"]')?.textContent:"";const hay=norm([el.name,el.id,el.placeholder,el.getAttribute("aria-label"),label].filter(Boolean).join(" "));if(a.some(x=>hay.includes(norm(x))))return el}if(key==="phone")return form.querySelector('input[type="tel"]');return null}function value(form,key){const el=find(form,key);return el?String(el.value||"").trim():""}function likely(form){return !!find(form,"phone")&&(!!find(form,"name")||/commande|commander|order|طلب|أكد|اطلب/i.test(form.textContent||""))}async function send(form){const payload={landing_id:LANDING_ID,name:value(form,"name"),phone:value(form,"phone"),city:value(form,"city"),address:value(form,"address"),quantity:Number(value(form,"quantity")||1)};if(!payload.phone)throw new Error("Téléphone non détecté");if(!payload.name)payload.name="Client landing externe";const r=await fetch("https://landpro.online/api/external-orders",{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:JSON.stringify(payload)});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"Commande LandPro impossible");form.dispatchEvent(new CustomEvent("landpro:order",{detail:x}));return x}document.addEventListener("submit",e=>{const form=e.target;if(!(form instanceof HTMLFormElement)||!likely(form)||form.dataset.landproSending==="1")return;form.dataset.landproSending="1";send(form).then(x=>console.info("[LandPro] Commande enregistrée",x)).catch(err=>{console.error("[LandPro]",err);form.dispatchEvent(new CustomEvent("landpro:error",{detail:{message:err?.message||"Erreur LandPro"}}))}).finally(()=>delete form.dataset.landproSending)},true);window.LandProOrders={send};})();`;
  return new NextResponse(js, {
    headers: {
      "content-type": "application/javascript; charset=utf-8",
      "cache-control": "no-store",
      "access-control-allow-origin": "*",
    },
  });
}
