export type ReferenceTemplate={id:string;no:number;hero:string;sections:string[];tone:string};
export const REFERENCE_TEMPLATES:ReferenceTemplate[]=[
["cod-direct",1,"product+compact COD form",["benefits","media","features","reviews","faq","order"],"green"],
["premium-product",2,"luxury editorial",["story","features","proof","faq","order"],"black-gold"],
["ugc-social",3,"creator/UGC",["creators","ugc","reviews","faq","order"],"blue"],
["problem-solver",4,"pain/problem",["problem","solution","before-after","proof","faq","order"],"red"],
["marketplace-cod",5,"marketplace buybox",["gallery","specs","reviews","faq","order"],"blue-orange"],
["flash-sale",6,"flash+timer",["timer","benefits","deal","reviews","faq","order"],"red"],
["minimal-clean",7,"minimal product",["benefits","gallery","features","faq","order"],"white-navy"],
["luxury-black",8,"black luxury",["story","details","proof","faq","order"],"black-gold"],
["beauty-glow",9,"beauty model",["benefits","routine","ugc","faq","order"],"pink"],
["health-trust",10,"doctor/trust",["trust","benefits","proof","faq","order"],"cyan-green"],
["auto-gear",11,"automotive product",["specs","benefits","gallery","faq","order"],"dark-orange"],
["tech-gadget",12,"neon technology",["specs","features","gallery","proof","faq","order"],"navy-purple"],
["before-after",13,"before/after",["compare","benefits","proof","faq","order"],"green"],
["story-selling",14,"cinematic story",["problem","story","benefits","proof","faq","order"],"brown"],
["video-first",15,"video dominant",["video","benefits","gallery","proof","faq","order"],"orange"],
["image-first",16,"large image",["gallery","benefits","proof","faq","order"],"navy"],
["benefit-cards",17,"benefit-led",["benefits","proof","reviews","faq","order"],"blue"],
["feature-showcase",18,"feature-led",["features","specs","proof","reviews","faq","order"],"blue"],
["social-proof",19,"reviews first",["proof","ugc","reviews","faq","order"],"green"],
["influencer-pick",20,"influencer recommendation",["ugc","proof","benefits","reviews","faq","order"],"pink"],
["one-screen-cod",21,"product+offer immediate",["benefits","proof","faq","order"],"green"],
["long-sales",22,"longform narrative",["problem","story","features","proof","reviews","faq","order"],"blue"],
["comparison-pro",23,"comparison table",["compare","features","proof","reviews","faq","order"],"teal"],
["bundle-offer",24,"quantity bundles",["bundle","benefits","proof","faq","order"],"pink"],
["fashion-editorial",25,"fashion model",["lookbook","details","proof","faq","order"],"peach"],
["home-solution",26,"home lifestyle",["problem","benefits","how","proof","faq","order"],"green"],
["arabic-cod",27,"RTL Arabic COD",["benefits","proof","reviews","faq","order"],"orange-green"],
["darija-morocco",28,"Moroccan delivery",["benefits","proof","reviews","faq","order"],"red"],
["whatsapp-commerce",29,"WhatsApp phone",["whatsapp","benefits","proof","faq","order"],"whatsapp-green"],
["conversion-max",30,"dark offer+timer",["timer","benefits","bundle","proof","faq","order"],"black-red"],
["apple-product",31,"monumental clean product",["story","bento","benefits","proof","faq","order"],"white-black"],
["samsung-launch",32,"immersive blue launch",["launch","features","benefits","proof","faq","order"],"black-blue"],
["dyson-premium",33,"engineering editorial",["engineering","features","benefits","proof","faq","order"],"white-purple"],
["nothing-tech",34,"monochrome technical grid",["grid","benefits","proof","faq","order"],"white-black"],
["gaming-neon",35,"neon gaming performance",["performance","benefits","proof","faq","order"],"black-purple"]
].map(([id,no,hero,sections,tone])=>({id:id as string,no:no as number,hero:hero as string,sections:sections as string[],tone:tone as string}));
export const referenceTemplate=(id:string)=>REFERENCE_TEMPLATES.find(x=>x.id===id);
