export type StoreLocale="darija"|"ar"|"fr";
type Profile={niche:string;hero:string;heroText:string;cta:string;collection:string;announcement:string;categories:string[];faq:{q:string;a:string}[];primary:string;accent:string;sections:string[]};
const niches=["COD Maroc","Général","Général","Minimal","Tech","Abaya & Mode Modeste","Mode & Fashion","Luxe","Bijoux","Montres","Lunettes","Sacs","Beauté","Parfums","Bébé","Chaussures","Fitness","Sport","Bien-être","Maison","Cuisine","Électronique","Gadgets","Automobile","Moto","Produit vedette","Promotions","Social & tendances","Premium","Marketplace"];
const colors=[["#12372a","#e67e22"],["#17324d","#e63946"],["#7f1d1d","#d97706"],["#111111","#111111"],["#050505","#f59e0b"],["#4c3d47","#a67c89"],["#1f2937","#db2777"],["#21180f","#b58b45"],["#19130a","#c99a2e"],["#101827","#2563eb"],["#0f3d4c","#06b6d4"],["#49362d","#c26d3b"],["#5b214b","#ec4899"],["#251725","#9f7aea"],["#4b7189","#f59eae"],["#111827","#ef4444"],["#17211a","#84cc16"],["#172554","#f97316"],["#285943","#4ade80"],["#44403c","#a16207"],["#7c2d12","#ea580c"],["#111827","#3b82f6"],["#172033","#8b5cf6"],["#18181b","#dc2626"],["#111111","#f97316"],["#0f172a","#16a34a"],["#991b1b","#f59e0b"],["#312e81","#ec4899"],["#000000","#d4af37"],["#1e3a8a","#f59e0b"]];
const fr:any={
"Abaya & Mode Modeste":["L’élégance modeste au quotidien","Découvrez une sélection d’abayas et de tenues modestes pensées pour allier élégance et confort.","Découvrir la collection","Nos essentiels","Abayas|Khimars|Nouveautés"],
"Sport":["Bouge plus. Va plus loin.","Équipe-toi pour l’entraînement, le running et un quotidien plus actif.","Voir la collection Sport","Performance & Sport","Running|Fitness|Accessoires"],
"Automobile":["Équipe ta voiture intelligemment","Des accessoires auto pratiques pour plus de confort, d’organisation et de sécurité au quotidien.","Découvrir Auto Gear","Accessoires Auto","Supports|Chargeurs|Confort"],
"Moto":["Prêt pour chaque trajet","Les accessoires essentiels pour moto, scooter et mobilité urbaine.","Découvrir Moto Ride","Équipement Moto","Supports|Route|Accessoires"],
"Beauté":["Révèle ton éclat","Une sélection beauté pensée pour une routine simple, élégante et efficace.","Découvrir Beauty Glow","Beauté & Soin","Soin|Routine|Nouveautés"],
"Parfums":["Une signature qui vous ressemble","Découvrez des parfums sélectionnés pour laisser une impression inoubliable.","Découvrir la collection","Parfums Signature","Femme|Homme|Best sellers"],
"Maison":["Un intérieur qui vous ressemble","Des essentiels pratiques et élégants pour améliorer chaque espace de votre maison.","Découvrir Maison","Maison & Lifestyle","Organisation|Déco|Essentiels"],
"Électronique":["La technologie utile au quotidien","Découvrez des produits tech sélectionnés pour simplifier votre quotidien.","Voir les nouveautés","Tech & Innovation","Mobile|Maison|Accessoires"],
"Gadgets":["Des idées smart pour tous les jours","Les gadgets pratiques et tendances qui rendent le quotidien plus simple.","Découvrir les gadgets","Smart Gadgets","Top ventes|Nouveautés|Pratique"],
"Chaussures":["Trouve ta prochaine paire","Sneakers et chaussures sélectionnées pour le style, le confort et le quotidien.","Shop Sneakers","Sneakers & Style","Sneakers|Lifestyle|Nouveautés"],
"Bijoux":["Des détails qui font la différence","Des bijoux élégants sélectionnés pour sublimer chaque moment.","Découvrir les bijoux","Bijoux & Éclat","Colliers|Bracelets|Best sellers"],
"Montres":["Le style à chaque seconde","Découvrez des montres qui associent caractère, élégance et quotidien.","Voir les montres","Collection Montres","Classique|Sport|Nouveautés"],
"Lunettes":["Votre style, votre regard","Lunettes et accessoires sélectionnés pour compléter chaque look.","Découvrir Vision","Lunettes & Style","Solaire|Optique|Nouveautés"],
"Sacs":["Le sac qui suit votre quotidien","Découvrez des sacs pratiques et élégants pour chaque occasion.","Voir les sacs","Sacs & Accessoires","Ville|Voyage|Nouveautés"],
"Fitness":["Construis ta meilleure routine","Équipement et accessoires pour progresser à la maison ou à la salle.","Découvrir Fitness","Fitness Essentials","Training|Maison|Accessoires"],
"Bien-être":["Prends soin de ton quotidien","Des essentiels sélectionnés pour le confort, la récupération et le bien-être.","Découvrir Wellness","Bien-être","Confort|Récupération|Essentiels"],
"Cuisine":["Plus simple, plus pratique en cuisine","Des accessoires intelligents pour gagner du temps et mieux profiter de votre cuisine.","Découvrir Cuisine","Cuisine Pratique","Préparation|Organisation|Top ventes"],
"Bébé":["Tout doux pour les petits","Des essentiels pratiques sélectionnés pour accompagner bébé et les parents au quotidien.","Découvrir Baby Care","Essentiels Bébé","Soin|Maison|Sortie"],
"Luxe":["L’exception au quotidien","Une sélection raffinée pour celles et ceux qui recherchent style et distinction.","Découvrir la sélection","Collection Signature","Premium|Nouveautés|Sélection"],
"Premium":["Une sélection sans compromis","Design, caractère et détails premium réunis dans une collection exclusive.","Découvrir Premium","Édition Premium","Exclusive|Signature|Best sellers"],
"Promotions":["Les offres à ne pas manquer","Profitez de nos sélections et offres du moment avant qu’elles ne disparaissent.","Voir les offres","Offres du moment","Flash|Best deals|Top ventes"],
"Marketplace":["Tout ce qu’il vous faut, au même endroit","Explorez nos catégories et trouvez rapidement les produits adaptés à votre quotidien.","Explorer le Store","Nos catégories","Maison|Tech|Lifestyle"],
"Produit vedette":["Le produit qui change votre quotidien","Découvrez notre produit vedette, ses bénéfices et pourquoi nos clients le choisissent.","Découvrir le produit","Produit vedette","Best seller|Offre|Nouveauté"]
};
function baseFr(niche:string){const v=fr[niche]||["Découvrez une sélection faite pour vous","Des produits sélectionnés avec soin, livraison partout au Maroc et paiement à la livraison.","Découvrir la boutique","Nos produits","Best sellers|Nouveautés|Sélection"];return v}
function localize(locale:StoreLocale,niche:string,v:any){if(locale==="fr")return v;if(locale==="ar")return ["اكتشف تشكيلتنا المختارة","منتجات مختارة بعناية مع التوصيل إلى جميع أنحاء المغرب والدفع عند الاستلام.","اكتشف المتجر",niche,"الأكثر مبيعاً|الجديد|مختاراتنا"];return ["كتاشف الاختيارات ديالنا","منتوجات مختارين بعناية، التوصيل لجميع المدن فالمغرب والخلص حتى يوصلك الطلب.","شوف المتجر",niche,"الأكثر مبيعاً|الجديد|اختياراتنا"]}
export function generateStoreSettings(templateId:string,locale:StoreLocale,name:string){const n=Math.max(1,Math.min(30,Number(templateId.replace("free-",""))||1)),niche=niches[n-1],v=localize(locale,niche,baseFr(niche)),c=colors[n-1];return {aiGenerated:true,aiNiche:niche,aiTemplate:templateId,primary:c[0],accent:c[1],logo:"",heroTitle:v[0],heroText:v[1],heroButton:v[2],heroImage:"",collectionTitle:v[3],categories:String(v[4]).split("|"),announcement:locale==="fr"?"🚚 Livraison partout au Maroc · Paiement à la livraison":"🚚 التوصيل لجميع المدن فالمغرب · الدفع عند الاستلام",showAnnouncement:true,showProducts:true,showTrust:true,showFooter:true,showFaq:true,selectedProductIds:[],sectionOrder:["hero","products","trust","faq","footer"],faq:locale==="fr"?[{q:"Comment fonctionne la livraison ?",a:"Nous livrons partout au Maroc. Les délais dépendent de votre ville."},{q:"Comment puis-je payer ?",a:"Vous payez à la livraison après réception de votre commande."}]:[{q:"كيفاش كيدوز التوصيل؟",a:"كنوصلو لجميع المدن فالمغرب، والمدة كتختلف حسب المدينة."},{q:"كيفاش نخلص؟",a:"كتخلص ملي يوصلك الطلب."}],generatedFor:name}}
