export type PremiumTheme={id:string;name:string;category:string;description:string;colors:[string,string,string,string];font:"Tajawal"|"Cairo"|"IBM Plex Sans Arabic";mode:"dark"|"light"};
export const PREMIUM_THEMES:PremiumTheme[]=[
{id:"cod-red-boost",name:"Red Boost",category:"COD Conversion",description:"Urgence, promotion et conversion directe",colors:["#fff7f5","#ffffff","#241513","#e53935"],font:"Cairo",mode:"light"},
{id:"cod-green-trust",name:"Green Trust",category:"COD Conversion",description:"Confiance, livraison et paiement COD",colors:["#f3faf5","#ffffff","#173321","#249a55"],font:"Tajawal",mode:"light"},
{id:"cod-orange-flash",name:"Orange Flash",category:"COD Conversion",description:"Offre énergique pour produit gagnant",colors:["#fff7ed","#ffffff","#321d0d","#ff7900"],font:"Cairo",mode:"light"},
{id:"cod-midnight",name:"Midnight Conversion",category:"COD Conversion",description:"Conversion premium sur fond sombre",colors:["#090d16","#121827","#f7f9ff","#ff8a34"],font:"Tajawal",mode:"dark"},
{id:"cod-clean",name:"Clean COD",category:"COD Conversion",description:"Minimal, lisible et rassurant",colors:["#f7f8fa","#ffffff","#17202a","#2563eb"],font:"IBM Plex Sans Arabic",mode:"light"},
{id:"luxury-black-gold",name:"Black Gold",category:"Luxury",description:"Noir profond et accents or",colors:["#0c0b09","#17140f","#fff8e8","#d4af55"],font:"Cairo",mode:"dark"},
{id:"luxury-ivory",name:"Ivory Atelier",category:"Luxury",description:"Ivoire élégant et finition éditoriale",colors:["#f8f4ea","#fffdf8","#2c261f","#aa7d45"],font:"Tajawal",mode:"light"},
{id:"luxury-navy",name:"Royal Navy",category:"Luxury",description:"Bleu royal et détails champagne",colors:["#071321","#0d2035","#f7f5ee","#d7b978"],font:"IBM Plex Sans Arabic",mode:"dark"},
{id:"luxury-emerald",name:"Emerald Prestige",category:"Luxury",description:"Émeraude sombre et finition bijouterie",colors:["#061713","#0c2820","#f2fff9","#45c392"],font:"Cairo",mode:"dark"},
{id:"luxury-bronze",name:"Chocolate Bronze",category:"Luxury",description:"Brun chocolat et bronze chaleureux",colors:["#17100c","#261912","#fff6ec","#c48352"],font:"Tajawal",mode:"dark"},
{id:"auto-carbon",name:"Carbon Auto",category:"Auto / Tech",description:"Carbone, métal et performance",colors:["#090b0d","#15191d","#f4f7fa","#ff5b35"],font:"IBM Plex Sans Arabic",mode:"dark"},
{id:"auto-racing",name:"Racing Red",category:"Auto / Tech",description:"Rouge racing et contraste puissant",colors:["#110a0a","#211010","#fff6f4","#ef312f"],font:"Cairo",mode:"dark"},
{id:"tech-electric",name:"Electric Blue",category:"Auto / Tech",description:"Bleu électrique pour gadgets modernes",colors:["#061526","#0b2540","#eef8ff","#2196f3"],font:"IBM Plex Sans Arabic",mode:"dark"},
{id:"tech-cyber",name:"Cyber Neon",category:"Auto / Tech",description:"Tech sombre avec accent néon",colors:["#070b12","#101725","#f3f7ff","#7c5cff"],font:"Tajawal",mode:"dark"},
{id:"tech-silver",name:"Silver Minimal",category:"Auto / Tech",description:"Minimalisme technologique clair",colors:["#f4f6f8","#ffffff","#17212b","#536579"],font:"IBM Plex Sans Arabic",mode:"light"},
{id:"beauty-rose",name:"Rose Studio",category:"Beauty / Health",description:"Rose doux pour beauté et skincare",colors:["#fff5f7","#ffffff","#3c222b","#d85f83"],font:"Tajawal",mode:"light"},
{id:"beauty-nude",name:"Nude Glow",category:"Beauty / Health",description:"Nude premium et cosmétique naturelle",colors:["#f8f0ea","#fffaf6","#3b2d27","#c98468"],font:"Cairo",mode:"light"},
{id:"health-aqua",name:"Aqua Care",category:"Beauty / Health",description:"Propre, médical et rassurant",colors:["#effafb","#ffffff","#15343a","#1599a8"],font:"IBM Plex Sans Arabic",mode:"light"},
{id:"health-sage",name:"Sage Wellness",category:"Beauty / Health",description:"Bien-être naturel et calme",colors:["#f2f6ef","#ffffff","#243426","#6f956d"],font:"Tajawal",mode:"light"},
{id:"beauty-plum",name:"Plum Signature",category:"Beauty / Health",description:"Beauté premium avec prune profond",colors:["#1b0e18","#2b1726","#fff5fb","#d276aa"],font:"Cairo",mode:"dark"},
{id:"fashion-editorial",name:"Editorial Mono",category:"Fashion / Lifestyle",description:"Mode éditoriale noir et blanc",colors:["#f7f7f5","#ffffff","#171717","#171717"],font:"IBM Plex Sans Arabic",mode:"light"},
{id:"fashion-caramel",name:"Caramel Chic",category:"Fashion / Lifestyle",description:"Mode chaleureuse et accessoires",colors:["#f7efe5","#fffaf4","#33251c","#b8733d"],font:"Tajawal",mode:"light"},
{id:"fashion-burgundy",name:"Burgundy House",category:"Fashion / Lifestyle",description:"Bordeaux élégant pour accessoires",colors:["#180b0e","#2b1118","#fff6f7","#b9475e"],font:"Cairo",mode:"dark"},
{id:"fashion-lilac",name:"Lilac Modern",category:"Fashion / Lifestyle",description:"Lifestyle contemporain et doux",colors:["#f8f5ff","#ffffff","#302742","#8b6ad9"],font:"Tajawal",mode:"light"},
{id:"fashion-olive",name:"Olive Street",category:"Fashion / Lifestyle",description:"Streetwear naturel et moderne",colors:["#11140d","#20261a","#f7f8ef","#9bae58"],font:"IBM Plex Sans Arabic",mode:"dark"},
{id:"home-sand",name:"Sand Home",category:"Home / Family",description:"Maison chaleureuse et minimaliste",colors:["#f5efe5","#fffaf2","#342d25","#aa8052"],font:"Tajawal",mode:"light"},
{id:"home-terracotta",name:"Terracotta Living",category:"Home / Family",description:"Décoration chaleureuse et artisanale",colors:["#fff4ed","#ffffff","#3a241c","#c96543"],font:"Cairo",mode:"light"},
{id:"home-moroccan",name:"Moroccan Premium",category:"Home / Family",description:"Vert zellige, sable et cuivre",colors:["#071b18","#0d2b26","#fff8e9","#c88b4a"],font:"Cairo",mode:"dark"},
{id:"kids-soft",name:"Kids Soft",category:"Home / Family",description:"Pastels doux pour bébé et famille",colors:["#fffaf2","#ffffff","#34354a","#7867d9"],font:"Tajawal",mode:"light"},
{id:"home-ocean",name:"Ocean Home",category:"Home / Family",description:"Maison fraîche et bleu côtier",colors:["#f1f8fa","#ffffff","#17313a","#397f91"],font:"IBM Plex Sans Arabic",mode:"light"}
];
export const THEME_CATEGORIES=["Tous",...Array.from(new Set(PREMIUM_THEMES.map(t=>t.category)))];
