// Série 3 — 20 templates de boutique, un par maquette envoyée (captures 1 à 20).
// Les maquettes servent de référence de mise en page, de couleurs et de typographie ;
// textes, noms et chiffres sont propres à LandPro (aucun chiffre inventé : {products},
// {categories} ou des engagements réels comme le paiement à la livraison).
import type { StoreTemplate, SxBlock, SxCopy, SxSectionType, SxTheme } from "./types";
import { SHARED_AR, SHARED_FR, withShared } from "./shared-copy";

type Blocks = Partial<Record<SxSectionType, SxBlock>>;
type Txt = Omit<SxCopy, "sections" | "announcement" | "collectionSubtitle"> & {
  announcement?: string;
  collectionSubtitle?: string;
  sections?: Blocks;
};

const base: Omit<SxTheme, "primary" | "accent" | "heroBg" | "heroText"> = {
  bg: "#ffffff",
  surface: "#f5f5f5",
  text: "#111111",
  muted: "#6b7280",
  border: "#e5e7eb",
  onPrimary: "#ffffff",
  onAccent: "#ffffff",
  dark: "#111111",
  onDark: "#ffffff",
  radius: 12,
  headingFont: "Inter",
  bodyFont: "Inter",
  headingWeight: 700,
};
const theme = (t: Partial<SxTheme> & Pick<SxTheme, "primary" | "accent" | "heroBg" | "heroText">): SxTheme => ({
  ...base,
  ...t,
});
const copy = (fr: Txt, ar: Txt) => ({
  fr: {
    announcement: "Livraison partout au Maroc · Paiement à la livraison",
    collectionSubtitle: "",
    ...fr,
    sections: withShared(SHARED_FR, fr.sections || {}),
  } as SxCopy,
  ar: {
    announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
    collectionSubtitle: "",
    ...ar,
    sections: withShared(SHARED_AR, ar.sections || {}),
  } as SxCopy,
});

/** Garanties courtes, reprises par plusieurs heros. */
const statsFr = [
  { value: "{products}", title: "Produits disponibles" },
  { value: "{categories}", title: "Catégories" },
  { value: "100%", title: "Paiement à la livraison" },
];
const statsAr = [
  { value: "{products}", title: "منتج متوفر" },
  { value: "{categories}", title: "تصنيف" },
  { value: "100%", title: "الدفع عند الاستلام" },
];

export const SERIE_3: StoreTemplate[] = [
  /* 01 · doudounes bleu glacier */
  {
    id: "s3-01",
    series: 3,
    folder: "01_FRZN Puffers",
    name: "Givre Urbain",
    niche: "Mode hiver & streetwear",
    description: "Bleu acier, gros titres condensés, produit flottant, cartes à coin coupé et logotype sur montagnes.",
    theme: theme({
      bg: "#bcd0e2",
      surface: "#a9c0d6",
      text: "#ffffff",
      muted: "#e3ecf5",
      border: "rgba(255,255,255,0.22)",
      primary: "#ffffff",
      onPrimary: "#4d6a86",
      accent: "#ffffff",
      onAccent: "#4d6a86",
      dark: "#4d6a86",
      heroBg: "#4d6a86",
      heroText: "#ffffff",
      radius: 4,
      headingFont: "Anton",
      bodyFont: "Space Mono",
      headingWeight: 400,
      headingCase: "uppercase",
      headingTracking: "0",
    }),
    header: "dark",
    hero: "frost",
    card: "plain",
    categories: "square-tiles",
    promos: "cards",
    trust: "numbered",
    layout: {
      header: "editorial",
      card: "cut",
      faq: "numbered",
      footer: "wordmark",
      shop: "topbar",
      product: "panel",
      page: "split",
    },
    sections: ["hero", "products", "marquee", "specs", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    showAnnouncement: false,
    copy: copy(
      {
        eyebrow: "Collection grand froid",
        title: "Quand le froid tombe, tout le reste se tait",
        highlight: "se tait",
        text: "Des pièces pensées pour la chaleur, pas pour l'apparence. Garnissage généreux, coupes amples, finitions robustes.",
        button: "Ajouter au panier",
        collectionTitle: "Inventaire grand froid",
        sections: {
          hero: {
            items: [
              { title: "Vous ne sentez plus le froid" },
              { title: "[ Garnissage dense ] [ Coupe ample ] [ Coutures renforcées ]" },
            ],
          },
          marquee: {
            items: [{ title: "Chaud" }, { title: "Ample" }, { title: "Robuste" }, { title: "Livré partout au Maroc" }],
          },
          specs: {
            title: "Fiche technique",
            items: [
              { title: "Garnissage", value: "Dense et léger" },
              { title: "Coupe", value: "Oversize" },
              { title: "Paiement", value: "À la livraison" },
              { title: "Échange", value: "Facile" },
            ],
          },
          newsletter: {
            title: "Rejoignez l'équipe grand froid",
            text: "Nouveaux arrivages et réassorts : écrivez-nous sur WhatsApp.",
          },
        },
      },
      {
        eyebrow: "مجموعة البرد",
        title: "ملي كيطيح البرد، كلشي كيسكت",
        highlight: "كيسكت",
        text: "قطع مصممة للدفا ماشي للمظهر. حشوة كثيفة، قصات واسعة وخياطة قوية.",
        button: "زيد للسلة",
        collectionTitle: "مخزون البرد",
        sections: {
          hero: {
            items: [{ title: "ما بقيتيش كتحس بالبرد" }, { title: "[ حشوة كثيفة ] [ قصة واسعة ] [ خياطة قوية ]" }],
          },
          marquee: {
            items: [{ title: "دافي" }, { title: "واسع" }, { title: "قوي" }, { title: "التوصيل لجميع المدن" }],
          },
          specs: {
            title: "البطاقة التقنية",
            items: [
              { title: "الحشوة", value: "كثيفة وخفيفة" },
              { title: "القصة", value: "واسعة" },
              { title: "الدفع", value: "عند الاستلام" },
              { title: "التبديل", value: "ساهل" },
            ],
          },
          newsletter: { title: "انضم لفريق البرد", text: "السلعة الجديدة: كتب لينا فواتساب." },
        },
      },
    ),
  },
  /* 02 · montres de luxe noir & or */
  {
    id: "s3-02",
    series: 3,
    folder: "02_Timecraft Watches",
    name: "Heure d'Or",
    niche: "Montres & accessoires de luxe",
    description: "Noir profond et or : hero photo sombre, catégories en cartes noires, cartes blanches avec cœur.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f4f4f4",
      text: "#111111",
      muted: "#666666",
      border: "#e6e6e6",
      primary: "#111111",
      accent: "#b08a52",
      dark: "#0d0d0d",
      heroBg: "#0d0d0d",
      heroText: "#ffffff",
      radius: 4,
      headingFont: "Oswald",
      bodyFont: "DM Sans",
      headingWeight: 600,
      headingCase: "uppercase",
      headingTracking: "0.01em",
    }),
    header: "overlay",
    hero: "luxe-dark",
    card: "plain",
    categories: "dark-tiles",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "utility",
      card: "heart",
      faq: "split",
      footer: "mega",
      shop: "sidebar",
      product: "split",
      page: "banner",
    },
    sections: ["hero", "categories", "products", "promos", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle collection",
        title: "Précision. Pensée pour durer.",
        highlight: "Pensée pour durer.",
        text: "Un design intemporel, une finition soignée.",
        button: "Voir les nouveautés",
        secondary: "Nos collections",
        collectionTitle: "Meilleures ventes",
        sections: {
          categories: { title: "Acheter par catégorie" },
          promos: {
            items: [
              {
                value: "Édition limitée",
                title: "Des pièces en petite série",
                text: "Pour celles et ceux qui aiment se démarquer.",
                image: "",
              },
              {
                value: "Conseil",
                title: "Un conseil avant de choisir ?",
                text: "Écrivez-nous sur WhatsApp, on vous guide.",
                image: "",
              },
            ],
          },
          newsletter: { title: "Restez à l'heure", text: "Nouveautés et offres : contactez-nous sur WhatsApp." },
        },
      },
      {
        eyebrow: "مجموعة جديدة",
        title: "الدقة. مصممة باش تدوم.",
        highlight: "مصممة باش تدوم.",
        text: "تصميم ما كيقدمش، وتشطيب متقن.",
        button: "شوف الجديد",
        secondary: "المجموعات",
        collectionTitle: "الأكثر مبيعا",
        sections: {
          categories: { title: "تسوق حسب التصنيف" },
          promos: {
            items: [
              { value: "إصدار محدود", title: "قطع بعدد قليل", text: "للي كيبغيو يتميزو.", image: "" },
              { value: "نصيحة", title: "بغيتي نصيحة قبل ما تختار؟", text: "كتب لينا فواتساب ونعاونوك.", image: "" },
            ],
          },
          newsletter: { title: "خليك فالوقت", text: "الجديد والعروض: تواصل معانا فواتساب." },
        },
      },
    ),
  },
  /* 03 · marché orange */
  {
    id: "s3-03",
    series: 3,
    folder: "03_BestShop Thermos",
    name: "Bazar Orange",
    niche: "Maison, cuisine & multi-produits",
    description: "Orange et blanc : grande recherche, bannière beige à flèches, offres du jour, mosaïque promo.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f6f6f6",
      text: "#1e1e1e",
      muted: "#777777",
      border: "#ececec",
      primary: "#1e1e1e",
      accent: "#f7931e",
      dark: "#1e1e1e",
      heroBg: "#f7e6d8",
      heroText: "#1e1e1e",
      radius: 10,
      headingFont: "Montserrat",
      bodyFont: "Open Sans",
      headingWeight: 800,
    }),
    header: "split",
    hero: "slider-beige",
    card: "plain",
    categories: "square-tiles",
    promos: "cards",
    trust: "bar",
    layout: {
      header: "stacked",
      card: "market",
      faq: "center",
      footer: "columns",
      shop: "sidebar",
      product: "stack",
      page: "simple",
    },
    sections: [
      "hero",
      "trust",
      "categories",
      "marquee",
      "deals",
      "mosaic",
      "products",
      "testimonials",
      "faq",
      "newsletter",
    ],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouveautés",
        title: "Des produits pratiques pour tous les jours",
        highlight: "",
        text: "Garder au chaud · Garder au frais · Toute la journée",
        button: "Acheter",
        collectionTitle: "Produits à la une",
        sections: {
          categories: { title: "Catégories populaires" },
          marquee: {
            items: [
              { title: "Bienvenue dans notre boutique" },
              { title: "Paiement à la livraison" },
              { title: "Livraison partout au Maroc" },
            ],
          },
          deals: { eyebrow: "Offres du jour", title: "Les offres du jour" },
          mosaic: {
            items: [
              { value: "Pratique", title: "Garde au chaud", text: "Des heures de chaleur.", image: "" },
              { value: "Pratique", title: "Garde au frais", text: "Idéal pour l'été.", image: "" },
              { value: "Offre", title: "Les bons plans", text: "Nos meilleures offres du moment.", image: "" },
              { value: "Qualité", title: "Matériaux sûrs", text: "Choisis avec soin.", image: "" },
              { value: "Écologique", title: "Réutilisable", text: "Moins de déchets au quotidien.", image: "" },
            ],
          },
        },
      },
      {
        eyebrow: "جديد",
        title: "منتجات عملية لكل نهار",
        highlight: "",
        text: "كيحافظ على السخونية · كيحافظ على البرودة · طول النهار",
        button: "اشري",
        collectionTitle: "منتجات مميزة",
        sections: {
          categories: { title: "التصنيفات المشهورة" },
          marquee: {
            items: [{ title: "مرحبا بيك فالمتجر" }, { title: "الدفع عند الاستلام" }, { title: "التوصيل لجميع المدن" }],
          },
          deals: { eyebrow: "عروض اليوم", title: "عروض اليوم" },
          mosaic: {
            items: [
              { value: "عملي", title: "كيحافظ على السخونية", text: "ساعات ديال الدفا.", image: "" },
              { value: "عملي", title: "كيحافظ على البرودة", text: "مزيان للصيف.", image: "" },
              { value: "عرض", title: "الهمزات", text: "أحسن العروض دابا.", image: "" },
              { value: "جودة", title: "مواد آمنة", text: "مختارة بعناية.", image: "" },
              { value: "بيئي", title: "كيتعاود يتستعمل", text: "نفايات قل كل نهار.", image: "" },
            ],
          },
        },
      },
    ),
  },
  /* 04 · néon rouge sur noir */
  {
    id: "s3-04",
    series: 3,
    folder: "04_AgentAI",
    name: "Néon Rouge",
    niche: "High-tech & gadgets",
    description: "Noir et rouge néon : halo lumineux, cartes en verre, phrase de présentation en couleur.",
    theme: theme({
      bg: "#050505",
      surface: "#141414",
      text: "#f4f4f4",
      muted: "#9a9a9a",
      border: "rgba(255,255,255,0.1)",
      primary: "#ff3b1f",
      accent: "#ff3b1f",
      dark: "#0d0d0d",
      heroBg: "#050505",
      heroText: "#ffffff",
      radius: 18,
      headingFont: "Inter Tight",
      bodyFont: "Inter",
      headingWeight: 500,
      headingTracking: "-0.04em",
    }),
    header: "overlay",
    hero: "neon",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "icons",
    statement: "inline",
    layout: {
      header: "pill",
      card: "glass",
      faq: "cards",
      footer: "minimal",
      shop: "topbar",
      product: "centered",
      page: "simple",
    },
    sections: ["hero", "statement", "products", "services", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle génération",
        title: "La tech qui suit votre rythme",
        highlight: "votre rythme",
        text: "Des gadgets choisis pour leur qualité, testés avant d'être proposés, livrés partout au Maroc.",
        button: "Voir les produits",
        secondary: "Nous contacter",
        collectionTitle: "Nos produits phares",
        sections: {
          hero: { items: statsFr },
          statement: {
            eyebrow: "À propos",
            title: "Nous choisissons des produits utiles,",
            text: "fiables et simples à utiliser, pour améliorer votre quotidien.",
            button: "Nous contacter",
            items: statsFr,
          },
          services: {
            eyebrow: "Services",
            title: "Un accompagnement de bout en bout",
            items: [
              { title: "Conseil avant achat", text: "On vous aide à choisir le bon produit." },
              { title: "Paiement à la livraison", text: "Vous payez à la réception." },
              { title: "Livraison rapide", text: "Partout au Maroc." },
              { title: "Échange facile", text: "Un souci ? On trouve une solution." },
              { title: "Suivi sur WhatsApp", text: "Réponse rapide à vos questions." },
              { value: "{products}", title: "Produits disponibles", text: "Sélectionnés et testés." },
            ],
          },
        },
      },
      {
        eyebrow: "جيل جديد",
        title: "تكنولوجيا كتمشي معاك",
        highlight: "معاك",
        text: "أجهزة مختارة على حساب الجودة، مجربة قبل ما نعرضوها، والتوصيل لجميع المدن.",
        button: "شوف المنتجات",
        secondary: "تواصل معانا",
        collectionTitle: "المنتجات المميزة",
        sections: {
          hero: { items: statsAr },
          statement: {
            eyebrow: "شكون حنا",
            title: "كنختارو منتجات مفيدة،",
            text: "موثوقة وساهلة فالاستعمال، باش يولي نهارك أحسن.",
            button: "تواصل معانا",
            items: statsAr,
          },
          services: {
            eyebrow: "الخدمات",
            title: "مرافقة من البداية للنهاية",
            items: [
              { title: "نصيحة قبل الشرا", text: "نعاونوك تختار المنتج المناسب." },
              { title: "الدفع عند الاستلام", text: "خلص ملي توصلك." },
              { title: "توصيل سريع", text: "لجميع المدن." },
              { title: "تبديل ساهل", text: "شي مشكل؟ كنلقاو الحل." },
              { title: "تتبع فواتساب", text: "جواب سريع." },
              { value: "{products}", title: "منتج متوفر", text: "مختارة ومجربة." },
            ],
          },
        },
      },
    ),
  },
  /* 05 · lunettes noir & citron */
  {
    id: "s3-05",
    series: 3,
    folder: "05_EEye Wear",
    name: "Regard Noir",
    niche: "Lunettes & optique",
    description: "Noir et vert citron : portrait à droite, note manuscrite, cartes sombres avec panier.",
    theme: theme({
      bg: "#0b0b0b",
      surface: "#161616",
      text: "#f5f5f5",
      muted: "#9a9a9a",
      border: "rgba(255,255,255,0.1)",
      primary: "#d7f35a",
      onPrimary: "#111111",
      accent: "#d7f35a",
      onAccent: "#111111",
      dark: "#111111",
      heroBg: "#0b0b0b",
      heroText: "#ffffff",
      radius: 12,
      headingFont: "Syne",
      bodyFont: "Manrope",
      scriptFont: "Caveat",
      headingWeight: 700,
    }),
    header: "dark",
    hero: "portrait-dark",
    card: "plain",
    categories: "side-cards",
    promos: "cards",
    trust: "icons",
    statement: "rows",
    layout: {
      header: "classic",
      card: "dark-icon",
      faq: "band",
      footer: "columns",
      shop: "banner",
      product: "split",
      page: "split",
    },
    sections: ["hero", "categories", "products", "statement", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Voir le monde autrement",
        title: "Des lunettes pour voir plus clair demain",
        highlight: "demain",
        text: "Élégantes, confortables, faites pour vous. Des montures choisies pour votre style et votre vue.",
        button: "Acheter",
        secondary: "Livraison",
        collectionTitle: "Meilleures ventes",
        sections: {
          hero: { items: [{ title: "Mieux voir, mieux vivre" }] },
          categories: {
            eyebrow: "Par catégorie",
            title: "Trouvez la monture idéale",
            text: "Pour chaque style, chaque visage et chaque occasion.",
          },
          statement: {
            eyebrow: "Notre histoire",
            title: "Plus que des lunettes,",
            text: "un style de vie : du confort, du style et une vraie qualité.",
            button: "En savoir plus",
            items: statsFr,
          },
          newsletter: { title: "Offres et nouveautés", text: "Écrivez-nous pour être informé des nouveaux modèles." },
        },
      },
      {
        eyebrow: "شوف العالم بطريقة أخرى",
        title: "نظارات باش تشوف أوضح غدا",
        highlight: "غدا",
        text: "أنيقة، مريحة ومصممة ليك. إطارات مختارة على حساب الستيل والنظر.",
        button: "اشري",
        secondary: "التوصيل",
        collectionTitle: "الأكثر مبيعا",
        sections: {
          hero: { items: [{ title: "شوف أحسن، عيش أحسن" }] },
          categories: { eyebrow: "حسب التصنيف", title: "لقا الإطار المناسب", text: "لكل ستيل ولكل وجه ولكل مناسبة." },
          statement: {
            eyebrow: "قصتنا",
            title: "كثر من نظارات،",
            text: "ستيل ديال الحياة: راحة، أناقة وجودة حقيقية.",
            button: "عرف كثر",
            items: statsAr,
          },
          newsletter: { title: "العروض والجديد", text: "كتب لينا باش نعلموك بالموديلات الجديدة." },
        },
      },
    ),
  },
  /* 06 · pneus rouge & gris */
  {
    id: "s3-06",
    series: 3,
    folder: "06_Cool Tyres",
    name: "Pneu Rouge",
    niche: "Auto, pneus & pièces",
    description:
      "Gris foncé et rouge : photo sombre avec découpe en biais, catégories en icônes, grand bandeau marques.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f2f2f2",
      text: "#222222",
      muted: "#777777",
      border: "#e3e3e3",
      primary: "#e3262f",
      accent: "#e3262f",
      dark: "#262626",
      heroBg: "#1a1a1a",
      heroText: "#ffffff",
      radius: 2,
      headingFont: "Oswald",
      bodyFont: "Roboto",
      headingWeight: 700,
      headingCase: "uppercase",
    }),
    header: "overlay",
    hero: "diagonal",
    card: "plain",
    categories: "icon-grid",
    promos: "cards",
    trust: "bar",
    layout: {
      header: "editorial",
      card: "tyre",
      faq: "center",
      footer: "cta",
      shop: "sidebar",
      product: "stack",
      page: "banner",
    },
    sections: ["hero", "categories", "products", "spotlight", "trust", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Offres du moment",
        title: "Des pneus de qualité pour chaque route",
        highlight: "",
        text: "Voitures, SUV, utilitaires : trouvez la bonne taille et faites-vous livrer.",
        button: "Voir les produits",
        secondary: "Nous contacter",
        collectionTitle: "Nos produits",
        sections: {
          categories: { eyebrow: "Par type", title: "Catégories", text: "Choisissez votre type de véhicule." },
          spotlight: { eyebrow: "Service & conseil", title: "Les meilleures marques de pneus", button: "Nous appeler" },
        },
      },
      {
        eyebrow: "عروض دابا",
        title: "روايض ديال الجودة لكل طريق",
        highlight: "",
        text: "طوموبيلات، SUV وكاميونات: لقا القياس المناسب ونوصلوه ليك.",
        button: "شوف المنتجات",
        secondary: "تواصل معانا",
        collectionTitle: "المنتجات ديالنا",
        sections: {
          categories: { eyebrow: "حسب النوع", title: "التصنيفات", text: "ختار نوع الطوموبيل ديالك." },
          spotlight: { eyebrow: "خدمة ونصيحة", title: "أحسن ماركات الروايض", button: "عيط لينا" },
        },
      },
    ),
  },
  /* 07 · couleurs pop */
  {
    id: "s3-07",
    series: 3,
    folder: "07_PHLOX",
    name: "Couleurs Pop",
    niche: "Électronique & audio",
    description: "Blanc et couleurs vives : mot géant transparent derrière le produit, cartes catégories colorées.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f0f0f0",
      text: "#111111",
      muted: "#7a7a7a",
      border: "#eeeeee",
      primary: "#f0313a",
      accent: "#f0313a",
      dark: "#1b1b1b",
      heroBg: "#ececec",
      heroText: "#111111",
      radius: 18,
      headingFont: "Poppins",
      bodyFont: "Poppins",
      headingWeight: 700,
    }),
    header: "split",
    hero: "ghost-word",
    card: "plain",
    categories: "color-blocks",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "classic",
      card: "centered",
      faq: "cards",
      footer: "centered",
      shop: "topbar",
      product: "centered",
      page: "simple",
    },
    sections: ["hero", "categories", "trust", "products", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Son sans fil",
        title: "Le son qui vous suit partout",
        highlight: "",
        text: "Du son clair, de l'autonomie et du confort : des produits choisis pour durer.",
        button: "Acheter par catégorie",
        collectionTitle: "Produits populaires",
        sections: { hero: { items: [{ title: "Audio" }] }, categories: { title: "" } },
      },
      {
        eyebrow: "صوت بلا خيط",
        title: "صوت كيتبعك فين ما مشيتي",
        highlight: "",
        text: "صوت صافي، بطارية طويلة وراحة: منتجات مختارة باش تدوم.",
        button: "تسوق حسب التصنيف",
        collectionTitle: "المنتجات المشهورة",
        sections: { hero: { items: [{ title: "صوت" }] }, categories: { title: "" } },
      },
    ),
  },
  /* 08 · garage noir */
  {
    id: "s3-08",
    series: 3,
    folder: "08_CarStore",
    name: "Garage Noir",
    niche: "Accessoires & pièces auto",
    description: "Gris anthracite et rouge : grande photo plein cadre, tuiles 2×2 alternées, doubles bannières.",
    theme: theme({
      bg: "#2b2b2b",
      surface: "#353535",
      text: "#f2f2f2",
      muted: "#a6a6a6",
      border: "rgba(255,255,255,0.08)",
      primary: "#d6242f",
      accent: "#d6242f",
      dark: "#1a1a1a",
      heroBg: "#1a1a1a",
      heroText: "#ffffff",
      radius: 3,
      headingFont: "Lato",
      bodyFont: "Lato",
      headingWeight: 700,
      headingCase: "uppercase",
      headingTracking: "0.03em",
    }),
    header: "overlay",
    hero: "smoke",
    card: "plain",
    categories: "split-tiles",
    promos: "split",
    trust: "bar",
    layout: {
      header: "utility",
      card: "glass",
      faq: "split",
      footer: "columns",
      shop: "banner",
      product: "panel",
      page: "banner",
    },
    sections: ["hero", "categories", "products", "promos", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Pièces & accessoires",
        title: "Équipez votre voiture",
        highlight: "",
        text: "Phares, jantes, sièges et accessoires : livrés partout au Maroc.",
        button: "Voir les produits",
        collectionTitle: "Produits à la une",
        sections: {
          categories: { title: "" },
          promos: {
            items: [
              { value: "Offre", title: "Livraison partout au Maroc", text: "Paiement à la livraison.", image: "" },
              {
                value: "Conseil",
                title: "Besoin d'aide pour choisir ?",
                text: "Écrivez-nous sur WhatsApp.",
                image: "",
              },
            ],
          },
        },
      },
      {
        eyebrow: "قطع وإكسسوارات",
        title: "جهز الطوموبيل ديالك",
        highlight: "",
        text: "ضواو، جنطات، كراسي وإكسسوارات: التوصيل لجميع المدن.",
        button: "شوف المنتجات",
        collectionTitle: "منتجات مميزة",
        sections: {
          categories: { title: "" },
          promos: {
            items: [
              { value: "عرض", title: "التوصيل لجميع المدن", text: "الدفع عند الاستلام.", image: "" },
              { value: "نصيحة", title: "بغيتي مساعدة باش تختار؟", text: "كتب لينا فواتساب.", image: "" },
            ],
          },
        },
      },
    ),
  },
  /* 09 · sneakers pop */
  {
    id: "s3-09",
    series: 3,
    folder: "09_WebStore Sneakers",
    name: "Sneaker Pop",
    niche: "Chaussures & sport",
    description: "Blanc et rouge corail : produit dans un grand disque, cartes à disque coloré, mosaïque colorée.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f3f3f3",
      text: "#111111",
      muted: "#6f6f6f",
      border: "#ececec",
      primary: "#e8473f",
      accent: "#e8473f",
      dark: "#111111",
      heroBg: "#ffffff",
      heroText: "#111111",
      radius: 14,
      headingFont: "Roboto Condensed",
      bodyFont: "Roboto",
      headingWeight: 700,
      headingCase: "uppercase",
    }),
    header: "split",
    hero: "circle-product",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "search",
      card: "circle",
      faq: "numbered",
      footer: "centered",
      shop: "topbar",
      product: "split",
      page: "split",
    },
    sections: ["hero", "products", "mosaic", "spotlight", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle saison",
        title: "La collection d'été est arrivée",
        highlight: "La collection",
        text: "Des sneakers confortables et stylées, livrées partout au Maroc.",
        button: "Acheter",
        secondary: "Livraison",
        collectionTitle: "Produits *populaires*",
        sections: {
          mosaic: {
            title: "Derniers arrivages",
            items: [
              { value: "Nouveau", title: "Running", text: "Légères et respirantes.", image: "" },
              { value: "Nouveau", title: "Lifestyle", text: "Pour tous les jours.", image: "" },
              { value: "Nouveau", title: "Sport", text: "Accroche et maintien.", image: "" },
              { value: "Nouveau", title: "Basket", text: "Amorti et style.", image: "" },
            ],
          },
          spotlight: { eyebrow: "Collection sport", title: "Bougez avec style", button: "Découvrir" },
        },
      },
      {
        eyebrow: "موسم جديد",
        title: "مجموعة الصيف وصلات",
        highlight: "مجموعة",
        text: "سبرديلات مريحة وزوينة، والتوصيل لجميع المدن.",
        button: "اشري",
        secondary: "التوصيل",
        collectionTitle: "المنتجات *المشهورة*",
        sections: {
          mosaic: {
            title: "آخر ما وصل",
            items: [
              { value: "جديد", title: "الجري", text: "خفيفة ومهوية.", image: "" },
              { value: "جديد", title: "يومي", text: "لكل نهار.", image: "" },
              { value: "جديد", title: "رياضة", text: "ثبات وراحة.", image: "" },
              { value: "جديد", title: "باسكيت", text: "راحة وستيل.", image: "" },
            ],
          },
          spotlight: { eyebrow: "مجموعة رياضية", title: "تحرك بستيل", button: "اكتشف" },
        },
      },
    ),
  },
  /* 10 · épure grise */
  {
    id: "s3-10",
    series: 3,
    folder: "10_Apple Watch",
    name: "Épure",
    niche: "Tech premium & accessoires",
    description: "Gris très clair et blanc : titre centré, grand produit, grille de tuiles grises.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f2f2f2",
      text: "#1d1d1f",
      muted: "#86868b",
      border: "#e5e5e5",
      primary: "#0071e3",
      accent: "#1d1d1f",
      dark: "#1d1d1f",
      heroBg: "#f2f2f2",
      heroText: "#1d1d1f",
      radius: 0,
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 600,
      headingTracking: "-0.02em",
    }),
    header: "center",
    hero: "center-product",
    card: "plain",
    categories: "gray-grid",
    promos: "cards",
    trust: "bar",
    layout: {
      header: "centered",
      card: "gray-round",
      faq: "center",
      footer: "minimal",
      shop: "topbar",
      product: "centered",
      page: "simple",
    },
    sections: ["hero", "categories", "products", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    showAnnouncement: false,
    copy: copy(
      {
        eyebrow: "Nouvelle collection",
        title: "L'essentiel, en mieux",
        highlight: "",
        text: "Disponible maintenant, livré partout au Maroc.",
        button: "Voir la boutique",
        secondary: "Livraison & paiement",
        collectionTitle: "Trois façons de trouver votre style",
        sections: { categories: { title: "Découvrez la collection" } },
      },
      {
        eyebrow: "المجموعة الجديدة",
        title: "الأساسي، بشكل أحسن",
        highlight: "",
        text: "متوفر دابا، والتوصيل لجميع المدن.",
        button: "شوف المتجر",
        secondary: "التوصيل والدفع",
        collectionTitle: "ثلاث طرق باش تلقا الستيل ديالك",
        sections: { categories: { title: "اكتشف المجموعة" } },
      },
    ),
  },
  /* 11 · sport noir & citron */
  {
    id: "s3-11",
    series: 3,
    folder: "11_MOVE Sportswear",
    name: "Élan Urbain",
    niche: "Sportswear & fitness",
    description: "Noir et vert fluo : photo de sport, titres très gras, icônes rondes, bande de photos.",
    theme: theme({
      bg: "#0a0a0a",
      surface: "#171717",
      text: "#ffffff",
      muted: "#a3a3a3",
      border: "rgba(255,255,255,0.1)",
      primary: "#c8ff2e",
      onPrimary: "#0a0a0a",
      accent: "#c8ff2e",
      onAccent: "#0a0a0a",
      dark: "#0a0a0a",
      heroBg: "#111111",
      heroText: "#ffffff",
      radius: 10,
      headingFont: "Archivo Black",
      bodyFont: "Inter",
      headingWeight: 400,
      headingCase: "uppercase",
      headingTracking: "-0.01em",
    }),
    header: "overlay",
    hero: "bold-photo",
    card: "plain",
    categories: "circle-icons",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "classic",
      card: "overlay",
      faq: "band",
      footer: "mega",
      shop: "banner",
      product: "stack",
      page: "banner",
    },
    sections: [
      "hero",
      "categories",
      "mosaic",
      "trust",
      "spotlight",
      "gallery",
      "products",
      "testimonials",
      "faq",
      "newsletter",
    ],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Sport & lifestyle",
        title: "Bougez mieux. Vivez plus fort.",
        highlight: "",
        text: "Des vêtements de sport pensés pour chaque mouvement.",
        button: "Voir les nouveautés",
        secondary: "Nos collections",
        collectionTitle: "Nouveautés",
        sections: {
          categories: { title: "" },
          mosaic: {
            items: [
              { value: "Femme", title: "Collection femme", text: "Force et style.", image: "" },
              { value: "Homme", title: "Collection homme", text: "Faite pour bouger.", image: "" },
              { value: "Nouveau", title: "Nouveautés", text: "Les dernières sorties.", image: "" },
            ],
          },
          spotlight: {
            title: "S'entraîner. Performer. Recommencer.",
            text: "Des tenues pour l'entraînement, la course et le quotidien.",
            button: "Voir la collection",
          },
          gallery: { title: "#EnMouvement", text: "Nos produits en action." },
        },
      },
      {
        eyebrow: "رياضة وأسلوب حياة",
        title: "تحرك أحسن. عيش أقوى.",
        highlight: "",
        text: "ملابس رياضية مصممة لكل حركة.",
        button: "شوف الجديد",
        secondary: "المجموعات",
        collectionTitle: "الجديد",
        sections: {
          categories: { title: "" },
          mosaic: {
            items: [
              { value: "نساء", title: "مجموعة النساء", text: "قوة وستيل.", image: "" },
              { value: "رجال", title: "مجموعة الرجال", text: "مصممة للحركة.", image: "" },
              { value: "جديد", title: "الجديد", text: "آخر ما خرج.", image: "" },
            ],
          },
          spotlight: {
            title: "تمرن. نجح. عاود.",
            text: "لبسة للتمرين، الجري والحياة اليومية.",
            button: "شوف المجموعة",
          },
          gallery: { title: "#فالحركة", text: "منتجاتنا فالحركة." },
        },
      },
    ),
  },
  /* 12 · brut orange */
  {
    id: "s3-12",
    series: 3,
    folder: "12_BRUTAL",
    name: "Brut Orange",
    niche: "Mode & concept store",
    description: "Blanc, noir et orange vif : typographie géante, lettre de couleur, bandeau numéroté, mosaïque.",
    theme: theme({
      bg: "#ffffff",
      surface: "#efefef",
      text: "#0a0a0a",
      muted: "#555555",
      border: "#0a0a0a",
      primary: "#0a0a0a",
      accent: "#ff4d00",
      dark: "#0a0a0a",
      heroBg: "#ffffff",
      heroText: "#0a0a0a",
      radius: 0,
      headingFont: "Anton",
      bodyFont: "Space Mono",
      headingWeight: 400,
      headingCase: "uppercase",
      headingTracking: "0",
    }),
    header: "split",
    hero: "brutal",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "numbered",
    layout: {
      header: "split",
      card: "editorial",
      faq: "numbered",
      footer: "split",
      shop: "sidebar",
      product: "panel",
      page: "split",
    },
    sections: ["hero", "trust", "newsletter", "mosaic", "products", "testimonials", "faq"],
    hiddenByDefault: ["testimonials"],
    showAnnouncement: false,
    copy: copy(
      {
        eyebrow: "Concept store",
        title: "On ne fait pas dans la moyenne.",
        highlight: "la moyenne.",
        text: "Des pièces fortes, choisies pour sortir du lot.",
        button: "Voir la collection",
        collectionTitle: "Sélection du moment",
        sections: {
          trust: { title: "Ce qu'on fait" },
          newsletter: {
            title: "Arrêtez de porter comme tout le monde",
            text: "Démarquez-vous. Écrivez-nous pour une commande ou un conseil.",
            button: "Nous écrire",
          },
          mosaic: {
            items: [
              { value: "01", title: "Pièces fortes", text: "Coupes et matières.", image: "" },
              { value: "02", title: "Nouveautés", text: "Chaque semaine.", image: "" },
              { value: "03", title: "Essentiels", text: "Les bases bien faites.", image: "" },
              { value: "04", title: "Accessoires", text: "Pour finir le look.", image: "" },
            ],
          },
        },
      },
      {
        eyebrow: "كونسيبت ستور",
        title: "ما كنديروش العادي.",
        highlight: "العادي.",
        text: "قطع قوية، مختارة باش تبان.",
        button: "شوف المجموعة",
        collectionTitle: "اختيار دابا",
        sections: {
          trust: { title: "شنو كنديرو" },
          newsletter: { title: "ما تلبسش بحال كولشي", text: "تميز. كتب لينا للطلب ولا النصيحة.", button: "كتب لينا" },
          mosaic: {
            items: [
              { value: "01", title: "قطع قوية", text: "قصات وخامات.", image: "" },
              { value: "02", title: "الجديد", text: "كل سيمانة.", image: "" },
              { value: "03", title: "الأساسيات", text: "مديورين مزيان.", image: "" },
              { value: "04", title: "إكسسوارات", text: "باش يكمل اللوك.", image: "" },
            ],
          },
        },
      },
    ),
  },
  /* 13 · tech blanche */
  {
    id: "s3-13",
    series: 3,
    folder: "13_Victory Earbuds",
    name: "Victoire Tech",
    niche: "Audio & gaming",
    description: "Blanc nacré et noir : titre techno, icônes de caractéristiques, bandeau technique, cartes chiffres.",
    theme: theme({
      bg: "#f7f7f7",
      surface: "#ffffff",
      text: "#0b0b0b",
      muted: "#6b6b6b",
      border: "#e4e4e4",
      primary: "#0b0b0b",
      accent: "#0b0b0b",
      dark: "#0b0b0b",
      heroBg: "#eeeeee",
      heroText: "#0b0b0b",
      radius: 6,
      headingFont: "Michroma",
      bodyFont: "Inter",
      headingWeight: 400,
      headingCase: "uppercase",
      headingTracking: "0.02em",
    }),
    header: "split",
    hero: "spec-tech",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "bar",
    layout: {
      header: "classic",
      card: "framed",
      faq: "split",
      footer: "bar",
      shop: "sidebar",
      product: "split",
      page: "simple",
    },
    sections: ["hero", "specs", "showcase", "bento", "products", "trust", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Sans fil",
        title: "Conçu pour gagner",
        highlight: "",
        text: "Des écouteurs et accessoires gaming choisis pour la performance et la précision.",
        button: "Acheter",
        collectionTitle: "Nos produits",
        sections: {
          hero: {
            items: [
              { title: "Faible latence", text: "Pour le jeu" },
              { title: "Double haut-parleur", text: "Son riche" },
              { title: "Grande autonomie", text: "Toute la journée" },
              { title: "Micro clair", text: "Appels nets" },
            ],
          },
          specs: {
            title: "Caractéristiques",
            items: [
              { title: "Connexion", value: "Bluetooth" },
              { title: "Usage", value: "Jeu & musique" },
              { title: "Paiement", value: "À la livraison" },
              { title: "Livraison", value: "Partout au Maroc" },
              { title: "Échange", value: "Facile" },
            ],
          },
          showcase: {
            eyebrow: "Performance",
            title: "Réactif comme vous",
            text: "Entendez chaque détail en temps réel et réagissez plus vite.",
            button: "En savoir plus",
          },
          bento: {
            items: [
              { title: "Son puissant", text: "Basses profondes et aigus clairs.", image: "" },
              { title: "Micro intelligent", text: "Votre voix, sans bruit autour.", image: "" },
              { value: "{products}", title: "Produits disponibles", text: "Sélectionnés pour vous." },
              { title: "Compatible partout", text: "Téléphone, PC et consoles." },
            ],
          },
        },
      },
      {
        eyebrow: "بلا خيط",
        title: "مصمم باش تربح",
        highlight: "",
        text: "سماعات وإكسسوارات ديال الألعاب مختارة على حساب الأداء والدقة.",
        button: "اشري",
        collectionTitle: "المنتجات ديالنا",
        sections: {
          hero: {
            items: [
              { title: "تأخير ضعيف", text: "للألعاب" },
              { title: "سماعتين", text: "صوت غني" },
              { title: "بطارية طويلة", text: "طول النهار" },
              { title: "ميكرو واضح", text: "مكالمات صافية" },
            ],
          },
          specs: {
            title: "المميزات",
            items: [
              { title: "الاتصال", value: "بلوتوث" },
              { title: "الاستعمال", value: "ألعاب وموسيقى" },
              { title: "الدفع", value: "عند الاستلام" },
              { title: "التوصيل", value: "لجميع المدن" },
              { title: "التبديل", value: "ساهل" },
            ],
          },
          showcase: { eyebrow: "أداء", title: "سريع بحالك", text: "سمع كل تفصيلة وتفاعل بسرعة.", button: "عرف كثر" },
          bento: {
            items: [
              { title: "صوت قوي", text: "باس عميق وصوت صافي.", image: "" },
              { title: "ميكرو ذكي", text: "صوتك بلا ضجيج.", image: "" },
              { value: "{products}", title: "منتج متوفر", text: "مختارة ليك." },
              { title: "متوافق مع كلشي", text: "تيليفون، PC وكونسول." },
            ],
          },
        },
      },
    ),
  },
  /* 14 · luxe marine */
  {
    id: "s3-14",
    series: 3,
    folder: "14_SHOPLUXE",
    name: "Luxe Marine",
    niche: "Boutique généraliste",
    description: "Bleu marine et camel : bannière claire avec accent manuscrit, pastille promo, bandeau 3 couleurs.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f5f3f0",
      text: "#0f1b33",
      muted: "#6b7280",
      border: "#e7e3dc",
      primary: "#0f1b33",
      accent: "#0f1b33",
      dark: "#0f1b33",
      heroBg: "#f5efe8",
      heroText: "#0f1b33",
      radius: 6,
      headingFont: "Roboto",
      bodyFont: "Roboto",
      scriptFont: "Dancing Script",
      headingWeight: 800,
      headingCase: "uppercase",
    }),
    header: "split",
    hero: "badge-split",
    card: "plain",
    categories: "square-tiles",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "classic",
      card: "outline-cart",
      faq: "cards",
      footer: "mega",
      shop: "topbar",
      product: "split",
      page: "banner",
    },
    sections: ["hero", "categories", "products", "mosaic", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Bienvenue",
        title: "Tout. Pour tout le monde.",
        highlight: "",
        text: "Une large sélection de produits de qualité, choisis pour vous.",
        button: "Acheter",
        secondary: "Nos collections",
        collectionTitle: "Tendances",
        sections: {
          hero: { items: [{ title: "Qualité et petits prix" }, { value: "Nouveau", title: "chaque semaine" }] },
          categories: { title: "Parcourir par catégorie" },
          mosaic: {
            items: [
              { value: "Livraison", title: "Partout au Maroc", text: "Voir la boutique", image: "" },
              { value: "Offre", title: "Paiement à la livraison", text: "Commandez sans carte", image: "" },
              { value: "Service", title: "Conseil sur WhatsApp", text: "Nous écrire", image: "" },
            ],
          },
        },
      },
      {
        eyebrow: "مرحبا",
        title: "كلشي. لكل واحد.",
        highlight: "",
        text: "اختيار واسع ديال منتجات ديال الجودة، مختارة ليك.",
        button: "اشري",
        secondary: "المجموعات",
        collectionTitle: "الرائج",
        sections: {
          hero: { items: [{ title: "جودة وأثمنة مزيانة" }, { value: "جديد", title: "كل سيمانة" }] },
          categories: { title: "تصفح حسب التصنيف" },
          mosaic: {
            items: [
              { value: "التوصيل", title: "لجميع المدن", text: "شوف المتجر", image: "" },
              { value: "عرض", title: "الدفع عند الاستلام", text: "اطلب بلا بطاقة", image: "" },
              { value: "خدمة", title: "نصيحة فواتساب", text: "كتب لينا", image: "" },
            ],
          },
        },
      },
    ),
  },
  /* 15 · gris studio */
  {
    id: "s3-15",
    series: 3,
    folder: "15_Commerce X",
    name: "Gris Studio",
    niche: "Gadgets & accessoires",
    description: "Niveaux de gris : logo centré, produit à droite, grandes cartes arrondies, catalogue avec filtres.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f5f5f5",
      text: "#111111",
      muted: "#7b7b7b",
      border: "#e6e6e6",
      primary: "#111111",
      accent: "#111111",
      dark: "#111111",
      heroBg: "#f4f4f4",
      heroText: "#111111",
      radius: 28,
      headingFont: "Space Grotesk",
      bodyFont: "Space Grotesk",
      headingWeight: 400,
      headingTracking: "-0.02em",
    }),
    header: "center",
    hero: "minimal-gray",
    card: "plain",
    categories: "big-cards",
    promos: "cards",
    trust: "bar",
    layout: {
      header: "centered",
      card: "gray-round",
      faq: "split",
      footer: "columns",
      shop: "topbar",
      product: "stack",
      page: "split",
    },
    sections: ["hero", "categories", "catalog", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    showAnnouncement: false,
    copy: copy(
      {
        eyebrow: "Gadgets & accessoires",
        title: "Des gadgets et accessoires de qualité",
        highlight: "",
        text: "Une sélection courte et soignée, livrée partout au Maroc.",
        button: "Voir les produits",
        secondary: "À propos",
        collectionTitle: "Tous les produits",
        sections: { categories: { title: "" }, catalog: { title: "" } },
      },
      {
        eyebrow: "أجهزة وإكسسوارات",
        title: "أجهزة وإكسسوارات ديال الجودة",
        highlight: "",
        text: "اختيار قصير ومتقن، والتوصيل لجميع المدن.",
        button: "شوف المنتجات",
        secondary: "شكون حنا",
        collectionTitle: "جميع المنتجات",
        sections: { categories: { title: "" }, catalog: { title: "" } },
      },
    ),
  },
  /* 16 · orange nuit */
  {
    id: "s3-16",
    series: 3,
    folder: "16_Gander",
    name: "Orange Nuit",
    niche: "Gaming & électronique",
    description: "Noir et dégradé orange : mot géant derrière la photo, carte contact, chiffres en police pixel.",
    theme: theme({
      bg: "#050505",
      surface: "#111111",
      text: "#f5f5f5",
      muted: "#8f8f8f",
      border: "rgba(255,255,255,0.1)",
      primary: "#ff5a1f",
      accent: "#ff5a1f",
      dark: "#0a0a0a",
      heroBg: "#1b0904",
      heroText: "#ffffff",
      radius: 22,
      headingFont: "Inter Tight",
      bodyFont: "Inter",
      headingWeight: 500,
      headingTracking: "-0.04em",
    }),
    header: "overlay",
    hero: "giant-behind",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "icons",
    statement: "inline",
    layout: {
      header: "menu",
      card: "glass",
      faq: "band",
      footer: "wordmark",
      shop: "banner",
      product: "centered",
      page: "split",
    },
    sections: ["hero", "statement", "products", "marquee", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Gaming & audio",
        title: "Jouez plus loin",
        highlight: "plus loin",
        text: "Casques, manettes et accessoires choisis pour les joueurs, livrés partout au Maroc.",
        button: "Commencer",
        secondary: "Nous écrire",
        collectionTitle: "Équipement",
        sections: {
          statement: {
            eyebrow: "À propos",
            title: "Nous sélectionnons du matériel fiable",
            text: "pour jouer mieux, plus longtemps et sans prise de tête.",
            items: statsFr,
          },
          marquee: {
            items: [
              { title: "Gaming" },
              { title: "Audio" },
              { title: "Accessoires" },
              { title: "Paiement à la livraison" },
            ],
          },
        },
      },
      {
        eyebrow: "ألعاب وصوت",
        title: "لعب كثر",
        highlight: "كثر",
        text: "كاسك، مانيطات وإكسسوارات مختارة للاعبين، والتوصيل لجميع المدن.",
        button: "بدا",
        secondary: "كتب لينا",
        collectionTitle: "المعدات",
        sections: {
          statement: {
            eyebrow: "شكون حنا",
            title: "كنختارو معدات موثوقة",
            text: "باش تلعب أحسن وكثر وبلا صداع.",
            items: statsAr,
          },
          marquee: {
            items: [{ title: "ألعاب" }, { title: "صوت" }, { title: "إكسسوارات" }, { title: "الدفع عند الاستلام" }],
          },
        },
      },
    ),
  },
  /* 17 · minuit montres */
  {
    id: "s3-17",
    series: 3,
    folder: "17_TINTON Watches",
    name: "Minuit Montres",
    niche: "Montres & horlogerie",
    description: "Noir nuit et vert d'eau : photo de nuit, mosaïque de 5 bannières, collections en cartes sombres.",
    theme: theme({
      bg: "#0c0c0c",
      surface: "#161616",
      text: "#f2f2f2",
      muted: "#9a9a9a",
      border: "rgba(255,255,255,0.08)",
      primary: "#7fd6b4",
      onPrimary: "#0c0c0c",
      accent: "#ffffff",
      onAccent: "#0c0c0c",
      dark: "#060606",
      heroBg: "#060606",
      heroText: "#ffffff",
      radius: 2,
      headingFont: "Jost",
      bodyFont: "Jost",
      headingWeight: 500,
      headingCase: "uppercase",
      headingTracking: "0.02em",
    }),
    header: "overlay",
    hero: "night-photo",
    card: "plain",
    categories: "collection",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "classic",
      card: "minimal",
      faq: "center",
      footer: "mega",
      shop: "sidebar",
      product: "panel",
      page: "simple",
    },
    sections: ["hero", "mosaic", "trust", "categories", "spotlight", "products", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle édition",
        title: "Votre nouvelle montre vous attend",
        highlight: "",
        text: "Des montres choisies avec soin, livrées partout au Maroc.",
        button: "Acheter",
        collectionTitle: "Nos montres",
        sections: {
          mosaic: {
            items: [
              { value: "Édition limitée", title: "La montre du moment", text: "", image: "" },
              { value: "Classique", title: "Collection de grandes marques", text: "", image: "" },
              { value: "Offre", title: "Paiement à la livraison", text: "", image: "" },
              { value: "Collection", title: "Acier et élégance", text: "", image: "" },
              { value: "Saison", title: "Nouvelle collection", text: "", image: "" },
            ],
          },
          categories: { eyebrow: "Collections", title: "Acheter par collection" },
          spotlight: { eyebrow: "Collection", title: "Des montres de caractère", button: "Acheter" },
        },
      },
      {
        eyebrow: "إصدار جديد",
        title: "الساعة الجديدة ديالك كتسناك",
        highlight: "",
        text: "ساعات مختارة بعناية، والتوصيل لجميع المدن.",
        button: "اشري",
        collectionTitle: "الساعات ديالنا",
        sections: {
          mosaic: {
            items: [
              { value: "إصدار محدود", title: "ساعة اللحظة", text: "", image: "" },
              { value: "كلاسيك", title: "مجموعة ماركات كبار", text: "", image: "" },
              { value: "عرض", title: "الدفع عند الاستلام", text: "", image: "" },
              { value: "مجموعة", title: "ستيل وأناقة", text: "", image: "" },
              { value: "موسم", title: "مجموعة جديدة", text: "", image: "" },
            ],
          },
          categories: { eyebrow: "المجموعات", title: "تسوق حسب المجموعة" },
          spotlight: { eyebrow: "مجموعة", title: "ساعات عندها شخصية", button: "اشري" },
        },
      },
    ),
  },
  /* 18 · rouge tech */
  {
    id: "s3-18",
    series: 3,
    folder: "18_TechVerse",
    name: "Rouge Tech",
    niche: "High-tech & objets connectés",
    description:
      "Blanc et rouge : grande recherche, carte hero avec panneau rouge, petites cartes catégories, idées en images.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f6f6f7",
      text: "#111111",
      muted: "#6b7280",
      border: "#ececee",
      primary: "#e0262f",
      accent: "#e0262f",
      dark: "#111111",
      heroBg: "#f6f6f7",
      heroText: "#111111",
      radius: 16,
      headingFont: "Plus Jakarta Sans",
      bodyFont: "Inter",
      headingWeight: 800,
    }),
    header: "split",
    hero: "red-panel",
    card: "plain",
    categories: "chip-cards",
    promos: "cards",
    trust: "bar",
    layout: {
      header: "search",
      card: "classic",
      faq: "cards",
      footer: "bar",
      shop: "sidebar",
      product: "centered",
      page: "banner",
    },
    sections: ["hero", "categories", "products", "trust", "gallery", "deals", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Découvrir. Acheter. Évoluer.",
        title: "Les derniers gadgets tech",
        highlight: "gadgets tech",
        text: "Des produits high-tech qui simplifient votre quotidien.",
        button: "Acheter",
        secondary: "Voir la collection",
        collectionTitle: "Tendances",
        sections: {
          hero: { items: [{ title: "Nouveautés" }] },
          categories: { title: "" },
          gallery: { title: "Des idées pour votre prochain achat", text: "" },
          deals: { eyebrow: "Offres exclusives", title: "Offres du jour" },
        },
      },
      {
        eyebrow: "اكتشف. اشري. طور.",
        title: "آخر الأجهزة التقنية",
        highlight: "الأجهزة التقنية",
        text: "منتجات تقنية كتسهل عليك النهار.",
        button: "اشري",
        secondary: "شوف المجموعة",
        collectionTitle: "الرائج",
        sections: {
          hero: { items: [{ title: "جديد" }] },
          categories: { title: "" },
          gallery: { title: "أفكار للشرا الجاي", text: "" },
          deals: { eyebrow: "عروض حصرية", title: "عروض اليوم" },
        },
      },
    ),
  },
  /* 19 · lavande */
  {
    id: "s3-19",
    series: 3,
    folder: "19_fabrid Store",
    name: "Lavande",
    niche: "Lifestyle & objets",
    description: "Blanc et violet lavande : nom de la boutique géant sur l'image, cartes pastel, prix en pastille.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f4f0fd",
      text: "#141414",
      muted: "#6b6b75",
      border: "#ece7f8",
      primary: "#6d3fd8",
      accent: "#6d3fd8",
      dark: "#1a0f3d",
      heroBg: "#dcd7f2",
      heroText: "#ffffff",
      radius: 18,
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 600,
      headingTracking: "-0.03em",
    }),
    header: "split",
    hero: "brand-giant",
    card: "plain",
    categories: "lavender",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "pill",
      card: "price-badge",
      faq: "split",
      footer: "centered",
      shop: "banner",
      product: "split",
      page: "simple",
    },
    sections: ["hero", "categories", "products", "spotlight", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    showAnnouncement: false,
    copy: copy(
      {
        eyebrow: "Store",
        title: "Des objets qui embellissent le quotidien",
        highlight: "",
        text: "Une sélection douce et colorée pour la maison.",
        button: "Acheter",
        collectionTitle: "Nos coups de cœur",
        collectionSubtitle: "Les favoris de la boutique.",
        sections: {
          hero: { items: [{ value: "{products}", title: "Produits" }] },
          categories: { title: "Catégories à la une", text: "Achetez par catégorie en quelques secondes." },
          spotlight: { eyebrow: "Offre", title: "Les essentiels du quotidien", button: "Découvrir" },
        },
      },
      {
        eyebrow: "متجر",
        title: "حوايج كيزينو النهار",
        highlight: "",
        text: "اختيار ناعم وملون للدار.",
        button: "اشري",
        collectionTitle: "اللي عجبونا",
        collectionSubtitle: "المفضلين فالمتجر.",
        sections: {
          hero: { items: [{ value: "{products}", title: "منتج" }] },
          categories: { title: "تصنيفات مميزة", text: "تسوق حسب التصنيف فثواني." },
          spotlight: { eyebrow: "عرض", title: "أساسيات كل نهار", button: "اكتشف" },
        },
      },
    ),
  },
  /* 20 · braise */
  {
    id: "s3-20",
    series: 3,
    folder: "20_Formix",
    name: "Braise",
    niche: "Mode homme & lifestyle",
    description: "Noir et orange braise : disque orange derrière la photo, barre de chiffres, services en cartes.",
    theme: theme({
      bg: "#0b0b0b",
      surface: "#151515",
      text: "#f2f2f2",
      muted: "#9a9a9a",
      border: "rgba(255,255,255,0.09)",
      primary: "#ff5a1f",
      accent: "#ff5a1f",
      dark: "#070707",
      heroBg: "#0b0b0b",
      heroText: "#ffffff",
      radius: 14,
      headingFont: "Manrope",
      bodyFont: "Manrope",
      headingWeight: 600,
      headingTracking: "-0.03em",
    }),
    header: "overlay",
    hero: "orange-orb",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "pill",
      card: "glass",
      faq: "split",
      footer: "cta",
      shop: "topbar",
      product: "panel",
      page: "banner",
    },
    sections: ["hero", "services", "products", "marquee", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle saison",
        title: "Un style qui se remarque",
        highlight: "qui se remarque",
        text: "Des vêtements et accessoires choisis pour leur coupe, leur matière et leur caractère.",
        button: "Acheter",
        secondary: "Voir la collection",
        collectionTitle: "Pièces qui parlent d'elles-mêmes",
        sections: {
          hero: { items: [{ value: "{products}+", title: "Produits" }, ...statsFr] },
          services: {
            eyebrow: "Ce que nous faisons",
            title: "Un style qui vous ressemble",
            items: [
              { title: "Coupes soignées", text: "Des pièces qui tombent bien." },
              { title: "Matières choisies", text: "Confort et durabilité." },
              { title: "Conseil taille", text: "On vous aide à choisir." },
              { title: "Livraison rapide", text: "Partout au Maroc." },
              { title: "Échange facile", text: "Un souci ? On trouve une solution." },
              { value: "100%", title: "Paiement à la livraison", text: "Vous payez à la réception." },
            ],
          },
          marquee: {
            items: [
              { title: "Nouveautés" },
              { title: "Essentiels" },
              { title: "Accessoires" },
              { title: "Livraison partout au Maroc" },
            ],
          },
        },
      },
      {
        eyebrow: "موسم جديد",
        title: "ستيل كيبان",
        highlight: "كيبان",
        text: "ملابس وإكسسوارات مختارة على حساب القصة، الخامة والشخصية.",
        button: "اشري",
        secondary: "شوف المجموعة",
        collectionTitle: "قطع كتهضر على راسها",
        sections: {
          hero: { items: [{ value: "{products}+", title: "منتج" }, ...statsAr] },
          services: {
            eyebrow: "شنو كنديرو",
            title: "ستيل كيشبهك",
            items: [
              { title: "قصات متقنة", text: "قطع كتجي مزيانة." },
              { title: "خامات مختارة", text: "راحة وجودة." },
              { title: "نصيحة فالقياس", text: "نعاونوك تختار." },
              { title: "توصيل سريع", text: "لجميع المدن." },
              { title: "تبديل ساهل", text: "شي مشكل؟ كنلقاو الحل." },
              { value: "100%", title: "الدفع عند الاستلام", text: "خلص ملي توصلك." },
            ],
          },
          marquee: {
            items: [
              { title: "الجديد" },
              { title: "الأساسيات" },
              { title: "إكسسوارات" },
              { title: "التوصيل لجميع المدن" },
            ],
          },
        },
      },
    ),
  },
];
