// Série 2 — 15 templates de boutique, un par dossier de la série (16 à 30).
// Les maquettes servent de référence de mise en page, de couleurs et de typographie ;
// textes et noms sont propres à LandPro, les images affichées sont celles des produits.
import type { StoreTemplate, SxCopy, SxTheme } from "./types";
import { SHARED_AR, SHARED_FR, withShared } from "./shared-copy";

const base: Omit<SxTheme, "primary" | "accent" | "heroBg" | "heroText"> = {
  bg: "#ffffff",
  surface: "#ffffff",
  text: "#111111",
  muted: "#6b7280",
  border: "#e5e7eb",
  onPrimary: "#ffffff",
  onAccent: "#ffffff",
  dark: "#111111",
  onDark: "#ffffff",
  radius: 14,
  headingFont: "Inter",
  bodyFont: "Inter",
  headingWeight: 600,
};
const theme = (t: Partial<SxTheme> & Pick<SxTheme, "primary" | "accent" | "heroBg" | "heroText">): SxTheme => ({
  ...base,
  ...t,
});
const copy = (fr: SxCopy, ar: SxCopy) => ({
  fr: { ...fr, sections: withShared(SHARED_FR, fr.sections) },
  ar: { ...ar, sections: withShared(SHARED_AR, ar.sections) },
});

export const SERIE_2: StoreTemplate[] = [
  {
    id: "s2-01",
    series: 2,
    folder: "16_Home arch",
    name: "Habitat Clair",
    niche: "Maison, déco & mobilier",
    description: "Blanc lumineux, grande image et miniatures, barre de recherche par catégorie.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f6f6f4",
      primary: "#111111",
      accent: "#111111",
      heroBg: "#ffffff",
      heroText: "#111111",
      radius: 22,
      headingFont: "Manrope",
      bodyFont: "Manrope",
      headingWeight: 500,
      headingTracking: "-0.03em",
    }),
    header: "split",
    hero: "gallery",
    card: "soft",
    categories: "tiles",
    promos: "split",
    trust: "icons",
    layout: {
      header: "pill",
      card: "framed",
      faq: "split",
      footer: "columns",
      shop: "sidebar",
      product: "split",
      page: "simple",
    },
    sections: ["hero", "showcase", "products", "categories", "testimonials", "spotlight", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle collection maison",
        title: "Des intérieurs qui vous ressemblent, enfin",
        highlight: "vous ressemblent",
        text: "Des pièces choisies avec soin, un conseil sur WhatsApp et une livraison partout au Maroc.",
        button: "Rechercher",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Pièces choisies pour vous",
        collectionSubtitle: "Les produits les plus aimés de la boutique.",
        sections: {
          showcase: {
            title: "Composer un intérieur beau et simple",
            text: "Propre, durable, facile à vivre : chaque produit est sélectionné pour son confort et sa qualité.",
            button: "Voir la boutique",
            items: [{ title: "Qualité contrôlée" }, { title: "Conseil personnalisé" }, { title: "Échange facile" }],
          },
          spotlight: {
            title: "Trouvez la pièce qui manque à votre intérieur",
            button: "Découvrir",
          },
        },
      },
      {
        eyebrow: "مجموعة جديدة للدار",
        title: "داخل كيشبهك، أخيرا",
        highlight: "كيشبهك",
        text: "قطع مختارة بعناية، نصيحة فواتساب وتوصيل لجميع المدن.",
        button: "قلب",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "قطع مختارة ليك",
        collectionSubtitle: "المنتجات اللي عجبات الزبناء أكثر.",
        sections: {
          showcase: {
            title: "دار زوينة وبسيطة",
            text: "نقي، كيدوم وساهل فالعيش: كل منتج مختار على حساب الراحة والجودة.",
            button: "شوف المتجر",
            items: [{ title: "جودة مراقبة" }, { title: "نصيحة شخصية" }, { title: "تبديل سهل" }],
          },
          spotlight: { title: "لقا القطعة اللي ناقصة فدارك", button: "اكتشف" },
        },
      },
    ),
  },
  {
    id: "s2-02",
    series: 2,
    folder: "17_Cousmi hand",
    name: "Peau Dorée",
    niche: "Soins & cosmétique naturelle",
    description: "Photos chaudes, vert olive, titres serif et carte produit flottante.",
    theme: theme({
      bg: "#fbf8f3",
      surface: "#ffffff",
      text: "#2a2116",
      muted: "#7b6b58",
      border: "#ece3d6",
      primary: "#5f6b2a",
      accent: "#5f6b2a",
      dark: "#3b2a1a",
      heroBg: "linear-gradient(135deg,#d9a676,#a8714a)",
      heroText: "#ffffff",
      radius: 20,
      headingFont: "Fraunces",
      bodyFont: "Inter",
      headingWeight: 400,
    }),
    header: "split",
    hero: "warm-photo",
    card: "soft",
    categories: "circles",
    promos: "cards",
    trust: "bar",
    layout: {
      header: "classic",
      card: "centered",
      faq: "center",
      footer: "wordmark",
      shop: "topbar",
      product: "panel",
      page: "banner",
    },
    sections: ["hero", "showcase", "products", "promos", "testimonials", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Soins naturels",
        title: "Un soin qui fait autant de bien qu'il est beau",
        text: "Des formules simples et efficaces, inspirées de la nature, pour une peau nourrie chaque jour.",
        button: "Voir la collection",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Nos meilleures ventes",
        collectionSubtitle: "Les soins préférés de nos clientes.",
        sections: {
          showcase: {
            eyebrow: "Notre conviction",
            title: "Garder une peau hydratée et nourrie",
            text: "Le soin doit être simple, efficace et inspiré par la nature : des extraits botaniques et une texture agréable.",
            button: "Découvrir",
          },
          promos: {
            items: [
              { title: "Chaque peau mérite le bon soin", text: "Trouvez la routine adaptée" },
              { title: "Des ingrédients propres", text: "Une peau saine au quotidien" },
            ],
          },
        },
      },
      {
        eyebrow: "عناية طبيعية",
        title: "عناية كتفرح البشرة وكتبان زوينة",
        text: "تركيبات بسيطة وفعالة، مستوحاة من الطبيعة، لبشرة مغذية كل نهار.",
        button: "شوف المجموعة",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "الأكثر مبيعا",
        collectionSubtitle: "منتجات العناية المفضلة عند زبوناتنا.",
        sections: {
          showcase: {
            eyebrow: "القناعة ديالنا",
            title: "بشرة مرطبة ومغذية",
            text: "العناية خاصها تكون بسيطة وفعالة ومستوحاة من الطبيعة.",
            button: "اكتشف",
          },
          promos: {
            items: [
              { title: "كل بشرة كتستاهل العناية المناسبة", text: "لقا الروتين اللي يناسبك" },
              { title: "مكونات نقية", text: "بشرة صحية كل نهار" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s2-03",
    series: 2,
    folder: "18_Sport",
    name: "Camp Élan",
    niche: "Sport & équipement",
    description: "Ciel bleu doux, jauge de performance, sections aérées et grand logotype final.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f5f6f8",
      primary: "#0f3b2e",
      accent: "#111111",
      dark: "#0f3b2e",
      heroBg: "linear-gradient(180deg,#a9bfe8 0%,#c9d6ee 100%)",
      heroText: "#ffffff",
      radius: 16,
      headingFont: "Manrope",
      bodyFont: "Manrope",
      headingWeight: 600,
    }),
    header: "split",
    hero: "sky-left",
    card: "plain",
    categories: "tiles",
    promos: "split",
    trust: "numbered",
    layout: {
      header: "classic",
      card: "minimal",
      faq: "split",
      footer: "wordmark",
      shop: "topbar",
      product: "split",
      page: "simple",
    },
    sections: ["hero", "bento", "products", "trust", "showcase", "categories", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Équipement sportif",
        title: "Trouvez votre équipement. Élevez votre niveau.",
        text: "Du matériel fiable pour s'entraîner, progresser et se dépasser, livré partout au Maroc.",
        button: "Voir les produits",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Pour chaque sport",
        collectionSubtitle: "Comparez, choisissez, commandez simplement.",
        sections: {
          bento: {
            title: "Une sélection pensée pour la performance",
            items: [
              { title: "Produits disponibles", value: "{products}", text: "Une gamme qui évolue chaque mois." },
              { title: "Testé sur le terrain", text: "Des produits choisis pour leur tenue." },
              { title: "Catégories", value: "{categories}", text: "Pour tous les niveaux." },
            ],
          },
          trust: {
            title: "Un parcours simple jusqu'à votre équipement",
            items: [
              { title: "Choisissez", text: "Comparez les produits et leurs caractéristiques." },
              { title: "Confirmez", text: "Nous vous appelons pour valider la commande." },
              { title: "Entraînez-vous", text: "Recevez et payez à la livraison." },
            ],
          },
          showcase: {
            eyebrow: "Pourquoi nous",
            title: "Pourquoi les sportifs nous choisissent",
            text: "Des produits sélectionnés pour leur qualité, des conseils honnêtes et un service rapide.",
            items: [
              { title: "Qualité vérifiée" },
              { title: "Conseils de pratiquants" },
              { title: "Prix clairs, sans surprise" },
            ],
          },
        },
      },
      {
        eyebrow: "تجهيزات رياضية",
        title: "لقا التجهيز ديالك. طلع بالمستوى ديالك.",
        text: "معدات مضمونة للتمرين والتقدم، كتوصلك لجميع المدن.",
        button: "شوف المنتجات",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "لكل رياضة",
        collectionSubtitle: "قارن، اختار، وطلب بسهولة.",
        sections: {
          bento: {
            title: "اختيار مصمم للأداء",
            items: [
              { title: "منتج متوفر", value: "{products}", text: "تشكيلة كتجدد كل شهر." },
              { title: "مجرب فالتيران", text: "منتجات مختارة على حساب الجودة." },
              { title: "تصنيفات", value: "{categories}", text: "لجميع المستويات." },
            ],
          },
          trust: {
            title: "طريق ساهل حتى للتجهيز ديالك",
            items: [
              { title: "اختار", text: "قارن المنتجات والمميزات ديالها." },
              { title: "أكد", text: "كنعيطو ليك باش نأكدو الطلب." },
              { title: "تمرن", text: "توصل وخلص عند الاستلام." },
            ],
          },
          showcase: {
            eyebrow: "علاش حنا",
            title: "علاش الرياضيين كيختارونا",
            text: "منتجات مختارة على حساب الجودة، نصائح صادقة وخدمة سريعة.",
            items: [{ title: "جودة مضمونة" }, { title: "نصائح ممارسين" }, { title: "أثمنة واضحة" }],
          },
        },
      },
    ),
  },
  {
    id: "s2-04",
    series: 2,
    folder: "19_Conference",
    name: "Vague Verte",
    niche: "Tech, gadgets & bureau",
    description: "Vagues vert tendre, titre géant bicolore, cartes chiffres et bouton vert citron.",
    theme: theme({
      bg: "#f4f5f2",
      surface: "#ffffff",
      text: "#0f1a12",
      primary: "#7a9a3c",
      accent: "#c9f25d",
      onAccent: "#0f1a12",
      dark: "#4f6b3c",
      heroBg: "linear-gradient(160deg,#eef1e6,#dfe8cf)",
      heroText: "#0f1a12",
      radius: 18,
      headingFont: "Manrope",
      bodyFont: "Inter",
      headingWeight: 600,
    }),
    header: "split",
    hero: "freeflow",
    card: "boxed",
    categories: "pills",
    promos: "banner",
    trust: "numbered",
    layout: {
      header: "pill",
      card: "framed",
      faq: "cards",
      footer: "wordmark",
      shop: "topbar",
      product: "centered",
      page: "split",
    },
    sections: ["hero", "showcase", "trust", "spotlight", "products", "bento", "categories", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouveautés tech",
        title: "Simplifiez chaque journée",
        highlight: "chaque journée",
        text: "Des gadgets malins et des accessoires de bureau qui font gagner du temps, livrés partout au Maroc.",
        button: "Voir les produits",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Tout ce qu'il faut pour être efficace",
        collectionSubtitle: "Des produits utiles, testés et faciles à prendre en main.",
        sections: {
          showcase: {
            eyebrow: "// à propos",
            title: "Moins de complications, plus d'efficacité au quotidien",
            text: "Nous sélectionnons des produits pratiques qui s'intègrent à vos habitudes, sans les changer.",
            button: "En savoir plus",
          },
          trust: {
            title: "Ce qui nous rend différents",
            items: [
              { title: "Produits testés", text: "Chaque article est vérifié avant d'être proposé." },
              { title: "Conseil rapide", text: "Une question ? Réponse sur WhatsApp." },
              { title: "Paiement à la livraison", text: "Aucune carte bancaire demandée." },
              { title: "Échange facile", text: "Un souci ? On trouve une solution." },
            ],
          },
          spotlight: { title: "Prêt à passer à la vitesse supérieure ?", button: "Commander" },
          bento: {
            title: "En quelques chiffres",
            items: [
              { title: "Produits", value: "{products}" },
              { title: "Catégories", value: "{categories}" },
              { title: "Paiement à la livraison", value: "100%" },
            ],
          },
        },
      },
      {
        eyebrow: "جديد التكنولوجيا",
        title: "سهل كل نهار",
        highlight: "كل نهار",
        text: "أدوات ذكية وإكسسوارات مكتب كيربحوك الوقت، كيوصلو لجميع المدن.",
        button: "شوف المنتجات",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "كلشي اللي خاصك باش تكون فعال",
        collectionSubtitle: "منتجات مفيدة، مجربة وساهلة فالاستعمال.",
        sections: {
          showcase: {
            eyebrow: "// علينا",
            title: "تعقيد قليل، فعالية أكثر",
            text: "كنختارو منتجات عملية كتدخل فالعادات ديالك بلا ما تبدلها.",
            button: "عرف أكثر",
          },
          trust: {
            title: "علاش حنا مختلفين",
            items: [
              { title: "منتجات مجربة", text: "كل منتج كيتشاف قبل ما يتعرض." },
              { title: "نصيحة سريعة", text: "عندك سؤال؟ جواب فواتساب." },
              { title: "الدفع عند الاستلام", text: "بلا بطاقة بنكية." },
              { title: "تبديل سهل", text: "إلا كان شي مشكل كنلقاو الحل." },
            ],
          },
          spotlight: { title: "واجد تطلع للمستوى الجاي؟", button: "طلب دابا" },
          bento: {
            title: "بالأرقام",
            items: [
              { title: "منتج", value: "{products}" },
              { title: "تصنيفات", value: "{categories}" },
              { title: "الدفع عند الاستلام", value: "100%" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s2-05",
    series: 2,
    folder: "20_architc",
    name: "Allure Résidence",
    niche: "Maison & équipement",
    description: "Carte pastel bleu-pêche, grande image 3D, étapes simples et projets en cartes.",
    theme: theme({
      bg: "#ffffff",
      surface: "#ffffff",
      text: "#131722",
      primary: "#131722",
      accent: "#131722",
      dark: "#131722",
      heroBg: "linear-gradient(110deg,#dce9f4 0%,#f6e7da 100%)",
      heroText: "#131722",
      radius: 18,
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 500,
      headingTracking: "-0.03em",
    }),
    header: "split",
    hero: "soft-card",
    card: "soft",
    categories: "tiles",
    promos: "split",
    trust: "icons",
    layout: {
      header: "classic",
      card: "classic",
      faq: "split",
      footer: "columns",
      shop: "sidebar",
      product: "split",
      page: "banner",
    },
    sections: ["hero", "trust", "products", "showcase", "stats", "categories", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Bienvenue",
        title: "Équipez votre maison",
        text: "Tout ce qu'il faut pour un intérieur pratique et confortable, livré chez vous partout au Maroc.",
        button: "Rechercher",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Nos produits phares",
        collectionSubtitle: "Les meilleures ventes du moment.",
        sections: {
          trust: {
            title: "Trois étapes, quelques minutes",
            items: [
              { title: "Choisissez", text: "Parcourez la boutique et ajoutez au panier." },
              { title: "Laissez votre numéro", text: "Nous vous appelons pour confirmer." },
              { title: "Recevez", text: "Livraison et paiement à la porte." },
            ],
          },
          showcase: {
            eyebrow: "Nos services",
            title: "Voici comment nous faisons mieux",
            text: "Des produits vérifiés, des prix clairs et un service client disponible.",
            items: [
              { title: "Produits contrôlés avant l'envoi" },
              { title: "Réponse rapide sur WhatsApp" },
              { title: "Échange simple en cas de souci" },
            ],
          },
        },
      },
      {
        eyebrow: "مرحبا",
        title: "جهز دارك",
        text: "كلشي اللي خاصك لدار عملية ومريحة، كيوصلك لجميع المدن.",
        button: "قلب",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "المنتجات المميزة",
        collectionSubtitle: "الأكثر مبيعا هاد الأيام.",
        sections: {
          trust: {
            title: "ثلاث خطوات، دقايق قليلة",
            items: [
              { title: "اختار", text: "تصفح المتجر وزيد للسلة." },
              { title: "خلي النمرة ديالك", text: "كنعيطو ليك باش نأكدو." },
              { title: "توصل", text: "التوصيل والخلاص عند الباب." },
            ],
          },
          showcase: {
            eyebrow: "الخدمات ديالنا",
            title: "هكا كنخدمو أحسن",
            text: "منتجات مراقبة، أثمنة واضحة وخدمة زبناء موجودة.",
            items: [
              { title: "منتجات مراقبة قبل الإرسال" },
              { title: "جواب سريع فواتساب" },
              { title: "تبديل ساهل إلا كان شي مشكل" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s2-06",
    series: 2,
    folder: "21_Fitness",
    name: "Énergie Club",
    niche: "Fitness & bien-être",
    description: "Photo sportive, cartes de suivi sombres, grands titres et bouton orange.",
    theme: theme({
      bg: "#f4f4f4",
      surface: "#fafafa",
      primary: "#ff6b3d",
      accent: "#ff6b3d",
      dark: "#0a0a0a",
      heroBg: "#2b2b2b",
      heroText: "#ffffff",
      radius: 24,
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 500,
      headingTracking: "-0.04em",
    }),
    header: "overlay",
    hero: "photo-cards",
    card: "soft",
    categories: "circles",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "pill",
      card: "overlay",
      faq: "band",
      footer: "split",
      shop: "banner",
      product: "panel",
      page: "banner",
    },
    sections: ["hero", "stats", "categories", "products", "showcase", "spotlight", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Équipement fitness",
        title: "Votre énergie. Votre progression.",
        text: "Le matériel qu'il faut pour bouger, se renforcer et suivre ses progrès, livré chez vous.",
        button: "Commencer",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Pour chaque objectif",
        collectionSubtitle: "Musculation, cardio, récupération.",
        sections: {
          stats: { title: "Bougez plus, progressez chaque jour" },
          showcase: {
            title: "Découvrez le pouvoir du sport au quotidien",
            text: "Un entraînement régulier, le bon matériel et des objectifs clairs : c'est la recette du progrès.",
            button: "Voir la boutique",
          },
          spotlight: {
            title: "Prêt à transformer votre forme ?",
            text: "Commandez aujourd'hui, payez à la livraison.",
            button: "Commander",
          },
        },
      },
      {
        eyebrow: "تجهيزات الفيتنس",
        title: "الطاقة ديالك. التقدم ديالك.",
        text: "المعدات اللي خاصك باش تتحرك، تقوى وتتبع التقدم ديالك، كتوصلك لدارك.",
        button: "بدا",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "لكل هدف",
        collectionSubtitle: "تقوية، كارديو، استرجاع.",
        sections: {
          stats: { title: "تحرك أكثر وتقدم كل نهار" },
          showcase: {
            title: "اكتشف قوة الرياضة فكل نهار",
            text: "تمرين منتظم، معدات مناسبة وأهداف واضحة: هادي هي الوصفة.",
            button: "شوف المتجر",
          },
          spotlight: { title: "واجد تبدل الفورمة ديالك؟", text: "طلب اليوم وخلص عند الاستلام.", button: "طلب دابا" },
        },
      },
    ),
  },
  {
    id: "s2-07",
    series: 2,
    folder: "22_Shoes",
    name: "Endurance",
    niche: "Chaussures & running",
    description: "Photo ciel, mot géant condensé, titres en capitales et bandeau orange.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f3f3f3",
      primary: "#111111",
      accent: "#f7d27a",
      onAccent: "#111111",
      dark: "#f0a35c",
      onDark: "#111111",
      heroBg: "linear-gradient(180deg,#9cc9ef 0%,#e9f3fb 100%)",
      heroText: "#111111",
      radius: 12,
      headingFont: "Anton",
      bodyFont: "Inter",
      headingWeight: 400,
      headingCase: "uppercase",
      headingTracking: "0",
    }),
    header: "split",
    hero: "giant-under",
    card: "plain",
    categories: "tiles",
    promos: "split",
    trust: "bar",
    layout: {
      header: "editorial",
      card: "swatch",
      faq: "numbered",
      footer: "columns",
      shop: "topbar",
      product: "stack",
      page: "split",
    },
    sections: ["hero", "showcase", "products", "rows", "trust", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Endurance",
        title: "Une collection pensée pour chaque foulée",
        text: "Chaque produit doit tenir la distance : confort, maintien et style pour vos entraînements.",
        button: "Voir les nouveautés",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "L'essentiel du coureur",
        collectionSubtitle: "Chaussures, vêtements et accessoires pour aller plus loin.",
        sections: {
          showcase: {
            title: "Trouvez votre prochaine paire",
            text: "Des modèles choisis pour la route, la piste et le quotidien.",
            button: "En savoir plus",
          },
          rows: {
            title: "Votre ressource sport",
            text: "Quoi porter, comment s'équiper : nos sélections pour chaque pratique.",
            button: "Voir",
            items: [
              { title: "Course sur route", text: "Amorti et légèreté pour les longues distances.", value: "Running" },
              { title: "Entraînement", text: "Maintien et stabilité pour la salle.", value: "Training" },
              { title: "Accessoires", text: "Chaussettes, sacs et petits indispensables.", value: "Essentiels" },
            ],
          },
        },
      },
      {
        eyebrow: "تحمل",
        title: "مجموعة مصممة لكل خطوة",
        text: "كل منتج خاصو يصبر: راحة، ثبات وستايل للتمارين ديالك.",
        button: "شوف الجديد",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "أساسيات العداء",
        collectionSubtitle: "صبابط، لبسة وإكسسوارات باش تمشي بعيد.",
        sections: {
          showcase: {
            title: "لقا الصباط الجاي ديالك",
            text: "موديلات مختارة للطريق والتيران وكل نهار.",
            button: "عرف أكثر",
          },
          rows: {
            title: "المرجع الرياضي ديالك",
            text: "شنو تلبس وكيفاش تتجهز: اختياراتنا لكل رياضة.",
            button: "شوف",
            items: [
              { title: "الجري فالطريق", text: "راحة وخفة للمسافات الطويلة.", value: "جري" },
              { title: "التمرين", text: "ثبات للصالة.", value: "تمرين" },
              { title: "إكسسوارات", text: "تقاشر، صاكات وحوايج صغيرة.", value: "أساسيات" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s2-08",
    series: 2,
    folder: "23_cloth",
    name: "Élégance Homme",
    niche: "Mode homme",
    description: "Beige crème, serif majuscules et italique, bandeau défilant de catégories.",
    theme: theme({
      bg: "#f2eee7",
      surface: "#faf8f4",
      text: "#1d1b18",
      muted: "#7a746b",
      border: "#e2dcd2",
      primary: "#1d1b18",
      accent: "#1d1b18",
      dark: "#1d1b18",
      heroBg: "#f2eee7",
      heroText: "#1d1b18",
      radius: 4,
      headingFont: "Bodoni Moda",
      bodyFont: "Inter",
      headingWeight: 400,
      headingCase: "uppercase",
    }),
    header: "split",
    hero: "editorial-serif",
    card: "plain",
    categories: "pills",
    promos: "banner",
    trust: "bar",
    layout: {
      header: "menu",
      card: "classic",
      faq: "split",
      footer: "centered",
      shop: "sidebar",
      product: "stack",
      page: "simple",
    },
    sections: ["hero", "marquee", "promos", "catalog", "showcase", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Collection homme",
        title: "Un style exclusif, sans limites",
        text: "Chemises, t-shirts et accessoires choisis pour sublimer votre allure en toute occasion.",
        button: "Acheter",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "La collection homme",
        sections: {
          marquee: {
            items: [
              { title: "Chemises" },
              { title: "Vestes" },
              { title: "Pantalons" },
              { title: "Chaussures" },
              { title: "Lunettes" },
            ],
          },
          promos: {
            title: "Une sélection à prix doux",
            text: "Profitez de nos pièces du moment sur toute la collection.",
            button: "Acheter",
          },
          catalog: { title: "La collection homme" },
          showcase: {
            title: "Pourquoi nous choisir",
            text: "Des pièces de qualité, des coupes actuelles et un service attentif.",
            items: [{ title: "Qualité premium" }, { title: "Coupes tendance" }, { title: "Service attentif" }],
          },
        },
      },
      {
        eyebrow: "مجموعة الرجال",
        title: "ستايل خاص بلا حدود",
        text: "قمجان، تيشورتات وإكسسوارات مختارة باش تبان فكل مناسبة.",
        button: "اشري دابا",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "مجموعة الرجال",
        sections: {
          marquee: {
            items: [
              { title: "قمجان" },
              { title: "جاكيطات" },
              { title: "سراويل" },
              { title: "صبابط" },
              { title: "نظارات" },
            ],
          },
          promos: { title: "اختيار بأثمنة مزيانة", text: "استافد من القطع ديال هاد اللحظة.", button: "اشري" },
          catalog: { title: "مجموعة الرجال" },
          showcase: {
            title: "علاش تختارنا",
            text: "قطع بجودة، قصات عصرية وخدمة مزيانة.",
            items: [{ title: "جودة عالية" }, { title: "قصات عصرية" }, { title: "خدمة مزيانة" }],
          },
        },
      },
    ),
  },
  {
    id: "s2-09",
    series: 2,
    folder: "24_Cosmi Bio",
    name: "Forêt Pure",
    niche: "Soins botaniques",
    description: "Vert forêt profond, titre serif italique, produits sur fond crème.",
    theme: theme({
      bg: "#f7f5ef",
      surface: "#ffffff",
      text: "#1a2a1d",
      muted: "#6b7468",
      border: "#e3e2d8",
      primary: "#20402a",
      accent: "#20402a",
      dark: "#1d3524",
      heroBg: "#1d3524",
      heroText: "#f3f0e6",
      radius: 10,
      headingFont: "Cormorant Garamond",
      bodyFont: "Inter",
      headingWeight: 500,
    }),
    header: "overlay",
    hero: "dark-forest",
    card: "plain",
    categories: "circles",
    promos: "split",
    trust: "bar",
    layout: {
      header: "utility",
      card: "classic",
      faq: "center",
      footer: "columns",
      shop: "topbar",
      product: "split",
      page: "banner",
    },
    sections: ["hero", "products", "spotlight", "categories", "showcase", "testimonials", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Soins botaniques",
        title: "Des soins purs, de vrais résultats",
        text: "Des actifs d'origine végétale et une routine simple pour une peau saine et lumineuse.",
        button: "Voir la collection",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Meilleures ventes",
        sections: {
          spotlight: {
            eyebrow: "Une routine bienfaisante",
            title: "Plus qu'un soin : un rituel",
            text: "Prenez le temps de prendre soin de vous, chaque jour.",
            button: "Découvrir",
          },
          categories: { title: "Que cherchez-vous ?" },
          showcase: {
            eyebrow: "Notre approche",
            title: "Un vrai changement",
            text: "Des formules douces pensées pour chaque type de peau.",
            button: "Nos ingrédients",
          },
          newsletter: {
            title: "Rejoignez notre communauté",
            text: "Conseils et nouveautés : écrivez-nous sur WhatsApp.",
          },
        },
      },
      {
        eyebrow: "عناية نباتية",
        title: "عناية نقية، نتائج حقيقية",
        text: "مكونات نباتية وروتين بسيط لبشرة صحية ومضيئة.",
        button: "شوف المجموعة",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "الأكثر مبيعا",
        sections: {
          spotlight: {
            eyebrow: "روتين مريح",
            title: "أكثر من عناية: طقس",
            text: "خصص وقت لراسك كل نهار.",
            button: "اكتشف",
          },
          categories: { title: "على شنو كتقلب؟" },
          showcase: {
            eyebrow: "الطريقة ديالنا",
            title: "تغيير حقيقي",
            text: "تركيبات لطيفة لكل نوع ديال البشرة.",
            button: "المكونات",
          },
          newsletter: { title: "انضم للمجتمع ديالنا", text: "نصائح وجديد: كتب لينا فواتساب." },
        },
      },
    ),
  },
  {
    id: "s2-10",
    series: 2,
    folder: "25_Restaurant",
    name: "Table Gourmande",
    niche: "Restauration & traiteur",
    description: "Blanc et brun chocolat, assiettes en cercle, titres soulignés au pinceau.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f2f6f6",
      text: "#1f1a17",
      primary: "#8a3b12",
      accent: "#8a3b12",
      dark: "#1f3b38",
      heroBg: "#ffffff",
      heroText: "#1f1a17",
      radius: 6,
      headingFont: "Poppins",
      bodyFont: "Poppins",
      headingWeight: 600,
    }),
    header: "split",
    hero: "plates",
    card: "boxed",
    categories: "pills",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "search",
      card: "framed",
      faq: "cards",
      footer: "cta",
      shop: "topbar",
      product: "centered",
      page: "simple",
    },
    sections: ["hero", "showcase", "catalog", "testimonials", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "-10 % sur la première commande",
        title: "Bienvenue à notre table gourmande",
        highlight: "table gourmande",
        text: "Des plats généreux, préparés chaque jour avec des produits frais, livrés chauds chez vous.",
        button: "Voir le menu",
        announcement: "Commande en ligne · Paiement à la livraison",
        collectionTitle: "Nos plats",
        sections: {
          showcase: {
            eyebrow: "À propos",
            title: "Une cuisine saine pour mieux vivre",
            text: "Des recettes équilibrées, des ingrédients frais et le goût du fait maison.",
            button: "Notre histoire",
          },
          catalog: { title: "Nos spécialités" },
          trust: {
            items: [
              { title: "Livraison rapide", text: "Vos plats arrivent chauds." },
              { title: "Le meilleur goût", text: "Des recettes préparées chaque jour." },
              { title: "Paiement à la livraison", text: "Vous payez à la réception." },
            ],
          },
        },
      },
      {
        eyebrow: "-10% على الطلب الأول",
        title: "مرحبا بيكم فالطبلة ديالنا",
        highlight: "الطبلة ديالنا",
        text: "أطباق كريمة، كتوجد كل نهار بمنتجات طرية، كتوصلك سخونة.",
        button: "شوف المنيو",
        announcement: "طلب أونلاين · الدفع عند الاستلام",
        collectionTitle: "الأطباق ديالنا",
        sections: {
          showcase: {
            eyebrow: "علينا",
            title: "ماكلة صحية لحياة أحسن",
            text: "وصفات متوازنة، مكونات طرية وذوق ديال الدار.",
            button: "القصة ديالنا",
          },
          catalog: { title: "الاختصاصات ديالنا" },
          trust: {
            items: [
              { title: "توصيل سريع", text: "الأطباق كتوصل سخونة." },
              { title: "أحسن ذوق", text: "وصفات كتوجد كل نهار." },
              { title: "الدفع عند الاستلام", text: "كتخلص ملي توصلك." },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s2-11",
    series: 2,
    folder: "26_Cousmi pro",
    name: "Ciel Vital",
    niche: "Compléments & bien-être",
    description: "Photos ciel lumineuses, bleu nuit, chiffres clés et cartes produits épurées.",
    theme: theme({
      bg: "#f5f8fb",
      surface: "#ffffff",
      text: "#14233a",
      muted: "#5f6f84",
      border: "#dfe7f0",
      primary: "#1f3a5f",
      accent: "#1f3a5f",
      dark: "#1f3a5f",
      heroBg: "linear-gradient(180deg,#9cc2ea,#d9e9f7)",
      heroText: "#14233a",
      radius: 16,
      headingFont: "Manrope",
      bodyFont: "Inter",
      headingWeight: 500,
    }),
    header: "split",
    hero: "sky-wellness",
    card: "boxed",
    categories: "tiles",
    promos: "split",
    trust: "numbered",
    layout: {
      header: "classic",
      card: "tinted",
      faq: "split",
      footer: "wordmark",
      shop: "banner",
      product: "panel",
      page: "banner",
    },
    sections: ["hero", "trust", "products", "promos", "testimonials", "spotlight", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Bien-être au quotidien",
        title: "Tout ce qu'il vous faut pour une journée en forme",
        text: "Des essentiels de bien-être simples à intégrer à votre routine, livrés chez vous.",
        button: "Voir les produits",
        secondary: "Comment commander",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Les essentiels",
        collectionSubtitle: "Pensés pour votre routine de tous les jours.",
        sections: {
          trust: {
            title: "Comment ça marche",
            items: [
              { title: "Trouvez votre routine", text: "Parcourez les produits selon vos besoins." },
              { title: "Commandez en 1 minute", text: "Nom, téléphone, ville : c'est tout." },
              { title: "Recevez chez vous", text: "Paiement en espèces à la livraison." },
            ],
          },
          promos: {
            items: [
              { title: "Offre de bienvenue", text: "Demandez-nous l'offre du moment", value: "Nouveau" },
              { title: "Les packs routine", text: "Plusieurs produits, un seul envoi", value: "Pack" },
            ],
          },
          spotlight: { title: "Prêt à commencer votre routine ?", button: "Commander" },
        },
      },
      {
        eyebrow: "راحة كل نهار",
        title: "كلشي اللي خاصك لنهار فيه الطاقة",
        text: "أساسيات الراحة ساهلين تدخلهم فالروتين ديالك، كيوصلوك لدارك.",
        button: "شوف المنتجات",
        secondary: "كيفاش نطلب",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "الأساسيات",
        collectionSubtitle: "مصممين للروتين اليومي ديالك.",
        sections: {
          trust: {
            title: "كيفاش خدامة",
            items: [
              { title: "لقا الروتين ديالك", text: "تصفح المنتجات حسب الحاجة ديالك." },
              { title: "طلب فدقيقة", text: "الاسم، التيليفون، المدينة: صافي." },
              { title: "توصل لدارك", text: "الخلاص كاش عند الاستلام." },
            ],
          },
          promos: {
            items: [
              { title: "عرض الترحيب", text: "سولنا على العرض ديال دابا", value: "جديد" },
              { title: "باكات الروتين", text: "بزاف ديال المنتجات، إرسال واحد", value: "باك" },
            ],
          },
          spotlight: { title: "واجد تبدا الروتين ديالك؟", button: "طلب دابا" },
        },
      },
    ),
  },
  {
    id: "s2-12",
    series: 2,
    folder: "27_Golf",
    name: "Green Club",
    niche: "Golf & loisirs plein air",
    description: "Photo encadrée arrondie, étiquettes vert citron, bloc sombre et logotype géant vert.",
    theme: theme({
      bg: "#f6f6f4",
      surface: "#ffffff",
      primary: "#3d6b2f",
      accent: "#c6f26b",
      onAccent: "#0d0d0d",
      dark: "#0b0b0b",
      heroBg: "#2f3a26",
      heroText: "#ffffff",
      radius: 22,
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 500,
      headingTracking: "-0.03em",
    }),
    header: "split",
    hero: "framed-photo",
    card: "soft",
    categories: "tiles",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "pill",
      card: "minimal",
      faq: "band",
      footer: "wordmark",
      shop: "banner",
      product: "panel",
      page: "banner",
    },
    sections: ["hero", "showcase", "rows", "bento", "products", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Bienvenue au club",
        title: "Passez votre jeu au niveau supérieur",
        text: "Équipement, accessoires et conseils pour profiter pleinement de chaque partie.",
        button: "Voir la boutique",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Notre collection",
        sections: {
          showcase: {
            eyebrow: "Notre histoire",
            title: "Le vrai esprit du jeu",
            text: "Du débutant au joueur confirmé, nous voulons rendre l'équipement accessible et agréable.",
            button: "Lire la suite",
          },
          rows: {
            title: "Les sélections du moment — à ne pas manquer",
            text: "Nos collections pour chaque moment sur le parcours.",
            button: "Voir",
            items: [
              { title: "Sacs & chariots", text: "Organisez votre matériel avec style.", value: "Collection" },
              { title: "Accessoires de jeu", text: "Balles, gants, tees : les indispensables.", value: "Essentiels" },
            ],
          },
          bento: {
            title: "Profitez du jeu, de la première à la dernière partie",
            items: [
              { title: "Pour tous les niveaux", text: "Débutants comme confirmés." },
              { title: "Produits disponibles", value: "{products}" },
              { title: "Paiement à la livraison", value: "100%" },
            ],
          },
        },
      },
      {
        eyebrow: "مرحبا فالنادي",
        title: "طلع اللعب ديالك للمستوى الجاي",
        text: "معدات، إكسسوارات ونصائح باش تستمتع بكل طرح.",
        button: "شوف المتجر",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "المجموعة ديالنا",
        sections: {
          showcase: {
            eyebrow: "القصة ديالنا",
            title: "الروح الحقيقية ديال اللعب",
            text: "من المبتدئ حتى للمحترف، بغينا نسهلو المعدات للجميع.",
            button: "قرا أكثر",
          },
          rows: {
            title: "اختيارات هاد اللحظة",
            text: "المجموعات ديالنا لكل لحظة.",
            button: "شوف",
            items: [
              { title: "صاكات وكراريس", text: "نظم المعدات ديالك بستايل.", value: "مجموعة" },
              { title: "إكسسوارات اللعب", text: "الكور، الليجان والأساسيات.", value: "أساسيات" },
            ],
          },
          bento: {
            title: "استمتع باللعب من الأول للآخر",
            items: [
              { title: "لجميع المستويات", text: "المبتدئين والمحترفين." },
              { title: "منتج متوفر", value: "{products}" },
              { title: "الدفع عند الاستلام", value: "100%" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s2-13",
    series: 2,
    folder: "28_cousmitique",
    name: "Rituel Lumière",
    niche: "Sérums & soins visage",
    description: "Vert profond, vert acidulé et crème, titres condensés et collage d'images.",
    theme: theme({
      bg: "#0f3d24",
      surface: "#134a2c",
      text: "#f1efe2",
      muted: "#b7c6b3",
      border: "#2a5a3e",
      primary: "#b9f36b",
      onPrimary: "#0f3d24",
      accent: "#b9f36b",
      onAccent: "#0f3d24",
      dark: "#0b2e1b",
      heroBg: "#0f3d24",
      heroText: "#f1efe2",
      radius: 8,
      headingFont: "Oswald",
      bodyFont: "Inter",
      headingWeight: 500,
      headingCase: "uppercase",
    }),
    header: "split",
    hero: "dark-collage",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "bar",
    layout: {
      header: "classic",
      card: "tinted",
      faq: "split",
      footer: "columns",
      shop: "topbar",
      product: "panel",
      page: "split",
    },
    sections: ["hero", "trust", "showcase", "products", "spotlight", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Soin de luxe, tout en douceur",
        title: "Un éclat aussi pur qu'il en a l'air",
        highlight: "pur",
        text: "Des soins pour hydrater, réparer et sublimer la peau, au quotidien.",
        button: "Voir la collection",
        secondary: "Notre histoire",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Les essentiels du rituel",
        collectionSubtitle: "Pour hydrater, réparer et sublimer.",
        sections: {
          showcase: {
            eyebrow: "Le naturel avant tout",
            title: "L'éclat commence par une routine",
            text: "Le soin de la peau est un rituel quotidien : des gestes simples, des formules choisies.",
            button: "Découvrir",
          },
          spotlight: {
            eyebrow: "Formules fraîches",
            title: "Formulé pour un éclat durable",
            button: "Voir les soins",
          },
        },
      },
      {
        eyebrow: "عناية راقية بلطف",
        title: "إشراقة نقية بحال ما كتبان",
        highlight: "نقية",
        text: "منتجات العناية باش ترطب، تصلح وتزين البشرة كل نهار.",
        button: "شوف المجموعة",
        secondary: "القصة ديالنا",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "أساسيات الروتين",
        collectionSubtitle: "باش ترطب، تصلح وتزين.",
        sections: {
          showcase: {
            eyebrow: "الطبيعي قبل كلشي",
            title: "الإشراقة كتبدا بروتين",
            text: "العناية بالبشرة طقس يومي: حركات بسيطة وتركيبات مختارة.",
            button: "اكتشف",
          },
          spotlight: { eyebrow: "تركيبات طرية", title: "مصمم لإشراقة كتدوم", button: "شوف المنتجات" },
        },
      },
    ),
  },
  {
    id: "s2-14",
    series: 2,
    folder: "29_Bio Tch",
    name: "Terra Nova",
    niche: "Jardin, agriculture & nature",
    description: "Grande photo de champ, titre centré, accordéon vert pâle et bloc articles sombre.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f6f7f2",
      primary: "#3f6b1f",
      accent: "#111111",
      dark: "#0d0d0d",
      heroBg: "#5b7f3a",
      heroText: "#ffffff",
      radius: 18,
      headingFont: "Manrope",
      bodyFont: "Inter",
      headingWeight: 500,
    }),
    header: "overlay",
    hero: "center-photo",
    card: "soft",
    categories: "tiles",
    promos: "split",
    trust: "numbered",
    layout: {
      header: "centered",
      card: "classic",
      faq: "center",
      footer: "minimal",
      shop: "sidebar",
      product: "split",
      page: "split",
    },
    sections: ["hero", "showcase", "categories", "rows", "products", "spotlight", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Pour la terre et le jardin",
        title: "Prenez soin de la terre, elle vous le rend",
        text: "Graines, outils et produits de jardin choisis pour des cultures saines.",
        button: "Commencer",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Nos produits",
        sections: {
          showcase: {
            title: "Des produits adaptés à vos besoins, pour des récoltes qui dépassent vos attentes",
            text: "Particuliers, agriculteurs ou passionnés : chacun trouve l'outil qu'il lui faut.",
          },
          rows: {
            eyebrow: "Nos conseils",
            title: "Restez informé avec des conseils de jardinage",
            button: "Lire",
            items: [
              {
                title: "Cultiver en respectant le sol",
                text: "Les bons gestes pour des cultures durables.",
                value: "Conseil",
              },
              { title: "Bien choisir ses outils", text: "Les indispensables selon votre surface.", value: "Guide" },
            ],
          },
          spotlight: { title: "Rejoignez la nouvelle vague du jardinage", button: "Voir la boutique" },
        },
      },
      {
        eyebrow: "للأرض والجردة",
        title: "اعتني بالأرض، هي غادي تردها ليك",
        text: "زريعة، أدوات ومنتجات الجردة مختارة لزراعة صحية.",
        button: "بدا",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "المنتجات ديالنا",
        sections: {
          showcase: {
            title: "منتجات مناسبة لحاجتك، لمحاصيل كتفوت التوقعات",
            text: "أفراد، فلاحة ولا هواة: كل واحد كيلقا الأداة اللي خاصاه.",
          },
          rows: {
            eyebrow: "نصائحنا",
            title: "بقا على اطلاع بنصائح الجردة",
            button: "قرا",
            items: [
              { title: "زرع مع احترام التربة", text: "الحركات الصحيحة لزراعة كتدوم.", value: "نصيحة" },
              { title: "اختار الأدوات مزيان", text: "الأساسيات حسب المساحة ديالك.", value: "دليل" },
            ],
          },
          spotlight: { title: "انضم للموجة الجديدة ديال الجردة", button: "شوف المتجر" },
        },
      },
    ),
  },
  {
    id: "s2-15",
    series: 2,
    folder: "30_Golfio",
    name: "Fairway Nuit",
    niche: "Sport premium & loisirs",
    description: "Vert nuit, jaune vif, grande image et logotype géant en pied de page.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f4f5f0",
      primary: "#1c2a13",
      accent: "#f5cf1a",
      onAccent: "#1c2a13",
      dark: "#1c2a13",
      heroBg: "#1c2a13",
      heroText: "#ffffff",
      radius: 14,
      headingFont: "Poppins",
      bodyFont: "Inter",
      headingWeight: 500,
    }),
    header: "dark",
    hero: "dark-split",
    card: "soft",
    categories: "tiles",
    promos: "cards",
    trust: "numbered",
    layout: {
      header: "classic",
      card: "swatch",
      faq: "numbered",
      footer: "wordmark",
      shop: "sidebar",
      product: "stack",
      page: "banner",
    },
    sections: ["hero", "trust", "products", "rows", "stats", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Jouez mieux",
        title: "Équipez-vous mieux, jouez plus malin",
        highlight: "jouez plus malin",
        text: "Une sélection d'équipements premium et un service simple : commandez, recevez, profitez.",
        button: "Voir la boutique",
        secondary: "Comment ça marche",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Équipement premium",
        sections: {
          trust: {
            title: "Votre parcours vers un meilleur jeu",
            items: [
              { title: "Trouvez", text: "Les produits adaptés à votre niveau." },
              { title: "Choisissez", text: "Comparez et posez vos questions." },
              { title: "Réservez", text: "Commandez en une minute." },
              { title: "Progressez", text: "Recevez et payez à la livraison." },
            ],
          },
          rows: {
            title: "Commandez en toute confiance",
            button: "Voir",
            items: [
              { title: "Collections premium", text: "Des marques choisies pour leur qualité.", value: "01" },
              {
                title: "Confirmation instantanée",
                text: "Un appel pour valider, sans paiement en ligne.",
                value: "02",
              },
            ],
          },
          stats: { title: "Une façon plus simple d'acheter et de jouer" },
        },
      },
      {
        eyebrow: "العب أحسن",
        title: "تجهز أحسن، العب بذكاء",
        highlight: "العب بذكاء",
        text: "اختيار ديال معدات راقية وخدمة بسيطة: طلب، توصل، واستمتع.",
        button: "شوف المتجر",
        secondary: "كيفاش خدامة",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "معدات راقية",
        sections: {
          trust: {
            title: "الطريق ديالك للعب أحسن",
            items: [
              { title: "لقا", text: "المنتجات المناسبة للمستوى ديالك." },
              { title: "اختار", text: "قارن وسول." },
              { title: "طلب", text: "فدقيقة وحدة." },
              { title: "تقدم", text: "توصل وخلص عند الاستلام." },
            ],
          },
          rows: {
            title: "طلب بثقة",
            button: "شوف",
            items: [
              { title: "مجموعات راقية", text: "ماركات مختارة على حساب الجودة.", value: "01" },
              { title: "تأكيد فوري", text: "مكالمة باش نأكدو، بلا خلاص أونلاين.", value: "02" },
            ],
          },
          stats: { title: "طريقة أسهل للشرا واللعب" },
        },
      },
    ),
  },
];
