// Série 1 — 15 templates de boutique, un par dossier de la série.
// Les maquettes de référence ne servent que pour la mise en page, les couleurs
// et la typographie : textes, noms et images sont propres à LandPro et les
// images affichées sont celles des produits de la boutique.
import type { StoreTemplate, SxCopy, SxTheme } from "./types";
import { SHARED_AR, SHARED_FR, withShared } from "./shared-copy";

const base: Omit<SxTheme, "primary" | "accent" | "heroBg" | "heroText"> = {
  bg: "#ffffff",
  surface: "#ffffff",
  text: "#111111",
  muted: "#6b7280",
  border: "#e5e7eb",
  onPrimary: "#ffffff",
  onAccent: "#ffffff",
  dark: "#111111",
  onDark: "#ffffff",
  radius: 14,
  headingFont: "Inter",
  bodyFont: "Inter",
  headingWeight: 700,
};
const theme = (t: Partial<SxTheme> & Pick<SxTheme, "primary" | "accent" | "heroBg" | "heroText">): SxTheme => ({
  ...base,
  ...t,
});
const copy = (fr: SxCopy, ar: SxCopy) => ({
  fr: { ...fr, sections: withShared(SHARED_FR, fr.sections) },
  ar: { ...ar, sections: withShared(SHARED_AR, ar.sections) },
});

export const SERIE_1: StoreTemplate[] = [
  {
    id: "s1-01",
    series: 1,
    folder: "001_DdBNP5wICPa",
    name: "Vision Rouge",
    niche: "Lunettes & accessoires",
    description: "Éditorial rouge et noir, très grands titres, chiffres clés et blocs contrastés.",
    theme: theme({
      bg: "#f4f3f0",
      surface: "#ffffff",
      primary: "#e10600",
      accent: "#f4e409",
      onAccent: "#0b0b0b",
      dark: "#0b0b0b",
      heroBg: "#f4f3f0",
      heroText: "#0b0b0b",
      radius: 4,
      headingFont: "Space Grotesk",
      bodyFont: "Inter",
      headingWeight: 600,
      headingCase: "uppercase",
      headingTracking: "-0.03em",
    }),
    header: "split",
    hero: "editorial",
    card: "plain",
    categories: "pills",
    promos: "split",
    trust: "numbered",
    sections: ["hero", "products", "showcase", "promos", "categories", "trust", "newsletter", "faq"],
    hiddenByDefault: ["stats", "testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle série",
        title: "La performance commence par la vision",
        highlight: "vision",
        text: "Des pièces conçues pour la précision, le confort et le style au quotidien.",
        button: "Découvrir la collection",
        secondary: "Livraison & paiement",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "La sélection",
        collectionSubtitle: "Nos modèles les plus demandés.",
        sections: {
          showcase: {
            eyebrow: "Conçu pour vous",
            title: "Clarté. Précision. Focus.",
            text: "Chaque modèle est choisi pour sa tenue, sa légèreté et ses finitions. Un style net qui vous suit toute la journée.",
            button: "Voir la boutique",
          },
          promos: {
            items: [
              { title: "Nouveautés", text: "Les derniers modèles arrivés", value: "Nouveau" },
              { title: "Best-sellers", text: "Les préférés de nos clients", value: "Top" },
            ],
          },
          stats: { title: "En chiffres" },
        },
      },
      {
        eyebrow: "سلسلة جديدة",
        title: "الأداء كيبدا من الرؤية",
        highlight: "الرؤية",
        text: "قطع مصممة للدقة والراحة والستايل فكل نهار.",
        button: "اكتشف المجموعة",
        secondary: "التوصيل والدفع",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "المختارات",
        collectionSubtitle: "الموديلات الأكثر طلبا.",
        sections: {
          showcase: {
            eyebrow: "مصمم ليك",
            title: "وضوح. دقة. تركيز.",
            text: "كل موديل مختار على حساب الجودة والخفة والفينيسيون. ستايل نقي كيبقى معاك طول النهار.",
            button: "شوف المتجر",
          },
          promos: {
            items: [
              { title: "الجديد", text: "آخر الموديلات اللي وصلات", value: "جديد" },
              { title: "الأكثر مبيعا", text: "المفضلين عند زبناءنا", value: "توب" },
            ],
          },
          stats: { title: "بالأرقام" },
        },
      },
    ),
  },
  {
    id: "s1-02",
    series: 1,
    folder: "001_DeCti3rjl8W",
    name: "Sunrise Pop",
    niche: "Jeunesse & loisirs",
    description: "Dégradé orange vif, bouton vert, formes arrondies et ambiance joyeuse.",
    theme: theme({
      bg: "#ffffff",
      primary: "#e8452c",
      accent: "#16a36a",
      dark: "#e8452c",
      heroBg: "#ffffff",
      heroText: "#1a1a1a",
      radius: 22,
      headingFont: "Poppins",
      bodyFont: "Poppins",
      headingWeight: 700,
    }),
    header: "split",
    hero: "pop",
    card: "soft",
    categories: "tiles",
    promos: "cards",
    trust: "icons",
    sections: ["hero", "trust", "products", "showcase", "categories", "promos", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouveautés",
        title: "Des produits qui font sourire chaque jour",
        highlight: "sourire",
        text: "Une sélection fun et utile, livrée chez vous partout au Maroc. Vous payez à la réception.",
        button: "Commencer mes achats",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Nos coups de cœur",
        collectionSubtitle: "Les produits préférés de la communauté.",
        sections: {
          showcase: {
            eyebrow: "Pourquoi nous",
            title: "Des avantages qui font la différence",
            text: "Des produits testés, des prix clairs et une équipe disponible pour vous aider à choisir.",
            button: "En savoir plus",
            items: [{ title: "Choix vérifié" }, { title: "Prix clairs" }, { title: "Aide rapide" }],
          },
          promos: {
            items: [
              { title: "Pour les petits", text: "Des idées cadeaux qui plaisent" },
              { title: "Pour toute la famille", text: "Utile au quotidien" },
            ],
          },
        },
      },
      {
        eyebrow: "الجديد",
        title: "منتجات كتفرح كل نهار",
        highlight: "كتفرح",
        text: "اختيارات زوينة ومفيدة كتوصلك لدارك فجميع المدن. كتخلص ملي توصلك.",
        button: "بدا التسوق",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "اختياراتنا",
        collectionSubtitle: "المنتجات المفضلة عند الزبناء.",
        sections: {
          showcase: {
            eyebrow: "علاش حنا",
            title: "مزايا كتفرق",
            text: "منتجات مجربة، أثمنة واضحة وفريق ديما معاك باش يعاونك تختار.",
            button: "عرف أكثر",
            items: [{ title: "اختيار مضمون" }, { title: "أثمنة واضحة" }, { title: "مساعدة سريعة" }],
          },
          promos: {
            items: [
              { title: "للصغار", text: "أفكار هدايا كتعجب" },
              { title: "للعائلة كاملة", text: "مفيد فكل نهار" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s1-03",
    series: 1,
    folder: "002_Ddwt4xeE0Sa",
    name: "Sauge Naturelle",
    niche: "Soins & cosmétique",
    description: "Vert sauge apaisant, mot géant en fond, cartes produits douces.",
    theme: theme({
      bg: "#f1f1ec",
      surface: "#ffffff",
      primary: "#6f8f5e",
      accent: "#e5482d",
      dark: "#6f8f5e",
      heroBg: "#7f9d6c",
      heroText: "#ffffff",
      radius: 18,
      headingFont: "Poppins",
      bodyFont: "Inter",
      headingWeight: 700,
      headingCase: "none",
    }),
    header: "overlay",
    hero: "giant",
    card: "boxed",
    categories: "tiles",
    promos: "split",
    trust: "icons",
    sections: ["hero", "showcase", "products", "promos", "trust", "categories", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Soins naturels",
        title: "Beauté naturelle",
        text: "Des soins simples et efficaces pour une routine qui vous ressemble.",
        button: "Acheter",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Prenez soin de vous",
        collectionSubtitle: "Les essentiels de votre routine.",
        sections: {
          showcase: {
            title: "La simplicité pour un soin plus efficace",
            text: "Moins d'étapes, de meilleurs gestes : nous sélectionnons des produits doux, adaptés au quotidien.",
            button: "Découvrir",
          },
          promos: {
            items: [
              { title: "Commandez en quelques clics", text: "Livraison rapide, paiement à la réception" },
              { title: "Les dernières nouveautés", text: "Les produits arrivés cette semaine" },
            ],
          },
        },
      },
      {
        eyebrow: "عناية طبيعية",
        title: "جمال طبيعي",
        text: "منتجات عناية بسيطة وفعالة لروتين كيشبهك.",
        button: "اشري دابا",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "اهتم براسك",
        collectionSubtitle: "الأساسيات ديال الروتين ديالك.",
        sections: {
          showcase: {
            title: "البساطة لعناية أكثر فعالية",
            text: "خطوات قليلة ونتيجة أحسن: كنختارو منتجات لطيفة ومناسبة لكل نهار.",
            button: "اكتشف",
          },
          promos: {
            items: [
              { title: "طلب فبضع نقرات", text: "توصيل سريع والدفع عند الاستلام" },
              { title: "آخر الجديد", text: "المنتجات اللي وصلات هاد السيمانة" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s1-04",
    series: 1,
    folder: "002_DeCjirbGcJC",
    name: "Créateur Orange",
    niche: "Tech & bureau",
    description: "Blanc net, orange énergique, grande image et cartes numérotées sur fond sombre.",
    theme: theme({
      bg: "#ffffff",
      primary: "#ff5b14",
      accent: "#ff5b14",
      dark: "#141414",
      heroBg: "linear-gradient(180deg,#ffffff 0%,#fff3ec 100%)",
      heroText: "#141414",
      radius: 16,
      headingFont: "Manrope",
      bodyFont: "Manrope",
      headingWeight: 700,
    }),
    header: "split",
    hero: "split-card",
    card: "soft",
    categories: "tiles",
    promos: "cards",
    trust: "numbered",
    sections: ["hero", "products", "trust", "showcase", "stats", "categories", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Équipez votre quotidien",
        title: "Travaillez mieux avec les bons outils",
        highlight: "bons outils",
        text: "Une sélection d'accessoires pratiques pour le travail, les études et la création.",
        button: "Voir les produits",
        secondary: "Comment commander",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Pensé pour les créateurs",
        collectionSubtitle: "Des produits utiles, choisis avec soin.",
        sections: {
          showcase: {
            eyebrow: "Comment ça marche",
            title: "Votre commande en quelques minutes",
            text: "Choisissez, commandez, recevez : nous nous occupons du reste.",
            items: [
              { title: "Choisissez vos produits", text: "Ajoutez-les au panier en un clic." },
              { title: "Confirmez par téléphone", text: "Nous vous appelons pour valider." },
              { title: "Recevez et payez", text: "Paiement en espèces à la livraison." },
            ],
          },
        },
      },
      {
        eyebrow: "جهز نهارك",
        title: "خدم أحسن بالأدوات المناسبة",
        highlight: "الأدوات المناسبة",
        text: "اختيار ديال إكسسوارات عملية للخدمة والقراية والإبداع.",
        button: "شوف المنتجات",
        secondary: "كيفاش نطلب",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "مصمم للمبدعين",
        collectionSubtitle: "منتجات مفيدة مختارة بعناية.",
        sections: {
          showcase: {
            eyebrow: "كيفاش خدامة",
            title: "الطلب ديالك فدقائق",
            text: "اختار، طلب، توصل: حنا كنتكلفو بالباقي.",
            items: [
              { title: "اختار المنتجات", text: "زيدهم للسلة بنقرة وحدة." },
              { title: "أكد بالتيليفون", text: "كنعيطو ليك باش نأكدو." },
              { title: "توصل وخلص", text: "الخلاص كاش عند الاستلام." },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s1-05",
    series: 1,
    folder: "003_Dd31zZaCmOm",
    name: "Minimal Clarté",
    niche: "Gadgets & électronique",
    description: "Gris très clair, typographie fine, accents orange et vert, maquette mobile.",
    theme: theme({
      bg: "#f3f3f1",
      surface: "#ffffff",
      primary: "#1c1c1c",
      accent: "#f08a24",
      dark: "#1c1c1c",
      heroBg: "#f3f3f1",
      heroText: "#1c1c1c",
      radius: 24,
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 500,
      headingTracking: "-0.02em",
    }),
    header: "split",
    hero: "mockup",
    card: "boxed",
    categories: "pills",
    promos: "cards",
    trust: "icons",
    sections: ["hero", "trust", "products", "showcase", "categories", "stats", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Simple et malin",
        title: "Le bon gadget, sans effort",
        highlight: "sans effort",
        text: "Des produits malins qui simplifient votre quotidien, livrés partout au Maroc.",
        button: "Découvrir",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Nos produits",
        collectionSubtitle: "Pratiques, fiables, faciles à utiliser.",
        sections: {
          showcase: {
            eyebrow: "En 3 étapes",
            title: "Commander n'a jamais été aussi simple",
            text: "Pas de carte bancaire, pas de compte à créer : il suffit de votre nom et de votre téléphone.",
            items: [
              { title: "Ajoutez au panier" },
              { title: "Laissez votre numéro" },
              { title: "Payez à la réception" },
            ],
          },
        },
      },
      {
        eyebrow: "بسيط وذكي",
        title: "الأداة المناسبة بلا تعب",
        highlight: "بلا تعب",
        text: "منتجات ذكية كتسهل حياتك اليومية، كتوصلك لجميع المدن.",
        button: "اكتشف",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "منتجاتنا",
        collectionSubtitle: "عملية، مضمونة وساهلة فالاستعمال.",
        sections: {
          showcase: {
            eyebrow: "ف3 خطوات",
            title: "الطلب عمرو ما كان ساهل بحال دابا",
            text: "بلا بطاقة بنكية وبلا حساب: غير سميتك ونمرة التيليفون.",
            items: [{ title: "زيد للسلة" }, { title: "خلي النمرة ديالك" }, { title: "خلص عند الاستلام" }],
          },
        },
      },
    ),
  },
  {
    id: "s1-06",
    series: 1,
    folder: "003_Dd4iBljtc_6",
    name: "Résidence Nocturne",
    niche: "Maison & décoration haut de gamme",
    description: "Photo sombre plein cadre, titres en capitales, beige minéral et cartes noires.",
    theme: theme({
      bg: "#efece6",
      surface: "#f7f5f1",
      text: "#161616",
      muted: "#6d6a64",
      border: "#dcd7cd",
      primary: "#161616",
      accent: "#161616",
      dark: "#1a1a1a",
      heroBg: "#1b1d20",
      heroText: "#ffffff",
      radius: 10,
      headingFont: "Manrope",
      bodyFont: "Manrope",
      headingWeight: 600,
    }),
    header: "overlay",
    hero: "photo-dark",
    card: "plain",
    categories: "tiles",
    promos: "split",
    trust: "bar",
    sections: ["hero", "showcase", "promos", "products", "categories", "trust", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Collection maison",
        title: "Votre intérieur, en mieux",
        text: "Des pièces choisies pour la lumière, les matières et le confort. Pensées pour durer.",
        button: "Explorer la collection",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Pièces choisies",
        collectionSubtitle: "Des matières nobles, des lignes simples.",
        sections: {
          showcase: {
            title: "Certaines pièces sont faites pour durer",
            text: "Plus qu'un objet : une atmosphère. Chaque produit est sélectionné pour sa qualité et son caractère.",
          },
          promos: {
            items: [
              { title: "Un confort pensé", text: "Des matières agréables, des finitions soignées." },
              { title: "Un style intemporel", text: "Des pièces faciles à associer, saison après saison." },
            ],
          },
        },
      },
      {
        eyebrow: "مجموعة الدار",
        title: "دارك، بشكل أحسن",
        text: "قطع مختارة على حساب الضو والمواد والراحة. مصنوعة باش تدوم.",
        button: "اكتشف المجموعة",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "قطع مختارة",
        collectionSubtitle: "مواد راقية وخطوط بسيطة.",
        sections: {
          showcase: {
            title: "كاين قطع مصنوعة باش تدوم",
            text: "ماشي غير ديكور: جو كامل. كل منتج مختار على حساب الجودة والشخصية ديالو.",
          },
          promos: {
            items: [
              { title: "راحة مدروسة", text: "مواد مريحة وفينيسيون نقي." },
              { title: "ستايل ما كيبلاش", text: "قطع ساهلة التنسيق فكل موسم." },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s1-07",
    series: 1,
    folder: "004_Ddn4pFNn6Cs",
    name: "Teal Street",
    niche: "Mode & streetwear",
    description: "Bleu canard, jaune moutarde, titres condensés et grille noire colorée.",
    theme: theme({
      bg: "#ffffff",
      surface: "#ffffff",
      primary: "#2d6b66",
      accent: "#f2b705",
      onAccent: "#111111",
      dark: "#111111",
      heroBg: "linear-gradient(135deg,#3f8580 0%,#2d6b66 60%,#24524f 100%)",
      heroText: "#ffffff",
      radius: 6,
      headingFont: "Oswald",
      bodyFont: "Inter",
      headingWeight: 500,
      headingCase: "uppercase",
    }),
    header: "overlay",
    hero: "color-block",
    card: "plain",
    categories: "tiles",
    promos: "banner",
    trust: "bar",
    sections: ["hero", "promos", "products", "categories", "showcase", "trust", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle collection",
        title: "Des offres exclusives pour vous",
        text: "Des pièces qui ont du caractère, à porter tous les jours.",
        button: "Acheter",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Les tendances",
        collectionSubtitle: "Ce qui se porte en ce moment.",
        sections: {
          promos: {
            title: "Collection créative",
            text: "Bien dans son style, bien dans sa peau.",
            button: "Voir la collection",
          },
          showcase: {
            title: "Le style rencontre le confort",
            text: "Des coupes actuelles, des matières agréables et des prix accessibles.",
            button: "Découvrir",
          },
        },
      },
      {
        eyebrow: "مجموعة جديدة",
        title: "عروض خاصة ليك",
        text: "قطع عندها الشخصية، تلبسها كل نهار.",
        button: "اشري دابا",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "الترندات",
        collectionSubtitle: "اللي كيتلبس هاد الأيام.",
        sections: {
          promos: { title: "مجموعة مبدعة", text: "مرتاح فالستايل ديالك.", button: "شوف المجموعة" },
          showcase: {
            title: "الستايل مع الراحة",
            text: "قصات عصرية، مواد مريحة وأثمنة مناسبة.",
            button: "اكتشف",
          },
        },
      },
    ),
  },
  {
    id: "s1-08",
    series: 1,
    folder: "004_DeHNP7KkiEI",
    name: "Marketplace Gris",
    niche: "Multi-catégories",
    description: "Marketplace claire : barre de catégories, filtres latéraux, grille dense et bannière.",
    theme: theme({
      bg: "#f4f4f4",
      surface: "#ffffff",
      primary: "#111111",
      accent: "#111111",
      dark: "#111111",
      heroBg: "#f4f4f4",
      heroText: "#111111",
      radius: 2,
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 500,
      headingTracking: "-0.02em",
    }),
    header: "center",
    hero: "market",
    card: "outline",
    categories: "pills",
    promos: "banner",
    trust: "numbered",
    sections: ["hero", "catalog", "promos", "trust", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Toute la boutique",
        title: "Un style premium pour la vie moderne",
        text: "Des collections choisies, de la qualité et des pièces intemporelles pour tous les jours.",
        button: "Voir tout",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Tous les produits",
        sections: {
          promos: {
            title: "La saison se termine, les bonnes affaires commencent",
            text: "Profitez de notre sélection du moment sur toute la boutique.",
            button: "Voir la sélection",
          },
          trust: {
            title: "Pourquoi nous choisir",
            items: [
              { title: "Produits vérifiés", text: "Chaque article est contrôlé avant l'envoi." },
              { title: "Livraison sûre", text: "Emballage soigné jusqu'à votre porte." },
              { title: "Aide et échanges", text: "Une équipe disponible pour vous répondre." },
            ],
          },
        },
      },
      {
        eyebrow: "المتجر كامل",
        title: "ستايل راقي للحياة العصرية",
        text: "مجموعات مختارة، جودة وقطع ما كتبلاش لكل نهار.",
        button: "شوف الكل",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "جميع المنتجات",
        sections: {
          promos: {
            title: "سالا الموسم، بداو الهميزات",
            text: "استافد من الاختيار ديال هاد اللحظة فالمتجر كامل.",
            button: "شوف الاختيار",
          },
          trust: {
            title: "علاش تختارنا",
            items: [
              { title: "منتجات مراقبة", text: "كل منتج كيتشاف قبل ما يتصيفط." },
              { title: "توصيل مضمون", text: "تغليف مزيان حتى لباب الدار." },
              { title: "مساعدة وتبديل", text: "فريق موجود باش يجاوبك." },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s1-09",
    series: 1,
    folder: "005_DdcF78wDlmf",
    name: "Évasion",
    niche: "Voyage, outdoor & bagagerie",
    description: "Grande photo arrondie avec recherche, icônes illustrées et bandeau turquoise.",
    theme: theme({
      bg: "#ffffff",
      primary: "#0f4c55",
      accent: "#0f4c55",
      dark: "#0f5f66",
      heroBg: "linear-gradient(160deg,#5f9fb0 0%,#2e6f73 55%,#2b4f3a 100%)",
      heroText: "#ffffff",
      radius: 18,
      headingFont: "Poppins",
      bodyFont: "Inter",
      headingWeight: 600,
    }),
    header: "overlay",
    hero: "search",
    card: "soft",
    categories: "tiles",
    promos: "cards",
    trust: "icons",
    sections: ["hero", "trust", "categories", "products", "testimonials", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Prêt pour l'aventure",
        title: "Partez l'esprit léger",
        text: "Tout ce qu'il faut pour vos voyages et sorties, livré chez vous avant le départ.",
        button: "Rechercher",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Essentiels de voyage",
        collectionSubtitle: "Des produits pratiques pour bouger sereinement.",
        sections: {
          categories: { eyebrow: "Catégories", title: "Pour chaque escapade" },
          newsletter: { title: "Prêt pour votre prochaine sortie ?", button: "Nous écrire" },
        },
      },
      {
        eyebrow: "واجد للمغامرة",
        title: "سافر وبالك مرتاح",
        text: "كلشي اللي خاصك للسفر والخرجات، كيوصلك قبل ما تمشي.",
        button: "قلب",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "أساسيات السفر",
        collectionSubtitle: "منتجات عملية باش تتحرك براحتك.",
        sections: {
          categories: { eyebrow: "التصنيفات", title: "لكل خرجة" },
          newsletter: { title: "واجد للخرجة الجاية؟", button: "كتب لينا" },
        },
      },
    ),
  },
  {
    id: "s1-10",
    series: 1,
    folder: "005_DeEJznYDtxU",
    name: "Terre Violette",
    niche: "Maison & équipement",
    description: "Carte sombre arrondie, violet, corail et vert citron, police Poppins.",
    theme: theme({
      bg: "#ffffff",
      surface: "#ffffff",
      text: "#303642",
      primary: "#4936a9",
      accent: "#4936a9",
      dark: "#303642",
      heroBg: "#303642",
      heroText: "#ffffff",
      radius: 20,
      headingFont: "Poppins",
      bodyFont: "Poppins",
      headingWeight: 700,
    }),
    header: "dark",
    hero: "rounded-dark",
    card: "soft",
    categories: "pills",
    promos: "cards",
    trust: "icons",
    sections: ["hero", "categories", "products", "promos", "stats", "trust", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Pour votre maison",
        title: "Choisissez ce qui vous rend heureux",
        text: "Équipement, rangement et confort : tout pour la maison, livré dans tout le Maroc.",
        button: "Rechercher",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Sélection maison",
        collectionSubtitle: "Des produits utiles pour chaque pièce.",
        sections: {
          promos: {
            items: [
              { title: "Confort", text: "Pour se sentir bien chez soi", value: "#d78780" },
              { title: "Pratique", text: "Des solutions malines au quotidien", value: "#b6d877" },
            ],
          },
        },
      },
      {
        eyebrow: "لدارك",
        title: "اختار اللي كيفرحك",
        text: "تجهيز، ترتيب وراحة: كلشي للدار، كيوصلك لجميع المدن.",
        button: "قلب",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "اختيارات الدار",
        collectionSubtitle: "منتجات مفيدة لكل بيت.",
        sections: {
          promos: {
            items: [
              { title: "راحة", text: "باش تحس براسك مرتاح فدارك", value: "#d78780" },
              { title: "عملي", text: "حلول ذكية لكل نهار", value: "#b6d877" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s1-11",
    series: 1,
    folder: "006_Dc2wwXxDK4O",
    name: "Beige Intemporel",
    niche: "Mode & accessoires",
    description: "Beige chaleureux, titres serif, catégories rondes et bannières promo.",
    theme: theme({
      bg: "#f6f0e9",
      surface: "#fbf8f4",
      text: "#1e1a16",
      muted: "#7a6f64",
      border: "#e6dccf",
      primary: "#1e1a16",
      accent: "#1e1a16",
      dark: "#2a241e",
      heroBg: "linear-gradient(120deg,#e9dccb 0%,#d9c6ad 100%)",
      heroText: "#1e1a16",
      radius: 12,
      headingFont: "Playfair Display",
      bodyFont: "Inter",
      headingWeight: 500,
    }),
    header: "split",
    hero: "serif-photo",
    card: "plain",
    categories: "circles",
    promos: "split",
    trust: "bar",
    sections: ["hero", "trust", "categories", "promos", "products", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle saison",
        title: "Un style intemporel, une vie moderne",
        text: "Des collections choisies pour chaque moment. Sublimez votre quotidien avec des pièces qui inspirent.",
        button: "Voir la collection",
        secondary: "Nouveautés",
        announcement: "Livraison partout au Maroc · Paiement à la livraison · Échange facile",
        collectionTitle: "Les plus demandés",
        sections: {
          promos: {
            items: [
              { title: "Une sélection à prix doux", text: "Sur une sélection de pièces", value: "Édition limitée" },
              { title: "Les nouveautés viennent d'arriver", text: "Découvrez les derniers styles", value: "Nouveau" },
            ],
          },
        },
      },
      {
        eyebrow: "موسم جديد",
        title: "ستايل ما كيبلاش لحياة عصرية",
        text: "مجموعات مختارة لكل لحظة. زين نهارك بقطع كتلهم.",
        button: "شوف المجموعة",
        secondary: "الجديد",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام · تبديل سهل",
        collectionTitle: "الأكثر طلبا",
        sections: {
          promos: {
            items: [
              { title: "اختيار بأثمنة مزيانة", text: "على مجموعة من القطع", value: "كمية محدودة" },
              { title: "الجديد وصل", text: "اكتشف آخر الستايلات", value: "جديد" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s1-12",
    series: 1,
    folder: "006_Ddl9Rc9Evrz",
    name: "Lagon Accessoires",
    niche: "Accessoires & bijoux",
    description: "Dégradé turquoise, accent manuscrit, catégories rondes et meilleures ventes.",
    theme: theme({
      bg: "#ffffff",
      surface: "#ffffff",
      primary: "#0b7d95",
      accent: "#0b2f3a",
      dark: "#0b7d95",
      heroBg: "linear-gradient(120deg,#1fb3cf 0%,#0e8fab 55%,#0b6f86 100%)",
      heroText: "#ffffff",
      radius: 16,
      headingFont: "Poppins",
      bodyFont: "Inter",
      scriptFont: "Caveat",
      headingWeight: 600,
    }),
    header: "split",
    hero: "gradient-promo",
    card: "boxed",
    categories: "circles",
    promos: "cards",
    trust: "bar",
    sections: ["hero", "trust", "categories", "promos", "products", "showcase", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Nouvelle saison",
        title: "Les accessoires qui vous révèlent",
        highlight: "Votre style, votre humeur",
        text: "Des pièces intemporelles pour chaque humeur, chaque occasion et chaque version de vous.",
        button: "Voir les nouveautés",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Meilleures ventes de la semaine",
        collectionSubtitle: "Les produits les plus populaires du moment.",
        sections: {
          promos: {
            items: [
              { title: "Affirmez votre style", text: "Des modèles pour toutes les envies" },
              { title: "Portez la confiance", text: "Pensé pour votre quotidien" },
            ],
          },
          showcase: {
            eyebrow: "Nouvelle collection",
            title: "Les détails qui complètent votre look",
            text: "Parce que tout est dans les détails.",
            button: "Voir la collection",
          },
        },
      },
      {
        eyebrow: "موسم جديد",
        title: "إكسسوارات كتبين شخصيتك",
        highlight: "الستايل ديالك، المزاج ديالك",
        text: "قطع ما كتبلاش لكل مزاج ولكل مناسبة.",
        button: "شوف الجديد",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "الأكثر مبيعا هاد السيمانة",
        collectionSubtitle: "المنتجات اللي عليها الطلب دابا.",
        sections: {
          promos: {
            items: [
              { title: "بين الستايل ديالك", text: "موديلات لكل ذوق" },
              { title: "لبس الثقة", text: "مصمم لنهارك" },
            ],
          },
          showcase: {
            eyebrow: "مجموعة جديدة",
            title: "التفاصيل اللي كتكمل اللوك ديالك",
            text: "حيت كلشي فالتفاصيل.",
            button: "شوف المجموعة",
          },
        },
      },
    ),
  },
  {
    id: "s1-13",
    series: 1,
    folder: "007_DdrsY3YGT_3",
    name: "Fizz Wordmark",
    niche: "Boissons & alimentation",
    description: "Ciel bleu, boutons orange, accent manuscrit et immense logotype en minuscules.",
    theme: theme({
      bg: "#ffffff",
      primary: "#ff7a1a",
      accent: "#ff7a1a",
      dark: "#1d6fd1",
      heroBg: "linear-gradient(180deg,#2f86e0 0%,#7cc0f2 100%)",
      heroText: "#ffffff",
      radius: 22,
      headingFont: "Poppins",
      bodyFont: "Inter",
      scriptFont: "Caveat",
      headingWeight: 500,
    }),
    header: "overlay",
    hero: "wordmark",
    card: "soft",
    categories: "tiles",
    promos: "cards",
    trust: "icons",
    sections: ["hero", "wordmark", "showcase", "products", "categories", "stats", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Fraîcheur",
        title: "Rafraîchissez votre journée, naturellement",
        highlight: "goûtez-moi",
        text: "Des saveurs vives et des ingrédients choisis pour un vrai moment de fraîcheur.",
        button: "Commander",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Nos saveurs",
        collectionSubtitle: "De l'énergie pour tout l'été.",
        sections: {
          wordmark: { eyebrow: "à propos" },
          showcase: {
            eyebrow: "à propos",
            title: "Pensé pour chaque moment rafraîchissant",
            text: "Nous sélectionnons des produits savoureux et de qualité, à partager ou à garder pour soi.",
            button: "Découvrir",
          },
          newsletter: { title: "Restez au frais", text: "Une question ? Écrivez-nous, on vous répond vite." },
        },
      },
      {
        eyebrow: "انتعاش",
        title: "نعش نهارك بطريقة طبيعية",
        highlight: "ذوقني",
        text: "نكهات منعشة ومكونات مختارة للحظة انتعاش حقيقية.",
        button: "طلب دابا",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "النكهات ديالنا",
        collectionSubtitle: "طاقة للصيف كامل.",
        sections: {
          wordmark: { eyebrow: "علينا" },
          showcase: {
            eyebrow: "علينا",
            title: "مصمم لكل لحظة انتعاش",
            text: "كنختارو منتجات بنينة وبجودة، تقسمها ولا تخليها ليك.",
            button: "اكتشف",
          },
          newsletter: { title: "بقا منتعش", text: "عندك سؤال؟ كتب لينا، كنجاوبوك بسرعة." },
        },
      },
    ),
  },
  {
    id: "s1-14",
    series: 1,
    folder: "007_DeES_f3mTpe",
    name: "Espace Mémoire",
    niche: "Mobilier & design d'intérieur",
    description: "Blanc architectural, titres soulignés, touche orange et pied de page sombre.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f6f6f6",
      primary: "#ff5a1f",
      accent: "#141414",
      dark: "#101014",
      heroBg: "#ffffff",
      heroText: "#141414",
      radius: 14,
      headingFont: "Inter",
      bodyFont: "Inter",
      headingWeight: 500,
      headingTracking: "-0.03em",
    }),
    header: "split",
    hero: "architect",
    card: "boxed",
    categories: "tiles",
    promos: "split",
    trust: "numbered",
    sections: ["hero", "showcase", "products", "categories", "trust", "promos", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Design d'intérieur",
        title: "Des espaces qui vous ressemblent",
        highlight: "ressemblent",
        text: "Mobilier et objets pensés pour transformer chaque pièce en un lieu où l'on se sent bien.",
        button: "Voir les produits",
        secondary: "Nous contacter",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Produits phares",
        collectionSubtitle: "Des pièces fortes pour votre intérieur.",
        sections: {
          showcase: {
            title: "Architecture & intérieur",
            text: "Transformer l'espace, élever le quotidien : des formes justes et des matières durables.",
            button: "Explorer",
          },
          trust: {
            title: "On vous accompagne à chaque étape",
            items: [
              { title: "Conseil", text: "On vous aide à choisir la bonne pièce." },
              { title: "Livraison", text: "Expédition soignée dans tout le Maroc." },
              { title: "Suivi", text: "Une équipe disponible après l'achat." },
            ],
          },
          promos: {
            items: [
              { title: "Designs innovants", text: "Des formes qui changent une pièce" },
              { title: "Espaces de vie", text: "Le confort au quotidien" },
            ],
          },
        },
      },
      {
        eyebrow: "ديكور الداخل",
        title: "فضاءات كتشبهك",
        highlight: "كتشبهك",
        text: "أثاث وقطع مصممين باش يردو كل بيت بلاصة مريحة.",
        button: "شوف المنتجات",
        secondary: "تواصل معنا",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "المنتجات المميزة",
        collectionSubtitle: "قطع قوية لدارك.",
        sections: {
          showcase: {
            title: "الهندسة والديكور",
            text: "نبدلو الفضاء ونطلعو بالمستوى ديال كل نهار: أشكال مضبوطة ومواد كتدوم.",
            button: "اكتشف",
          },
          trust: {
            title: "معاك فكل خطوة",
            items: [
              { title: "النصيحة", text: "كنعاونوك تختار القطعة المناسبة." },
              { title: "التوصيل", text: "شحن مضبوط لجميع المدن." },
              { title: "المتابعة", text: "فريق موجود حتى من بعد الشرا." },
            ],
          },
          promos: {
            items: [
              { title: "تصاميم مبتكرة", text: "أشكال كتبدل البيت" },
              { title: "فضاءات العيش", text: "الراحة فكل نهار" },
            ],
          },
        },
      },
    ),
  },
  {
    id: "s1-15",
    series: 1,
    folder: "008_Dc3YlnbjodC",
    name: "Saveur Serif",
    niche: "Restaurant & épicerie fine",
    description: "Titres serif élégants, orange vif, vert frais et cartes menu colorées.",
    theme: theme({
      bg: "#ffffff",
      surface: "#f7f7f5",
      text: "#070a00",
      primary: "#070a00",
      accent: "#f24f04",
      dark: "#070a00",
      heroBg: "#ffffff",
      heroText: "#070a00",
      radius: 18,
      headingFont: "DM Serif Display",
      bodyFont: "Inter",
      headingWeight: 400,
    }),
    header: "split",
    hero: "food",
    card: "boxed",
    categories: "tiles",
    promos: "cards",
    trust: "icons",
    sections: ["hero", "showcase", "products", "categories", "stats", "newsletter", "faq"],
    hiddenByDefault: ["testimonials"],
    copy: copy(
      {
        eyebrow: "Fait avec passion",
        title: "Un lieu où les envies sont respectées",
        highlight: "envies",
        text: "Des produits savoureux, préparés avec soin, pour transformer chaque repas en moment à part.",
        button: "Commander",
        secondary: "Voir le menu",
        announcement: "Livraison partout au Maroc · Paiement à la livraison",
        collectionTitle: "Votre plat, votre humeur",
        collectionSubtitle: "Choisissez selon vos envies du moment.",
        sections: {
          showcase: {
            eyebrow: "Notre histoire",
            title: "Un bon plat raconte une histoire — la vôtre commence ici",
            text: "Des saveurs franches, des ingrédients de qualité et une présentation soignée : c'est notre façon de cuisiner.",
          },
          stats: { title: "Notre maison" },
        },
      },
      {
        eyebrow: "مصنوع بحب",
        title: "بلاصة كتحترم الشهوة ديالك",
        highlight: "الشهوة",
        text: "منتجات بنينة، موجدة بعناية، باش كل وجبة تولي لحظة خاصة.",
        button: "طلب دابا",
        secondary: "شوف المنيو",
        announcement: "التوصيل لجميع المدن · الدفع عند الاستلام",
        collectionTitle: "الماكلة ديالك، المزاج ديالك",
        collectionSubtitle: "اختار على حساب شهوتك.",
        sections: {
          showcase: {
            eyebrow: "القصة ديالنا",
            title: "الماكلة البنينة كتحكي قصة — والقصة ديالك كتبدا هنا",
            text: "نكهات صافية، مكونات بجودة وتقديم نقي: هادي هي الطريقة ديالنا.",
          },
          stats: { title: "الدار ديالنا" },
        },
      },
    ),
  },
];
