// Templates « sur mesure » : créés à partir d'une maquette envoyée à part (hors séries de 15).
// Dans les titres de section, un mot entre *étoiles* est souligné au feutre (couleur d'accent).
import type { StoreTemplate } from "./types";
import { SHARED_AR, SHARED_FR, withShared } from "./shared-copy";

export const SUR_MESURE: StoreTemplate[] = [
  {
    id: "s90-01",
    series: 90,
    folder: "EduLearn (maquette école)",
    name: "École Vive",
    niche: "École, cours & formation",
    description:
      "Crème, vert sarcelle et orange : titres soulignés au feutre, collage photo, cartes à encoche et doodles dessinés.",
    theme: {
      bg: "#f8f7f3",
      surface: "#efeeec",
      text: "#2b2b2b",
      muted: "#6b6b6b",
      border: "#e3e1db",
      primary: "#2a7d73",
      onPrimary: "#ffffff",
      accent: "#f99d0b",
      onAccent: "#ffffff",
      dark: "#2a7d73",
      onDark: "#ffffff",
      heroBg: "#f8f7f3",
      heroText: "#2b2b2b",
      radius: 26,
      headingFont: "Inter Tight",
      bodyFont: "Hanken Grotesk",
      headingWeight: 700,
      headingTracking: "-0.035em",
    },
    header: "split",
    hero: "school",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "icons",
    layout: {
      header: "classic",
      card: "notch",
      faq: "cards",
      footer: "bar",
      shop: "topbar",
      product: "split",
      page: "simple",
    },
    sections: ["hero", "features", "photostats", "products", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    showAnnouncement: false,
    ctaPhoto: true,
    copy: {
      fr: {
        eyebrow: "Cours & formations",
        title: "Apprendre devient un plaisir",
        highlight: "devient",
        text: "Des cours clairs, des formateurs disponibles et une inscription simple : avancez à votre rythme, où que vous soyez au Maroc.",
        button: "Commencer",
        announcement: "Inscription en ligne · Réponse rapide sur WhatsApp",
        collectionTitle: "Nos *cours* à la une",
        collectionSubtitle: "Choisissez votre formation et inscrivez-vous en quelques clics.",
        sections: withShared(SHARED_FR, {
          hero: {
            items: [
              { title: "Des formateurs *qualifiés*", value: "{products}", text: "formations disponibles" },
              { title: "Des cours qui donnent envie d'apprendre" },
            ],
          },
          features: {
            title: "Une façon plus *simple* d'apprendre",
            text: "Des cours bien construits, un suivi attentif et un accompagnement sur WhatsApp : chaque élève progresse à son rythme.",
            items: [
              {
                title: "Des cours *clairs* et progressifs",
                text: "Chaque notion est expliquée pas à pas, avec des exemples concrets.",
              },
              {
                title: "Un *suivi* proche de chaque élève",
                text: "Une question ? L'équipe répond rapidement sur WhatsApp.",
              },
              {
                title: "Des objectifs *atteints*, étape par étape",
                text: "Des exercices réguliers pour vérifier vos progrès.",
              },
            ],
          },
          photostats: {
            title: "Pourquoi choisir *nos* cours ?",
            text: "Des formations sélectionnées avec soin, une inscription simple et un accompagnement humain du début à la fin.",
            items: [
              { value: "{products}", title: "Formations disponibles" },
              { value: "{categories}", title: "Domaines d'étude" },
              { value: "100%", title: "Inscription en ligne" },
            ],
          },
          testimonials: {
            title: "Ce que disent nos *élèves*",
            text: "Remplacez ces exemples par de vrais avis de vos élèves ou de leurs parents.",
          },
          faq: { title: "Questions *fréquentes*" },
          newsletter: {
            eyebrow: "Contactez-nous",
            title: "Rejoignez notre communauté d'élèves",
            text: "Une question sur une formation ou une inscription ? Écrivez-nous, on vous répond rapidement.",
            button: "Nous contacter",
          },
        }),
      },
      ar: {
        eyebrow: "دروس وتكوينات",
        title: "التعلم ولّا متعة",
        highlight: "متعة",
        text: "دروس واضحة، مكونين معاك وتسجيل ساهل: تقدم بالسرعة ديالك، فين ما كنتي فالمغرب.",
        button: "بدا دابا",
        announcement: "التسجيل أونلاين · جواب سريع فواتساب",
        collectionTitle: "الدروس *ديالنا*",
        collectionSubtitle: "ختار التكوين ديالك وسجل فبضع نقرات.",
        sections: withShared(SHARED_AR, {
          hero: {
            items: [
              { title: "مكونين *مؤهلين*", value: "{products}", text: "تكوين متوفر" },
              { title: "دروس كتحبب ليك التعلم" },
            ],
          },
          features: {
            title: "طريقة *أسهل* باش تتعلم",
            text: "دروس منظمة، تتبع قريب ومرافقة فواتساب: كل تلميذ كيتقدم بالسرعة ديالو.",
            items: [
              { title: "دروس *واضحة* وبالتدريج", text: "كل فكرة مشروحة خطوة بخطوة بأمثلة من الواقع." },
              { title: "*تتبع* قريب لكل تلميذ", text: "عندك سؤال؟ الفريق كيجاوب بسرعة فواتساب." },
              { title: "أهداف *كتوصل* ليها خطوة بخطوة", text: "تمارين منتظمة باش تشوف التقدم ديالك." },
            ],
          },
          photostats: {
            title: "علاش تختار *الدروس* ديالنا؟",
            text: "تكوينات مختارة بعناية، تسجيل ساهل ومرافقة من البداية حتى للنهاية.",
            items: [
              { value: "{products}", title: "تكوين متوفر" },
              { value: "{categories}", title: "مجال دراسة" },
              { value: "100%", title: "تسجيل أونلاين" },
            ],
          },
          testimonials: {
            title: "شنو كيقولو *التلاميذ*",
            text: "بدل هاد الأمثلة بآراء حقيقية ديال التلاميذ ولا الوالدين.",
          },
          faq: { title: "أسئلة *متكررة*" },
          newsletter: {
            eyebrow: "تواصل معانا",
            title: "انضم للمجتمع ديال التلاميذ ديالنا",
            text: "عندك سؤال على شي تكوين ولا التسجيل؟ كتب لينا ونجاوبوك بسرعة.",
            button: "تواصل معانا",
          },
        }),
      },
    },
  },
  ,
  {
    id: "s90-02",
    series: 90,
    folder: "HavenHues (maquette immobilier)",
    name: "Clé Lime",
    niche: "Immobilier, maison & décoration",
    description:
      "Grande photo plein cadre, noir et vert citron : annonces horizontales, trio de quartiers, services sur fond sombre.",
    theme: {
      bg: "#ffffff",
      surface: "#f4f4f1",
      text: "#1d1d1b",
      muted: "#8a8a84",
      border: "#e7e7e2",
      primary: "#1f1f1d",
      onPrimary: "#ffffff",
      accent: "#d5ee3b",
      onAccent: "#1d1d1b",
      dark: "#222220",
      onDark: "#ffffff",
      heroBg: "#1d2b1a",
      heroText: "#ffffff",
      radius: 14,
      headingFont: "Outfit",
      bodyFont: "Manrope",
      headingWeight: 500,
      headingTracking: "-0.02em",
    },
    header: "overlay",
    hero: "estate",
    card: "plain",
    categories: "trio",
    promos: "cards",
    trust: "icons",
    statement: "rows",
    layout: {
      header: "classic",
      card: "listing",
      faq: "numbered",
      footer: "photo",
      shop: "banner",
      product: "panel",
      page: "banner",
    },
    sections: ["hero", "statement", "products", "categories", "services", "testimonials", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    showAnnouncement: false,
    copy: {
      fr: {
        eyebrow: "Biens sélectionnés",
        title: "Ouvrez la porte de votre prochain chez-vous",
        highlight: "",
        text: "Maisons, appartements et terrains sélectionnés, visites accompagnées partout au Maroc.",
        button: "Voir les biens",
        announcement: "Visites sur rendez-vous · Réponse rapide sur WhatsApp",
        collectionTitle: "Trouvez le bien qui vous ressemble",
        collectionSubtitle: "Nos biens à la une, avec leurs points forts.",
        sections: withShared(SHARED_FR, {
          hero: {
            items: [
              { value: "{products}+", title: "Biens disponibles" },
              { value: "{categories}", title: "Quartiers" },
            ],
          },
          statement: {
            eyebrow: "À propos",
            title: "Acheter, vendre ou louer devient plus simple,",
            text: "grâce à une connaissance fine du terrain et un accompagnement de A à Z.",
            button: "Nous contacter",
            items: [
              { value: "{products}+", title: "Biens disponibles" },
              { value: "{categories}+", title: "Quartiers couverts" },
              { value: "7j/7", title: "Réponse sur WhatsApp" },
              { value: "100%", title: "Visites accompagnées" },
            ],
          },
          categories: {
            eyebrow: "Quartiers",
            title: "Des quartiers qui ont du caractère",
          },
          services: {
            eyebrow: "Nos services",
            title: "Tout ce qu'il vous faut, au même endroit",
            items: [
              { title: "Vente accompagnée", text: "Mise en valeur de votre bien et diffusion ciblée." },
              { title: "Recherche sur mesure", text: "On cherche pour vous selon votre budget." },
              { title: "Estimation", text: "Un prix juste, basé sur le marché local." },
              { title: "Aide au financement", text: "Mise en relation avec des partenaires." },
              { title: "Visites & dossiers", text: "Organisation des visites et des papiers." },
              {
                value: "{products}+",
                title: "Biens disponibles",
                text: "Acheter, louer ou investir : on vous accompagne.",
              },
            ],
          },
          testimonials: { eyebrow: "Avis clients", title: "Ce que disent nos clients" },
          faq: { eyebrow: "FAQ", title: "Questions fréquentes" },
          newsletter: {
            title: "Un projet immobilier ? Parlons-en",
            text: "Dites-nous ce que vous cherchez, on vous propose les biens qui correspondent.",
            button: "Nous contacter",
          },
        }),
      },
      ar: {
        eyebrow: "عقارات مختارة",
        title: "افتح الباب ديال الدار الجديدة ديالك",
        highlight: "",
        text: "ديور، شقق وأراضي مختارة، وزيارات مرافقة فجميع المدن.",
        button: "شوف العقارات",
        announcement: "الزيارات بموعد · جواب سريع فواتساب",
        collectionTitle: "لقا العقار اللي كيناسبك",
        collectionSubtitle: "العقارات المميزة ديالنا مع النقط القوية ديالها.",
        sections: withShared(SHARED_AR, {
          hero: {
            items: [
              { value: "{products}+", title: "عقار متوفر" },
              { value: "{categories}", title: "حي" },
            ],
          },
          statement: {
            eyebrow: "شكون حنا",
            title: "الشرا، البيع ولا الكرا ولاو ساهلين،",
            text: "بفضل معرفة مزيانة بالسوق ومرافقة من البداية حتى للنهاية.",
            button: "تواصل معانا",
            items: [
              { value: "{products}+", title: "عقار متوفر" },
              { value: "{categories}+", title: "حي" },
              { value: "7/7", title: "جواب فواتساب" },
              { value: "100%", title: "زيارات مرافقة" },
            ],
          },
          categories: { eyebrow: "الأحياء", title: "أحياء عندها طابع خاص" },
          services: {
            eyebrow: "الخدمات ديالنا",
            title: "كلشي اللي محتاج، فبلاصة وحدة",
            items: [
              { title: "بيع مرافق", text: "نبينو المزايا ديال العقار ونوصلوه للناس المناسبين." },
              { title: "بحث على حسابك", text: "كنقلبو ليك على حساب الميزانية ديالك." },
              { title: "تقييم", text: "ثمن معقول على حساب السوق المحلي." },
              { title: "مساعدة فالتمويل", text: "كنوصلوك بشركاء موثوقين." },
              { title: "الزيارات والوثائق", text: "كننظمو الزيارات والأوراق." },
              { value: "{products}+", title: "عقار متوفر", text: "شرا، كرا ولا استثمار: حنا معاك." },
            ],
          },
          testimonials: { eyebrow: "آراء الزبناء", title: "شنو كيقولو الزبناء" },
          faq: { eyebrow: "أسئلة", title: "أسئلة متكررة" },
          newsletter: {
            title: "عندك مشروع عقاري؟ نهضرو عليه",
            text: "قول لينا شنو كتقلب، ونقترحو عليك العقارات المناسبة.",
            button: "تواصل معانا",
          },
        }),
      },
    },
  },
  {
    id: "s90-03",
    series: 90,
    folder: "Dentora (maquette soins dentaires)",
    name: "Sourire Clair",
    niche: "Santé, soins & bien-être",
    description:
      "Photo arrondie encadrée, bleu clair et blanc : pastilles de services, carte expert, cartes points forts et articles.",
    theme: {
      bg: "#ffffff",
      surface: "#f3f6f8",
      text: "#111827",
      muted: "#6b7280",
      border: "#e5e9ee",
      primary: "#12a3cc",
      onPrimary: "#ffffff",
      accent: "#12a3cc",
      onAccent: "#ffffff",
      dark: "#0f1d2b",
      onDark: "#ffffff",
      heroBg: "#3e4c55",
      heroText: "#ffffff",
      radius: 18,
      headingFont: "Plus Jakarta Sans",
      bodyFont: "Inter",
      headingWeight: 600,
      headingTracking: "-0.02em",
    },
    header: "overlay",
    hero: "clinic",
    card: "plain",
    categories: "pills",
    promos: "cards",
    trust: "bar",
    statement: "inline",
    layout: {
      header: "pill",
      card: "post",
      faq: "split",
      footer: "wordmark",
      shop: "topbar",
      product: "centered",
      page: "split",
    },
    sections: ["hero", "statement", "expert", "highlights", "testimonials", "products", "faq", "newsletter"],
    hiddenByDefault: ["testimonials"],
    showAnnouncement: false,
    copy: {
      fr: {
        eyebrow: "Soins pour toute la famille",
        title: "Des soins attentifs pour toute la famille",
        highlight: "",
        text: "Des produits et des soins choisis avec des spécialistes, pour un sourire sain et confiant.",
        button: "Prendre rendez-vous",
        announcement: "Conseil gratuit sur WhatsApp · Livraison partout au Maroc",
        collectionTitle: "Nos soins et produits",
        collectionSubtitle: "Les essentiels recommandés pour prendre soin de vous.",
        sections: withShared(SHARED_FR, {
          hero: { items: [{ title: "Un sourire naturel et confiant", value: "" }] },
          statement: {
            eyebrow: "À propos",
            title: "Nous proposons des soins personnalisés",
            text: "avec des produits modernes et un accompagnement doux, pour des sourires sains et confiants.",
            button: "Nous contacter",
            items: [
              { value: "{products}", title: "Soins & produits" },
              { value: "{categories}", title: "Spécialités" },
              { value: "100%", title: "Paiement à la livraison" },
            ],
          },
          expert: {
            eyebrow: "Notre expertise",
            title: "Des soins avancés pour un sourire en bonne santé",
            text: "Des conseils personnalisés et des produits sélectionnés pour chaque besoin.",
            button: "Prendre rendez-vous",
            items: [
              {
                title: "Votre spécialiste",
                value: "Conseil & suivi",
                text: "Remplacez ce texte par la présentation de votre spécialiste ou de votre équipe.",
              },
              { value: "{products}", title: "Soins disponibles" },
              { value: "{categories}", title: "Spécialités" },
            ],
          },
          highlights: {
            title: "Pourquoi nous choisir ?",
            items: [
              { title: "Des solutions complètes" },
              { value: "Conseil gratuit", title: "Un *suivi* régulier pour garder un sourire sain" },
              { title: "Des soins tout en douceur" },
              { value: "100%", title: "Paiement à la livraison" },
            ],
          },
          testimonials: { eyebrow: "Avis", title: "Ce que disent nos patients" },
          faq: { eyebrow: "FAQ", title: "Questions fréquentes" },
          newsletter: {
            title: "Votre sourire compte : parlons-en",
            text: "Une question sur un soin ou un produit ? Écrivez-nous, on vous répond rapidement.",
            button: "Nous contacter",
          },
        }),
      },
      ar: {
        eyebrow: "عناية لكل العائلة",
        title: "عناية دقيقة لكل العائلة",
        highlight: "",
        text: "منتجات وعناية مختارة مع مختصين، باش تكون عندك ابتسامة صحية وواثقة.",
        button: "خود موعد",
        announcement: "نصيحة مجانية فواتساب · التوصيل لجميع المدن",
        collectionTitle: "العناية والمنتجات ديالنا",
        collectionSubtitle: "الأساسيات اللي كننصحو بيها باش تعتني براسك.",
        sections: withShared(SHARED_AR, {
          hero: { items: [{ title: "ابتسامة طبيعية وواثقة", value: "" }] },
          statement: {
            eyebrow: "شكون حنا",
            title: "كنقدمو عناية على حساب كل واحد",
            text: "بمنتجات حديثة ومرافقة لطيفة، باش تكون الابتسامة صحية وواثقة.",
            button: "تواصل معانا",
            items: [
              { value: "{products}", title: "عناية ومنتجات" },
              { value: "{categories}", title: "تخصصات" },
              { value: "100%", title: "الدفع عند الاستلام" },
            ],
          },
          expert: {
            eyebrow: "الخبرة ديالنا",
            title: "عناية متقدمة لابتسامة صحية",
            text: "نصائح على حسابك ومنتجات مختارة لكل حاجة.",
            button: "خود موعد",
            items: [
              { title: "المختص ديالك", value: "نصيحة وتتبع", text: "بدل هاد النص بتقديم المختص ولا الفريق ديالك." },
              { value: "{products}", title: "عناية متوفرة" },
              { value: "{categories}", title: "تخصصات" },
            ],
          },
          highlights: {
            title: "علاش تختارنا؟",
            items: [
              { title: "حلول كاملة" },
              { value: "نصيحة مجانية", title: "*تتبع* منتظم باش تبقى الابتسامة صحية" },
              { title: "عناية بلطف" },
              { value: "100%", title: "الدفع عند الاستلام" },
            ],
          },
          testimonials: { eyebrow: "آراء", title: "شنو كيقولو الزبناء" },
          faq: { eyebrow: "أسئلة", title: "أسئلة متكررة" },
          newsletter: {
            title: "الابتسامة ديالك مهمة: نهضرو",
            text: "عندك سؤال على شي عناية ولا منتج؟ كتب لينا ونجاوبوك بسرعة.",
            button: "تواصل معانا",
          },
        }),
      },
    },
  },
];
