"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
export default function ResetPassword(){
 const[p,setP]=useState(""),[confirm,setConfirm]=useState(""),[msg,setMsg]=useState(""),[ready,setReady]=useState(false),[loading,setLoading]=useState(true);
 const s=useMemo(()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!),[]);
 useEffect(()=>{let alive=true;async function init(){try{const url=new URL(window.location.href),code=url.searchParams.get("code"),hash=new URLSearchParams(url.hash.replace(/^#/,"")),accessToken=hash.get("access_token"),refreshToken=hash.get("refresh_token");if(code){const {error}=await s.auth.exchangeCodeForSession(code);if(error)throw error;url.searchParams.delete("code");history.replaceState({},document.title,url.pathname+url.search)}else if(accessToken&&refreshToken){const {error}=await s.auth.setSession({access_token:accessToken,refresh_token:refreshToken});if(error)throw error;history.replaceState({},document.title,url.pathname+url.search)}const {data,error}=await s.auth.getSession();if(error)throw error;if(alive)setReady(!!data.session)}catch(e:any){if(alive)setMsg("Lien invalide ou expiré. Demande un nouveau lien de réinitialisation.")}finally{if(alive)setLoading(false)}}init();const {data}=s.auth.onAuthStateChange((event,session)=>{if(event==="PASSWORD_RECOVERY"||session)setReady(!!session)});return()=>{alive=false;data.subscription.unsubscribe()}},[s]);
 async function submit(e:FormEvent){e.preventDefault();setMsg("");if(p.length<8){setMsg("Le mot de passe doit contenir au moins 8 caractères.");return}if(p!==confirm){setMsg("Les deux mots de passe ne correspondent pas.");return}setLoading(true);const {error}=await s.auth.updateUser({password:p});if(error){setMsg(error.message);setLoading(false);return}await s.auth.signOut();setMsg("Mot de passe modifié avec succès. Redirection vers la connexion...");setTimeout(()=>location.href="/login",1200)}
 return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#070b14",padding:24,fontFamily:"Arial,sans-serif"}}><form onSubmit={submit} style={{width:"100%",maxWidth:420,background:"#101827",border:"1px solid #243044",borderRadius:20,padding:32,color:"white"}}><div style={{width:48,height:48,borderRadius:14,display:"grid",placeItems:"center",background:"#ff6b00",fontWeight:900,fontSize:24,marginBottom:22}}>M</div><h1>Nouveau mot de passe</h1><p style={{color:"#94a3b8"}}>{loading?"Vérification du lien...":ready?"Choisis ton nouveau mot de passe.":"Ce lien n’est pas valide ou a expiré."}</p>{ready&&<><input type="password" minLength={8} autoComplete="new-password" required value={p} onChange={e=>setP(e.target.value)} placeholder="Nouveau mot de passe" style={{width:"100%",boxSizing:"border-box",padding:14,borderRadius:10,margin:"8px 0 12px",background:"#0b1220",color:"white",border:"1px solid #334155"}}/><input type="password" minLength={8} autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirmer le mot de passe" style={{width:"100%",boxSizing:"border-box",padding:14,borderRadius:10,margin:"0 0 18px",background:"#0b1220",color:"white",border:"1px solid #334155"}}/><button disabled={loading} style={{width:"100%",padding:14,border:0,borderRadius:10,background:"#ff6b00",color:"white",fontWeight:800}}>{loading?"Modification...":"Modifier le mot de passe"}</button></>}{msg&&<p style={{color:ready?"#e2e8f0":"#fca5a5"}}>{msg}</p>}<p style={{textAlign:"center"}}><a href={ready?"/login":"/forgot-password"} style={{color:"#ff8a3d"}}>{ready?"Se connecter":"Demander un nouveau lien"}</a></p></form></main>
}