import {NextResponse} from "next/server"; import {createClient} from "@supabase/supabase-js"; import OpenAI from "openai";
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SECRET_KEY;if(!u||!k)throw new Error("Supabase env missing");return createClient(u,k,{auth:{persistSession:false}})}
function slugify(s:string){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)}
function parseJson(s:string){return JSON.parse(s.replace(/```json|```/g,"").trim())}
export async function POST(req:Request){try{const p=await req.json();if(!p.name||!p.price)return NextResponse.json({error:"Nom et prix requis"},{status:400});if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:"OPENAI_API_KEY manquante dans Vercel"},{status:500});
const language=p.language||"Darija Maroc",client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const prompt=`Tu es expert e-commerce COD Maroc et directeur artistique. Analyse le produit depuis son nom et uniquement les informations fournies.\nProduit: ${p.name}\nPrix: ${p.price} MAD. Ancien prix: ${p.oldPrice||"non fourni"}. Description: ${p.description||"non fournie"}. Langue: ${language}.\nChoisis design_profile parmi automotive-tech, beauty, fashion-luxury, health-wellness, sport-fitness, home-lifestyle, electronics-tech, kids-family, general. Adapte le contenu au type de produit. N’invente aucune caractéristique, certification, statistique, avis client ni résultat. Pour santé/sport, aucune promesse médicale non prouvée. Écris en Darija naturelle en alphabet arabe quand la langue est Darija Maroc.\nRetourne UNIQUEMENT un JSON valide avec exactement ces clés: {"design_profile":"","product_category":"","headline":"","subheadline":"","description":"","benefits":["","","",""],"cta":"","delivery":"","problem_title":"","problem_text":"","features_title":"","features":[{"title":"","text":""},{"title":"","text":""},{"title":"","text":""}],"how_title":"","how_steps":["","",""],"trust_title":"","trust_points":["","",""],"guarantee":"","faq":[{"question":"","answer":""},{"question":"","answer":""},{"question":"","answer":""}]}`mport {NextResponse} from "next/server"; import {createClient} from "@supabase/supabase-js"; import OpenAI from "openai";
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SECRET_KEY;if(!u||!k)throw new Error("Supabase env missing");return createClient(u,k,{auth:{persistSession:false}})}
function slugify(s:string){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)}
function parseJson(s:string){return JSON.parse(s.replace(/```json|```/g,"").trim())}
export async function POST(req:Request){try{const p=await req.json();if(!p.name||!p.price)return NextResponse.json({error:"Nom et prix requis"},{status:400});if(!process.env.OPENAI_API_KEY)return NextResponse.json({error:"OPENAI_API_KEY manquante dans Vercel"},{status:500});
const language=p.language||"Darija Maroc",client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const prompt=`Tu es directeur artistique et expert landing pages COD Maroc. Analyse d'abord le TYPE DE PRODUIT principalement depuis son NOM.
Produit: ${p.name}
Prix: ${p.price} MAD. Ancien prix: ${p.oldPrice||"non fourni"}. Description: ${p.description||"non fournie"}. Langue: ${language}.
Choisis exactement un design_profile parmi: automotive-tech, beauty, fashion-luxury, health-wellness, sport-fitness, home-lifestyle, electronics-tech, kids-family, general.
Exemples: support/chargeur voiture ou moto => automotive-tech; montre/sac/lunettes mode => fashion-luxury; genouillère => sport-fitness ou health-wellness selon le nom.
Adapte aussi la STRUCTURE et le ton au type de produit. Pour automotive/electronics: mets en avant technologie, usage et caractéristiques. Pour beauty/fashion: bénéfice visuel, élégance et expérience. Pour health/sport: confort, usage et bénéfices sans promesse médicale non prouvée. Pour home: problème quotidien puis solution. Pour kids: simplicité, usage familial et réassurance. Génère problem_title/problem_text, 3 features avec titre+texte, how_title + 3 étapes, social_proof_title et 3 trust_points. Écris une page persuasive mais factuelle sans inventer de caractéristiques, avis clients, statistiques, certifications ou résultats. En Darija, alphabet arabe naturel.
Retourne UNIQUEMENT JSON valide avec: {"design_profile":"","product_category":"","headline":"","subheadline":"","description":"","benefits":["","","",""],"cta":"","delivery":"","problem_title":"","problem_text":"","features_title":"","features":[{"title":"","text":""},{"title":"","text":""},{"title":"","text":""}],"how_title":"","how_steps":["","",""],"social_proof_title":"","trust_points":["","",""],"problem_title":"","problem_text":"","features_title":"","features":[{"title":"","text":""},{"title":"","text":""},{"title":"","text":""}],"how_title":"","how_steps":["","",""],"trust_title":"","trust_points":["","",""],"guarantee":"","faq":[{"question":"","answer":""},{"question":"","answer":""},{"question":"","answer":""}]}`;
const ai=await client.responses.create({model:"gpt-5.6-luna",input:prompt,reasoning:{effort:"low"},store:false});const content=parseJson(ai.output_text);
const allowed=["automotive-tech","beauty","fashion-luxury","health-wellness","sport-fitness","home-lifestyle","electronics-tech","kids-family","general"];if(!allowed.includes(content.design_profile))content.design_profile="general";
const slug=slugify(p.name)+"-"+Date.now().toString().slice(-5),lang=language==="Français"?"fr-MA":language==="English"?"en":"ar-MA",supabase=db();
const {data,error}=await supabase.rpc("create_landing_product",{p_name:p.name,p_slug:slug,p_price:Number(p.price),p_old_price:p.oldPrice?Number(p.oldPrice):null,p_description:content.description||p.description||null,p_language:lang});if(error)throw error;
const {error:saveError}=await supabase.from("landing_pages").update({seo:{ai_content:content,source_url:p.sourceUrl||null,images:Array.isArray(p.imageUrls)?p.imageUrls:[]}}).eq("id",data.landing_page_id);if(saveError)throw saveError;
return NextResponse.json({page:{...content,price:p.price,oldPrice:p.oldPrice||"",slug:data.slug,url:"/landing/"+data.slug,images:Array.isArray(p.imageUrls)?p.imageUrls:[]},record:data});}catch(e:any){return NextResponse.json({error:e?.message||"Erreur génération IA"},{status:500})}}