import {NextResponse} from "next/server"; import {createClient} from "@supabase/supabase-js";import {authContext,adminDb} from "../../../lib/server-auth";
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SECRET_KEY;if(!u||!k)throw new Error("Supabase env missing");return createClient(u,k,{auth:{persistSession:false}})}
export async function GET(req:Request){try{
 const {s:supabase,workspaceId}=await authContext(req),url=new URL(req.url),requested=Number(url.searchParams.get("limit")||50),limit=Math.min(100,Math.max(1,Number.isFinite(requested)?requested:50)),cursor=url.searchParams.get("cursor");
 let ordersQuery=supabase.from("orders").select("id,order_number,lead_id,landing_page_id,product_id,quantity,unit_price,subtotal,shipping_price,discount,total,currency,shipment_status,tracking_number,delivery_company_id,carrier_city_id,carrier_city_name,shipped_at,delivered_at,returned_at,created_at").eq("workspace_id",workspaceId).order("created_at",{ascending:false}).limit(limit+1);
 if(cursor)ordersQuery=ordersQuery.lt("created_at",cursor);
 const {data:orders,error}=await ordersQuery;
 if(error)throw error;
 const fetched=orders||[],hasMore=fetched.length>limit,base=hasMore?fetched.slice(0,limit):fetched,leadIds=[...new Set(base.map((o:any)=>o.lead_id).filter(Boolean))],productIds=[...new Set(base.map((o:any)=>o.product_id).filter(Boolean))],landingIds=[...new Set(base.map((o:any)=>o.landing_page_id).filter(Boolean))],carrierIds=[...new Set(base.map((o:any)=>o.delivery_company_id).filter(Boolean))];
 const [leadsQ,productsQ,landingsQ,carriersQ]=await Promise.all([
  leadIds.length?supabase.from("leads").select("id,full_name,phone_raw,phone_e164,city_name,address,status,notes").eq("workspace_id",workspaceId).in("id",leadIds):Promise.resolve({data:[]}),
  productIds.length?supabase.from("products").select("id,name").eq("workspace_id",workspaceId).in("id",productIds):Promise.resolve({data:[]}),
  landingIds.length?supabase.from("landing_pages").select("id,name,slug").eq("workspace_id",workspaceId).in("id",landingIds):Promise.resolve({data:[]}),
  carrierIds.length?supabase.from("delivery_companies").select("id,name,code").eq("workspace_id",workspaceId).in("id",carrierIds):Promise.resolve({data:[]})
 ]);
 const by=(rows:any[]=[])=>new Map(rows.map((x:any)=>[x.id,x])),leads=by(leadsQ.data||[]),products=by(productsQ.data||[]),landings=by(landingsQ.data||[]),carriers=by(carriersQ.data||[]);
 const rows=base.map((o:any)=>({...o,lead:leads.get(o.lead_id)||null,product:products.get(o.product_id)||null,landing:landings.get(o.landing_page_id)||null,delivery_company:carriers.get(o.delivery_company_id)||null}));
 const {data:kpiOrders,error:kpiError}=await supabase.from("orders").select("total,shipment_status,tracking_number,lead_id").eq("workspace_id",workspaceId);
 if(kpiError)throw kpiError;
 const all:any[]=kpiOrders||[],allLeadIds=[...new Set(all.map((o:any)=>o.lead_id).filter(Boolean))];
 const {data:kpiLeads,error:kpiLeadsError}=allLeadIds.length?await supabase.from("leads").select("id,status").eq("workspace_id",workspaceId).in("id",allLeadIds):{data:[],error:null};
 if(kpiLeadsError)throw kpiLeadsError;
 const leadStatus=new Map((kpiLeads||[]).map((l:any)=>[l.id,l.status]));
 const kpis={total:all.length,new:all.filter(o=>leadStatus.get(o.lead_id)==="NEW").length,call:all.filter(o=>["CONTACTED","NO_ANSWER","CALL_BACK"].includes(String(leadStatus.get(o.lead_id)||""))).length,confirmed:all.filter(o=>leadStatus.get(o.lead_id)==="CONFIRMED").length,sent:all.filter(o=>!!o.tracking_number&&["PENDING","PICKED_UP","IN_TRANSIT"].includes(o.shipment_status)).length,out:all.filter(o=>o.shipment_status==="OUT_FOR_DELIVERY").length,delivered:all.filter(o=>o.shipment_status==="DELIVERED").length,returns:all.filter(o=>["FAILED","RETURNING","RETURNED","CANCELLED"].includes(o.shipment_status)).length,deliveredRevenue:all.filter(o=>o.shipment_status==="DELIVERED").reduce((sum,o)=>sum+Number(o.total||0),0)};
 return NextResponse.json({orders:rows,kpis,pagination:{limit,hasMore,nextCursor:hasMore?base[base.length-1]?.created_at||null:null}});
}catch(e:any){return NextResponse.json({error:e.message,orders:[]},{status:500})}}
export async function POST(req:Request){try{const b=await req.json();if(!b.slug||!b.name||!b.phone)return NextResponse.json({error:"Champs requis manquants"},{status:400});const s=adminDb(),slug=String(b.slug).trim(),ip=(req.headers.get("x-forwarded-for")||req.headers.get("x-real-ip")||"unknown").split(",")[0].trim();const {data:allowed,error:re}=await s.rpc("check_public_order_rate_limit",{p_key:slug+"|"+ip,p_limit:12,p_window_seconds:600});if(re)throw re;if(!allowed)return NextResponse.json({error:"Trop de tentatives. Réessayez dans quelques minutes."},{status:429,headers:{"Retry-After":"600"}});const {data:lp}=await s.from("landing_pages").select("id,status").eq("slug",slug).is("archived_at",null).maybeSingle();if(!lp||lp.status!=="PUBLISHED")return NextResponse.json({error:"Cette landing page n’est pas publiée"},{status:404});const {data,error}=await s.rpc("capture_public_order",{p_slug:slug,p_full_name:String(b.name).trim().slice(0,160),p_phone:String(b.phone).trim().slice(0,40),p_city:b.city?String(b.city).trim().slice(0,120):null,p_quantity:Math.min(10,Math.max(1,Number(b.quantity||1))),p_address:b.address?String(b.address).trim().slice(0,500):null});if(error)throw error;return NextResponse.json(data,{status:201})}catch(e:any){return NextResponse.json({error:e.message},{status:500})}}